In [1]:
print("hello abhijit")

hello abhijit

In [2]:
import pandas as pd
import numpy as np

In [4]:
df1=pd.read_csv(r"D:\code_of_digital_impersonation\unique_professional_identities_500_repaired.csv")
df2=pd.read_csv(r"D:\code_of_digital_impersonation\dataset2_500_final_v7.csv")
df3=pd.read_csv(r"D:\code_of_digital_impersonation\dataset3_500_final_v4.csv")

In [53]:
df1

,identity_id,name,role,organization,official_email,official_domain,organization_type,country,source_url,source_type
0,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,cmo@nic.in,odisha.gov.in,Government,India,https://inpr.odisha.gov.in/en/about-us/whos-wh...,Official government directory
1,ID-0002,Hemant Sharma,Additional Chief Secretary,Government of Odisha,iprsec.or@nic.in,odisha.gov.in,Government,India,https://inpr.odisha.gov.in/en/about-us/whos-wh...,Official government directory
2,ID-0003,Anuj Kumar Das Pattanaik,Director,"Information & Public Relations Department, Odisha",director-ipr.od@gov.in,odisha.gov.in,Government,India,https://inpr.odisha.gov.in/en/about-us/whos-wh...,Official government directory
3,ID-0004,Pruthwee Raj Pani,AFA-cum-Under Secretary,"Information & Public Relations Department, Odisha",pruthweeraj1970@gmail.com,odisha.gov.in,Government,India,https://inpr.odisha.gov.in/en/about-us/whos-wh...,Official government directory
4,ID-0005,Parthasarathi Mallick,PIO-cum-Under Secretary,"Information & Public Relations Department, Odisha",rti-ori@nic.in,odisha.gov.in,Government,India,https://inpr.odisha.gov.in/en/about-us/whos-wh...,Official government directory
...,...,...,...,...,...,...,...,...,...,...
495,ID-0496,Himanshu Rai,Director,IIM Indore,director@iimidr.ac.in,iimidr.ac.in,Education,India,https://www.iimidr.ac.in/about-iim-indore/dire...,Official University Website
496,ID-0497,Debashis Chatterjee,Director,IIM Kozhikode,director@iimk.ac.in,iimk.ac.in,Education,India,https://www.iimk.ac.in/faculty/administration/,Official University Website
497,ID-0498,B. Ravi,Director,"NIT Karnataka, Surathkal",director@nitk.ac.in,nitk.ac.in,Education,India,https://www.nitk.ac.in/director,Official University Website
498,ID-0499,Madan Pillutla,Dean,Indian School of Business,madan.pillutla@isb.edu,isb.edu,Education,India,https://www.isb.edu/en/about-isb/leadership.html,Official University Website
499,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,director@tifr.res.in,tifr.res.in,Education,India,https://www.tifr.res.in/director/,Official University Website

In [49]:
dataset2

,message_id,identity_id,identity_name,identity_role,organization,organization_type,organization_domain,sender_name,sender_email,receiver_name,...,urgency_level,has_link,has_attachment,link_domain_class,data_type,generation_version,generation_batch,generator_type,generation_seed,research_source
0,2f2bfd59-a7dd-4b01-b5d3-5a9a25b4b16b,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Mohan Charan Majhi,cmo@nic.in,Anita Sharma,...,NORMAL,False,False,NONE,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
1,2f3f52c3-c970-45d9-82c0-a2704a1b5b5b,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Mohan Charan Majhi,cmo@nic.in,Sneha Sen,...,NORMAL,True,False,VENDOR,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
2,2785a537-b1d6-43f8-9266-6175cfdda32b,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Sasmita Verma,sasmita.verma@induscabling.co.in,Mohan Charan Majhi,...,NORMAL,False,False,NONE,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
3,93d8a1b4-74ba-4938-b3e2-6b58cb8587a3,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Rohit Acharya,rohit.acharya@odisha.gov.in,Mohan Charan Majhi,...,NORMAL,False,False,NONE,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
4,b1dc7f51-5ffa-4fcd-a604-4149f2ace1b7,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Preeti Acharya,preetia@odisha.gov.in,Mohan Charan Majhi,...,NORMAL,True,False,PARTNER,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,c6c06265-ec84-4f85-ad24-d8043207622b,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Sandip Trivedi,director@tifr.res.in,Geeta Reddy,...,NORMAL,True,False,CLOUD,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9996,5e0145b6-6a14-4c6f-a951-a2df7f1d07a9,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Nandini Menon,nandini.menon@tifr.res.in,Sandip Trivedi,...,MEDIUM,True,False,ORG,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9997,48ceacc5-d104-4d73-8dac-9cd01c69bc43,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Itishree Dutta,itishree.dutta@icai.info,Sandip Trivedi,...,NORMAL,True,False,PARTNER,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9998,fa9f73a3-b28a-43c7-a5fc-de559cb67ed9,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Amit Iyer,amit.iyer@kpmg-office.com,Sandip Trivedi,...,NORMAL,False,False,NONE,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9999,519775e2-64f8-4628-9766-09f22ed2918b,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Sandip Trivedi,director@tifr.res.in,Prakash Trivedi,...,NORMAL,True,False,SHORTENED,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05

In [11]:
dataset3

,identity_id,identity_name,identity_role,organization,organization_type,usual_hours,usual_days,avg_messages_per_active_day,usual_sender_domain,common_recipient_type,avg_message_length,common_request_types,usual_channel,data_type
0,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,Afternoon,Weekdays,1.11,nic.in,Internal Contacts,387.8,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
1,ID-0002,Hemant Sharma,Additional Chief Secretary,Government of Odisha,Government,Morning,"Monday, Tuesday, Wednesday, Thursday, Saturday...",1.00,nic.in,Internal Contacts,453.2,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
2,ID-0003,Anuj Kumar Das Pattanaik,Director,"Information & Public Relations Department, Odisha",Government,Morning,All Days,1.00,gov.in,Internal Contacts,468.2,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
3,ID-0004,Pruthwee Raj Pani,AFA-cum-Under Secretary,"Information & Public Relations Department, Odisha",Government,Mixed,"Monday, Tuesday, Wednesday, Thursday, Friday, ...",1.11,gmail.com,Internal Contacts,496.6,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
4,ID-0005,Parthasarathi Mallick,PIO-cum-Under Secretary,"Information & Public Relations Department, Odisha",Government,Afternoon,"Monday, Wednesday, Thursday, Saturday, Sunday",1.00,nic.in,Internal Contacts,453.9,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ID-0496,Himanshu Rai,Director,IIM Indore,Education,Morning,"Monday, Tuesday, Wednesday, Saturday, Sunday",1.00,iimidr.ac.in,Internal Contacts,447.8,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
496,ID-0497,Debashis Chatterjee,Director,IIM Kozhikode,Education,Morning,"Monday, Wednesday, Thursday, Friday, Sunday",1.11,iimk.ac.in,Internal Contacts,428.6,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
497,ID-0498,B. Ravi,Director,"NIT Karnataka, Surathkal",Education,Afternoon,"Monday, Wednesday, Thursday, Friday",1.00,nitk.ac.in,Internal Contacts,411.1,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
498,ID-0499,Madan Pillutla,Dean,Indian School of Business,Education,Afternoon,"Monday, Tuesday, Wednesday, Friday, Saturday",1.00,isb.edu,Internal Contacts,421.9,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...
499,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,Afternoon,"Monday, Tuesday, Wednesday, Thursday, Friday, ...",1.00,tifr.res.in,Internal Contacts,411.5,"payment, banking/beneficiary, access/credentia...",Email,DERIVED_FROM_DATASET2_500_FINAL_V7_LEGITIMATE_...

In [12]:
print("Dataset 1 columns:")
print(df1.columns.tolist())

print("\nDataset 2 columns:")
print(df2.columns.tolist())

print("\nDataset 3 columns:")
print(df3.columns.tolist())

Dataset 1 columns:
['identity_id', 'name', 'role', 'organization', 'official_email', 'official_domain', 'organization_type', 'country', 'source_url', 'source_type']

Dataset 2 columns:
['message_id', 'identity_id', 'identity_name', 'identity_role', 'organization', 'organization_type', 'organization_domain', 'sender_name', 'sender_email', 'receiver_name', 'receiver_email', 'reply_to', 'date', 'subject', 'message', 'label', 'attack_type', 'impersonation_mechanism', 'sender_relationship', 'scenario_family', 'request_category', 'domain_match', 'reply_to_match', 'risk_signals', 'urgency_level', 'has_link', 'has_attachment', 'link_domain_class', 'data_type', 'generation_version', 'generation_batch', 'generator_type', 'generation_seed', 'research_source']

Dataset 3 columns:
['identity_id', 'identity_name', 'identity_role', 'organization', 'organization_type', 'usual_hours', 'usual_days', 'avg_messages_per_active_day', 'usual_sender_domain', 'common_recipient_type', 'avg_message_length', 'common_request_types', 'usual_channel', 'data_type']

# dataset 1 checking

In [13]:
print("Dataset 1 Shape:", df1.shape)
print("Dataset 1 Unique Identities:", df1["identity_id"].nunique())

print("\nExpected:")
print("Rows: 500")
print("Unique identities: 500")

Dataset 1 Shape: (500, 10)
Dataset 1 Unique Identities: 500

Expected:
Rows: 500
Unique identities: 500

In [14]:
duplicate_ids = df1["identity_id"].duplicated().sum()

print("Duplicate identity IDs:", duplicate_ids)
print("Expected: 0")

Duplicate identity IDs: 0
Expected: 0

In [15]:
missing_values = df1.isnull().sum()

print(missing_values)

identity_id          0
name                 0
role                 0
organization         0
official_email       0
official_domain      0
organization_type    0
country              0
source_url           0
source_type          0
dtype: int64

In [16]:
missing_values = df1.isnull().sum()

print(missing_values)

identity_id          0
name                 0
role                 0
organization         0
official_email       0
official_domain      0
organization_type    0
country              0
source_url           0
source_type          0
dtype: int64

In [17]:
duplicate_rows = df1.duplicated().sum()

print("Duplicate rows:", duplicate_rows)
print("Expected: 0")

Duplicate rows: 0
Expected: 0

In [ ]:
missing_values = df1.isnull().sum()

print(missing_values)

identity_id          0
name                 0
role                 0
organization         0
official_email       0
official_domain      0
organization_type    0
country              0
source_url           0
source_type          0
dtype: int64

In [18]:
invalid_ids = df1[
    ~df1["identity_id"].str.match(r"^ID-\d{4}$", na=False)
]

print("Invalid identity IDs:", len(invalid_ids))

if len(invalid_ids) > 0:
    display(invalid_ids[["identity_id"]])

Invalid identity IDs: 0

In [19]:
expected_ids = {f"ID-{i:04d}" for i in range(1, 501)}
actual_ids = set(df1["identity_id"])

missing_ids = expected_ids - actual_ids
extra_ids = actual_ids - expected_ids

print("Missing IDs:", len(missing_ids))
print("Extra IDs:", len(extra_ids))

if missing_ids:
    print("Missing:", sorted(missing_ids))

if extra_ids:
    print("Extra:", sorted(extra_ids))

Missing IDs: 0
Extra IDs: 0

In [20]:
text_columns = [
    "name",
    "role",
    "organization",
    "official_email",
    "official_domain",
    "organization_type",
    "country",
    "source_url",
    "source_type"
]

for col in text_columns:
    blank_count = df1[col].astype(str).str.strip().eq("").sum()
    print(f"{col}: {blank_count} blank")

name: 0 blank
role: 0 blank
organization: 0 blank
official_email: 0 blank
official_domain: 0 blank
organization_type: 0 blank
country: 0 blank
source_url: 0 blank
source_type: 0 blank

In [21]:


import re

email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_emails = df1[
    ~df1["official_email"].astype(str).str.match(
        email_pattern,
        na=False
    )
]

print("Invalid official emails:", len(invalid_emails))

if len(invalid_emails) > 0:
    display(
        invalid_emails[
            ["identity_id", "name", "official_email"]
        ]
    )

Invalid official emails: 0

In [22]:
domain_pattern = r"^(?!-)[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$"

invalid_domains = df1[
    ~df1["official_domain"].astype(str).str.match(
        domain_pattern,
        na=False
    )
]

print("Invalid official domains:", len(invalid_domains))

if len(invalid_domains) > 0:
    display(
        invalid_domains[
            ["identity_id", "name", "official_domain"]
        ]
    )

Invalid official domains: 0

In [23]:
email_domains = (
    df1["official_email"]
    .str.split("@")
    .str[-1]
    .str.lower()
    .str.strip()
)

official_domains = (
    df1["official_domain"]
    .str.lower()
    .str.strip()
)

mismatch = email_domains != official_domains

print("Email/domain mismatches:", mismatch.sum())

if mismatch.sum() > 0:
    display(
        df1.loc[
            mismatch,
            [
                "identity_id",
                "name",
                "official_email",
                "official_domain"
            ]
        ]
    )

Email/domain mismatches: 182

,identity_id,name,official_email,official_domain
0,ID-0001,Mohan Charan Majhi,cmo@nic.in,odisha.gov.in
1,ID-0002,Hemant Sharma,iprsec.or@nic.in,odisha.gov.in
2,ID-0003,Anuj Kumar Das Pattanaik,director-ipr.od@gov.in,odisha.gov.in
3,ID-0004,Pruthwee Raj Pani,pruthweeraj1970@gmail.com,odisha.gov.in
4,ID-0005,Parthasarathi Mallick,rti-ori@nic.in,odisha.gov.in
...,...,...,...,...
258,ID-0259,"Shri Bijay Kumar Prusty, IAS",gadmin.or@nic.in,odisha.gov.in
259,ID-0260,"Sri Rudra Narayan Dash, OAS",tourismsec.od@nic.in,odisha.gov.in
261,ID-0262,"Shri Girish Chandra Singh, IAS",Secretarysme.od@nic.in,odisha.gov.in
262,ID-0263,Sri Surendra Kumar Sahoo,coopsec.or@nic.in,odisha.gov.in
488,ID-0489,V. Ramgopal Rao,vc@pilani.bits-pilani.ac.in,bits-pilani.ac.in

In [24]:
mismatch_df = df1.loc[
    mismatch,
    [
        "identity_id",
        "name",
        "organization",
        "official_email",
        "official_domain"
    ]
].copy()

mismatch_df["email_domain"] = (
    mismatch_df["official_email"]
    .str.split("@")
    .str[-1]
    .str.lower()
    .str.strip()
)

print("Total mismatches:", len(mismatch_df))

print("\nTop email domains:")
display(
    mismatch_df["email_domain"]
    .value_counts()
    .head(30)
)

Total mismatches: 182

Top email domains:

email_domain
nic.in                      114
gmail.com                    27
od.gov.in                    16
gov.in                       12
pnb.co.in                     5
orissaminerals.gov.in         4
odishatourism.gov.in          1
yahoo.co.in                   1
pmuosrp.org                   1
pilani.bits-pilani.ac.in      1
Name: count, dtype: int64

In [25]:
mismatch_category = (
    mismatch_df
    .groupby("email_domain")
    .agg(
        count=("identity_id", "count"),
        organizations=("organization", "nunique"),
        examples=("organization", lambda x: " | ".join(x.dropna().astype(str).unique()[:5]))
    )
    .sort_values("count", ascending=False)
)

display(mismatch_category)

,count,organizations,examples
email_domain,,,
nic.in,114,29,Government of Odisha | Information & Public Re...
gmail.com,27,12,"Information & Public Relations Department, Odi..."
od.gov.in,16,8,"Chief Minister's Office, Odisha | Home Departm..."
gov.in,12,5,"Information & Public Relations Department, Odi..."
pnb.co.in,5,1,Punjab National Bank
orissaminerals.gov.in,4,1,Department of Steel & Mines
odishatourism.gov.in,1,1,Department of Tourism
pilani.bits-pilani.ac.in,1,1,BITS Pilani
pmuosrp.org,1,1,Works Department
yahoo.co.in,1,1,Works Department

In [26]:
gmail_records = mismatch_df[
    mismatch_df["email_domain"] == "gmail.com"
]

display(
    gmail_records[
        [
            "identity_id",
            "name",
            "role",
            "organization",
            "official_email",
            "official_domain"
        ]
    ].to_string(index=False)
)

KeyError: "['role'] not in index"

In [27]:
gmail_records = mismatch_df[
    mismatch_df["email_domain"] == "gmail.com"
]

display(
    gmail_records[
        [
            "identity_id",
            "name",
            "organization",
            "official_email",
            "official_domain"
        ]
    ].to_string(index=False)
)

"identity_id                            name                                                          organization                          official_email official_domain\n    ID-0004               Pruthwee Raj Pani                     Information & Public Relations Department, Odisha               pruthweeraj1970@gmail.com   odisha.gov.in\n    ID-0010                  Saumyajit Rout                                            Finance Department, Odisha                saumyajit.rout@gmail.com   odisha.gov.in\n    ID-0105        Dr. Nivedita Prusty, IAS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0106       Smt Chinmayee Biswal, OAS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0109    Sri Pratap Chandra Hota, IAS                          Handlooms, Textiles & Handicrafts Department                   mail.pchota@gmail.com   odisha.gov.in\n    ID-0115    Smt. Sonia Behera, OAS (SAG) Social Security & Empowerment of Persons with Disabilities Department                   ssepdodisha@gmail.com   odisha.gov.in\n    ID-0118           Smt Mamata Samantaroy                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0120           Mr. Binaya Kumar Dash                             Department of Housing & Urban Development                  dashbinaya45@gmail.com   odisha.gov.in\n    ID-0128    Smt. Soojata Misra, OAS (SS) ST & SC Development, Minorities & Backward Classes Welfare Department                       stscdev@gmail.com   odisha.gov.in\n    ID-0129          Sri Manas Ranjan Patra                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0137      Smt. Banita Dash, OFS(SAG) ST & SC Development, Minorities & Backward Classes Welfare Department                       stscdev@gmail.com   odisha.gov.in\n    ID-0139           Smt. Rashmi Kabi, OFS                                     Planning & Convergence Department                  giapncodisha@gmail.com   odisha.gov.in\n    ID-0143     Shri Bhaskar Raito OAS(SAG) Social Security & Empowerment of Persons with Disabilities Department                   ssepdodisha@gmail.com   odisha.gov.in\n    ID-0144    Sri Daridryabhanjan MM Patra                      Department of Agriculture & Farmers' Empowerment                     dbmmpatra@gmail.com   odisha.gov.in\n    ID-0150            Sri Abhijeet Routray                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0151              Sri Anshuman Nayak                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0167          Sri Shubhranshu Mishra                      Department of Agriculture & Farmers' Empowerment          addl.secretarypolicy@gmail.com   odisha.gov.in\n    ID-0170  Sri Deba Prasad Dash, OAS (SS)                         Odia Language Literature & Culture Department specialsecretarycultureodisha@gmail.com   odisha.gov.in\n    ID-0175 Shri Sukanta Kumar Pradhan, OAS                    Skill Development & Technical Education Department                     sdte.addl@gmail.com   odisha.gov.in\n    ID-0182     Smt. Madhusmita Behera, OFS                          Handlooms, Textiles & Handicrafts Department          madhusmitabehera0711@gmail.com   odisha.gov.in\n    ID-0183          Sri Arindam Dakua, IAS                             Department of Housing & Urban Development                       dmahudd@gmail.com   odisha.gov.in\n    ID-0193               Sri Ganeswar Jena                      Department of Agriculture & Farmers' Empowerment                 ganeswarjena2@gmail.com   odisha.gov.in\n    ID-0199    Sri Subrat Kumar Behera, OAS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0203         Sri Nilamani Nayak, OSS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in\n    ID-0204           Sri Saroj Kumar Sahoo                                           Department of Steel & Mines                    sksahoo667@gmail.com   odisha.gov.in\n    ID-0251              Er. Satyaban Patel                                                      Works Department                       eenhjsg@gmail.com   odisha.gov.in\n    ID-0258           Smt Mamata Nayak, OAS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com   odisha.gov.in"

In [28]:
gmail_usage = (
    gmail_records
    .groupby("official_email")
    .agg(
        identity_count=("identity_id", "count"),
        identities=("identity_id", lambda x: ", ".join(x)),
        organizations=("organization", lambda x: " | ".join(x.unique()))
    )
    .sort_values("identity_count", ascending=False)
)

display(gmail_usage)

,identity_count,identities,organizations
official_email,,,
hthdepartment@gmail.com,9,"ID-0105, ID-0106, ID-0118, ID-0129, ID-0150, I...","Handlooms, Textiles & Handicrafts Department"
stscdev@gmail.com,2,"ID-0128, ID-0137","ST & SC Development, Minorities & Backward Cla..."
ssepdodisha@gmail.com,2,"ID-0115, ID-0143",Social Security & Empowerment of Persons with ...
addl.secretarypolicy@gmail.com,1,ID-0167,Department of Agriculture & Farmers' Empowerment
dashbinaya45@gmail.com,1,ID-0120,Department of Housing & Urban Development
eenhjsg@gmail.com,1,ID-0251,Works Department
ganeswarjena2@gmail.com,1,ID-0193,Department of Agriculture & Farmers' Empowerment
dmahudd@gmail.com,1,ID-0183,Department of Housing & Urban Development
dbmmpatra@gmail.com,1,ID-0144,Department of Agriculture & Farmers' Empowerment
madhusmitabehera0711@gmail.com,1,ID-0182,"Handlooms, Textiles & Handicrafts Department"
giapncodisha@gmail.com,1,ID-0139,Planning & Convergence Department
mail.pchota@gmail.com,1,ID-0109,"Handlooms, Textiles & Handicrafts Department"
pruthweeraj1970@gmail.com,1,ID-0004,"Information & Public Relations Department, Odisha"
sdte.addl@gmail.com,1,ID-0175,Skill Development & Technical Education Depart...
saumyajit.rout@gmail.com,1,ID-0010,"Finance Department, Odisha"
specialsecretarycultureodisha@gmail.com,1,ID-0170,Odia Language Literature & Culture Department
sksahoo667@gmail.com,1,ID-0204,Department of Steel & Mines

In [29]:
gmail_org_consistency = (
    gmail_records
    .groupby("official_email")
    .agg(
        identity_count=("identity_id", "count"),
        organization_count=("organization", "nunique"),
        organizations=("organization", lambda x: " | ".join(x.unique()))
    )
    .sort_values(
        ["organization_count", "identity_count"],
        ascending=False
    )
)

display(gmail_org_consistency)

,identity_count,organization_count,organizations
official_email,,,
hthdepartment@gmail.com,9,1,"Handlooms, Textiles & Handicrafts Department"
ssepdodisha@gmail.com,2,1,Social Security & Empowerment of Persons with ...
stscdev@gmail.com,2,1,"ST & SC Development, Minorities & Backward Cla..."
addl.secretarypolicy@gmail.com,1,1,Department of Agriculture & Farmers' Empowerment
dashbinaya45@gmail.com,1,1,Department of Housing & Urban Development
dbmmpatra@gmail.com,1,1,Department of Agriculture & Farmers' Empowerment
dmahudd@gmail.com,1,1,Department of Housing & Urban Development
eenhjsg@gmail.com,1,1,Works Department
ganeswarjena2@gmail.com,1,1,Department of Agriculture & Farmers' Empowerment
giapncodisha@gmail.com,1,1,Planning & Convergence Department
madhusmitabehera0711@gmail.com,1,1,"Handlooms, Textiles & Handicrafts Department"
mail.pchota@gmail.com,1,1,"Handlooms, Textiles & Handicrafts Department"
pruthweeraj1970@gmail.com,1,1,"Information & Public Relations Department, Odisha"
saumyajit.rout@gmail.com,1,1,"Finance Department, Odisha"
sdte.addl@gmail.com,1,1,Skill Development & Technical Education Depart...
sksahoo667@gmail.com,1,1,Department of Steel & Mines
specialsecretarycultureodisha@gmail.com,1,1,Odia Language Literature & Culture Department

In [30]:
individual_gmail = gmail_records[
    gmail_records["official_email"].map(
        gmail_records["official_email"].value_counts()
    ) == 1
].copy()

individual_gmail["email_local"] = (
    individual_gmail["official_email"]
    .str.split("@")
    .str[0]
    .str.lower()
)

individual_gmail[
    [
        "identity_id",
        "name",
        "official_email",
        "email_local"
    ]
]

,identity_id,name,official_email,email_local
3,ID-0004,Pruthwee Raj Pani,pruthweeraj1970@gmail.com,pruthweeraj1970
9,ID-0010,Saumyajit Rout,saumyajit.rout@gmail.com,saumyajit.rout
108,ID-0109,"Sri Pratap Chandra Hota, IAS",mail.pchota@gmail.com,mail.pchota
119,ID-0120,Mr. Binaya Kumar Dash,dashbinaya45@gmail.com,dashbinaya45
138,ID-0139,"Smt. Rashmi Kabi, OFS",giapncodisha@gmail.com,giapncodisha
143,ID-0144,Sri Daridryabhanjan MM Patra,dbmmpatra@gmail.com,dbmmpatra
166,ID-0167,Sri Shubhranshu Mishra,addl.secretarypolicy@gmail.com,addl.secretarypolicy
169,ID-0170,"Sri Deba Prasad Dash, OAS (SS)",specialsecretarycultureodisha@gmail.com,specialsecretarycultureodisha
174,ID-0175,"Shri Sukanta Kumar Pradhan, OAS",sdte.addl@gmail.com,sdte.addl
181,ID-0182,"Smt. Madhusmita Behera, OFS",madhusmitabehera0711@gmail.com,madhusmitabehera0711
182,ID-0183,"Sri Arindam Dakua, IAS",dmahudd@gmail.com,dmahudd
192,ID-0193,Sri Ganeswar Jena,ganeswarjena2@gmail.com,ganeswarjena2
203,ID-0204,Sri Saroj Kumar Sahoo,sksahoo667@gmail.com,sksahoo667
250,ID-0251,Er. Satyaban Patel,eenhjsg@gmail.com,eenhjsg

In [31]:
print(df1["source_type"].value_counts(dropna=False))

source_type
Official government directory       193
Official Company Website            167
Official university directory        40
Official University Website          28
Official bank management page        20
Official company leadership page     10
Official Institutional Directory      9
Official Government Website           8
Official ministry directory           8
Official Regulatory Website           6
Official bank board page              5
Official RBI directory                4
Official regulator directory          2
Name: count, dtype: int64

In [32]:
url_pattern = r"^https?://.+"

invalid_source_urls = df1[
    ~df1["source_url"].astype(str).str.match(
        url_pattern,
        na=False
    )
]

print("Invalid source URLs:", len(invalid_source_urls))

if len(invalid_source_urls) > 0:
    display(
        invalid_source_urls[
            ["identity_id", "name", "source_url", "source_type"]
        ]
    )

Invalid source URLs: 0

In [33]:
print(df1["organization_type"].value_counts(dropna=False))

organization_type
Government                209
Company/Executive         160
Education                  68
Banking/Financial          37
PSU/Public Institution     18
Regulator                   8
Name: count, dtype: int64

In [36]:
government_df = df1[
    df1["organization_type"] == "Government"
].copy()

print("Government records:", len(government_df))

display(
    government_df[
        [
            "identity_id",
            "name",
            "role",
            "organization",
            "official_email",
            "official_domain",
            "source_type"
        ]
    ].head(209)
)

Government records: 209

,identity_id,name,role,organization,official_email,official_domain,source_type
0,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,cmo@nic.in,odisha.gov.in,Official government directory
1,ID-0002,Hemant Sharma,Additional Chief Secretary,Government of Odisha,iprsec.or@nic.in,odisha.gov.in,Official government directory
2,ID-0003,Anuj Kumar Das Pattanaik,Director,"Information & Public Relations Department, Odisha",director-ipr.od@gov.in,odisha.gov.in,Official government directory
3,ID-0004,Pruthwee Raj Pani,AFA-cum-Under Secretary,"Information & Public Relations Department, Odisha",pruthweeraj1970@gmail.com,odisha.gov.in,Official government directory
4,ID-0005,Parthasarathi Mallick,PIO-cum-Under Secretary,"Information & Public Relations Department, Odisha",rti-ori@nic.in,odisha.gov.in,Official government directory
...,...,...,...,...,...,...,...
467,ID-0468,N. Kalaiselvi,Director General,CSIR,kalaiselvi@csir.res.in,csir.res.in,Official Government Website
468,ID-0469,Rajiv Bahl,Director General,ICMR,rajiv.bahl@icmr.gov.in,icmr.gov.in,Official Government Website
469,ID-0470,Himanshu Pathak,Director General,ICAR,himanshu.pathak@icar.org.in,icar.org.in,Official Government Website
470,ID-0471,Jagadesh Kumar,Chairman,University Grants Commission,jagadesh.kumar@ugc.gov.in,ugc.gov.in,Official Government Website
471,ID-0472,T.G. Sitharam,Chairman,AICTE,sitharam@aicte-india.org,aicte-india.org,Official Government Website

In [37]:
government_email_domains = (
    government_df["official_email"]
    .str.split("@")
    .str[-1]
    .str.lower()
    .value_counts()
)

print("Government email domains:")
display(government_email_domains)

Government email domains:

official_email
nic.in                   113
gmail.com                 27
gov.in                    19
od.gov.in                 18
odisha.gov.in             16
orissaminerals.gov.in      4
odishatourism.gov.in       2
yahoo.co.in                1
pmuosrp.org                1
isro.gov.in                1
drdo.gov.in                1
niti.gov.in                1
csir.res.in                1
icmr.gov.in                1
icar.org.in                1
ugc.gov.in                 1
aicte-india.org            1
Name: count, dtype: int64

In [38]:
government_domain_org = (
    government_df
    .assign(
        email_domain=government_df["official_email"]
        .str.split("@")
        .str[-1]
        .str.lower()
        .str.strip()
    )
    .groupby("email_domain")
    .agg(
        identity_count=("identity_id", "count"),
        organization_count=("organization", "nunique"),
        organizations=(
            "organization",
            lambda x: " | ".join(x.dropna().unique()[:10])
        )
    )
    .sort_values("identity_count", ascending=False)
)

display(government_domain_org)

,identity_count,organization_count,organizations
email_domain,,,
nic.in,113,28,Government of Odisha | Information & Public Re...
gmail.com,27,12,"Information & Public Relations Department, Odi..."
gov.in,19,6,"Information & Public Relations Department, Odi..."
od.gov.in,18,8,"Chief Minister's Office, Odisha | Home Departm..."
odisha.gov.in,16,6,"Home Department, Odisha | Industries Departmen..."
orissaminerals.gov.in,4,1,Department of Steel & Mines
odishatourism.gov.in,2,1,Department of Tourism
aicte-india.org,1,1,AICTE
drdo.gov.in,1,1,DRDO
isro.gov.in,1,1,ISRO
icmr.gov.in,1,1,ICMR
icar.org.in,1,1,ICAR
csir.res.in,1,1,CSIR
niti.gov.in,1,1,NITI Aayog
pmuosrp.org,1,1,Works Department
ugc.gov.in,1,1,University Grants Commission
yahoo.co.in,1,1,Works Department

In [39]:
government_org_domain = (
    government_df
    .groupby("organization")
    .agg(
        identity_count=("identity_id", "count"),
        domain_count=("official_domain", "nunique"),
        domains=("official_domain", lambda x: " | ".join(x.dropna().unique()))
    )
    .sort_values(
        ["domain_count", "identity_count"],
        ascending=[False, False]
    )
)

display(government_org_domain)

,identity_count,domain_count,domains
organization,,,
Works Department,43,2,odisha.gov.in | gov.in
Department of Tourism,5,2,odisha.gov.in | odishatourism.gov.in
Department of Women and Child Development,4,2,od.gov.in | odisha.gov.in
"Micro, Small & Medium Enterprise Department",4,2,od.gov.in | odisha.gov.in
Electronics & Information Technology Department,2,2,gov.in | odisha.gov.in
Department of Steel & Mines,14,1,odisha.gov.in
"Handlooms, Textiles & Handicrafts Department",11,1,odisha.gov.in
"Home Department, Odisha",11,1,odisha.gov.in
"Chief Minister's Office, Odisha",9,1,odisha.gov.in
Ministry of Cooperation,8,1,cooperation.gov.in
Commerce & Transport Department,7,1,odisha.gov.in
Labour and Employee's State Insurance Department,6,1,odisha.gov.in
Department of Excise,5,1,odisha.gov.in
Department of Health & Family Welfare,5,1,odisha.gov.in
Department of School and Mass Education,5,1,odisha.gov.in
"Finance Department, Odisha",5,1,odisha.gov.in
Department of Agriculture & Farmers' Empowerment,4,1,odisha.gov.in
Department of Housing & Urban Development,4,1,odisha.gov.in
Science & Technology Department,4,1,odisha.gov.in
Sports & Youth Services Department,4,1,odisha.gov.in
Department of Co-operation,3,1,odisha.gov.in
Department of Public Enterprises,3,1,odisha.gov.in
Industries Department,3,1,odisha.gov.in
"Information & Public Relations Department, Odisha",3,1,odisha.gov.in
Law Department,3,1,odisha.gov.in
Panchayati Raj & Drinking Water Department,3,1,odisha.gov.in
"ST & SC Development, Minorities & Backward Classes Welfare Department",3,1,odisha.gov.in
Social Security & Empowerment of Persons with Disabilities Department,3,1,odisha.gov.in
Department of General Administration & Public Grievance,2,1,odisha.gov.in
Energy Department,2,1,odisha.gov.in
Finance Department,2,1,odisha.gov.in
"Forest, Environment and Climate Change Department",2,1,odisha.gov.in
Government of Odisha,2,1,odisha.gov.in
Skill Development & Technical Education Department,2,1,odisha.gov.in
AICTE,1,1,aicte-india.org
CSIR,1,1,csir.res.in
DRDO,1,1,drdo.gov.in
Department of Water Resources,1,1,odisha.gov.in
Fisheries & Animal Resources Development Department,1,1,odisha.gov.in
ICAR,1,1,icar.org.in
ICMR,1,1,icmr.gov.in
ISRO,1,1,isro.gov.in
NITI Aayog,1,1,niti.gov.in
Odia Language Literature & Culture Department,1,1,odisha.gov.in
Parliamentary Affairs Department,1,1,odisha.gov.in
Planning & Convergence Department,1,1,odisha.gov.in
University Grants Commission,1,1,ugc.gov.in

In [42]:
tourism_records = government_df[
    government_df["organization"] == "Department of Tourism"
].copy()

display(
    tourism_records[
        [
            "identity_id",
            "name",
            "role",
            "official_email",
            "official_domain",
            "source_url",
            "source_type"
        ]
    ].to_string(index=False)
)

'identity_id                        name                 role                  official_email      official_domain                                            source_url                   source_type\n    ID-0141   Dr. Jagadish Sarangi, OAS     Deputy Secretary            tourismsec.od@nic.in        odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0160      Shri Manoj Behera, OAS     Deputy Secretary            tourismsec.od@nic.in        odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0195 Sri Saroja Kumar Swain, OAS Additional Secretary       info@odishatourism.gov.in        odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0208   Sri Biswajit Routray, OTS  Additional Director ad.tourism@odishatourism.gov.in odishatourism.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0260 Sri Rudra Narayan Dash, OAS Additional Secretary            tourismsec.od@nic.in        odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory'

In [43]:
wcd_records = government_df[
    government_df["organization"] ==
    "Department of Women and Child Development"
].copy()

display(
    wcd_records[
        [
            "identity_id",
            "name",
            "role",
            "official_email",
            "official_domain",
            "source_url",
            "source_type"
        ]
    ].to_string(index=False)
)

'identity_id                                    name                       role      official_email official_domain                                            source_url                   source_type\n    ID-0102              Dr. Mrinalini Darswal, IAS Commissioner-cum-Secretary wcdsec.or@od.gov.in       od.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0146                Sri Krutibash Routh, OAS       Additional Secretary wcdsec.or@od.gov.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0152 Smt. Sumitra Kumari Pattnaik, OAS (SAG)       Additional Secretary wcdsec.or@od.gov.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0154         Sri Bibekananda Sahoo, OAS(SAG)       Additional Secretary wcdsec.or@od.gov.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory'

In [44]:
msme_records = government_df[
    government_df["organization"] ==
    "Micro, Small & Medium Enterprise Department"
].copy()

display(
    msme_records[
        [
            "identity_id",
            "name",
            "role",
            "official_email",
            "official_domain",
            "source_url",
            "source_type"
        ]
    ].to_string(index=False)
)

'identity_id                       name                           role         official_email official_domain                                            source_url                   source_type\n    ID-0103    Ms. Rashmita Panda, IAS     Commissioner-cum-Secretary secy-msme.od@od.gov.in       od.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0161   Shri Chandrapati Pradhan Deputy Secretary to Government secy-msme.od@od.gov.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0197         Shri Bhagala Sirka                Joint Secretary secy-msme.od@od.gov.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0257 Shri Narayan Chandra Nayak                Joint Secretary secy-msme.od@od.gov.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory'

In [45]:
eit_records = government_df[
    government_df["organization"] ==
    "Electronics & Information Technology Department"
].copy()

display(
    eit_records[
        [
            "identity_id",
            "name",
            "role",
            "official_email",
            "official_domain",
            "source_url",
            "source_type"
        ]
    ].to_string(index=False)
)

'identity_id                                 name                                role         official_email official_domain                                            source_url                   source_type\n    ID-0114                 Shri Sabyasachi Hota  Additional Secretary to Government sabyasachi.hota@gov.in          gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0207 Smt. Shanti Sudha Kanungo, OFS (SAG) FA-cum-Additional Secretary to Govt        itsec.od@nic.in   odisha.gov.in https://odisha.gov.in/en/about-us/whos-who/department Official government directory'

In [46]:
from urllib.parse import urlparse

government_df["source_domain"] = government_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower()
)

display(
    government_df[
        ["organization", "official_domain", "source_domain"]
    ].drop_duplicates()
    .sort_values(["organization", "official_domain"])
    .to_string(index=False)
)

"                                                         organization      official_domain          source_domain\n                                                                AICTE      aicte-india.org    www.aicte-india.org\n                                                                 CSIR          csir.res.in        www.csir.res.in\n                                      Chief Minister's Office, Odisha        odisha.gov.in          odisha.gov.in\n                                      Commerce & Transport Department        odisha.gov.in          odisha.gov.in\n                                                                 DRDO          drdo.gov.in        www.drdo.gov.in\n                     Department of Agriculture & Farmers' Empowerment        odisha.gov.in          odisha.gov.in\n                                           Department of Co-operation        odisha.gov.in          odisha.gov.in\n                                                 Department of Excise        odisha.gov.in          odisha.gov.in\n              Department of General Administration & Public Grievance        odisha.gov.in          odisha.gov.in\n                                Department of Health & Family Welfare        odisha.gov.in          odisha.gov.in\n                            Department of Housing & Urban Development        odisha.gov.in          odisha.gov.in\n                                     Department of Public Enterprises        odisha.gov.in          odisha.gov.in\n                              Department of School and Mass Education        odisha.gov.in          odisha.gov.in\n                                          Department of Steel & Mines        odisha.gov.in          odisha.gov.in\n                                                Department of Tourism        odisha.gov.in          odisha.gov.in\n                                                Department of Tourism odishatourism.gov.in          odisha.gov.in\n                                        Department of Water Resources        odisha.gov.in          odisha.gov.in\n                            Department of Women and Child Development            od.gov.in          odisha.gov.in\n                            Department of Women and Child Development        odisha.gov.in          odisha.gov.in\n                      Electronics & Information Technology Department               gov.in          odisha.gov.in\n                      Electronics & Information Technology Department        odisha.gov.in          odisha.gov.in\n                                                    Energy Department        odisha.gov.in          odisha.gov.in\n                                                   Finance Department        odisha.gov.in          odisha.gov.in\n                                           Finance Department, Odisha        odisha.gov.in  finance.odisha.gov.in\n                  Fisheries & Animal Resources Development Department        odisha.gov.in          odisha.gov.in\n                    Forest, Environment and Climate Change Department        odisha.gov.in          odisha.gov.in\n                                                 Government of Odisha        odisha.gov.in     inpr.odisha.gov.in\n                         Handlooms, Textiles & Handicrafts Department        odisha.gov.in          odisha.gov.in\n                                              Home Department, Odisha        odisha.gov.in     home.odisha.gov.in\n                                                                 ICAR          icar.org.in            icar.org.in\n                                                                 ICMR          icmr.gov.in       main.icmr.nic.in\n                                                                 ISRO          isro.gov.in        www.isro.gov.in\n                                                Industries Department        odisha.gov.in          odisha.gov.in\n                    Information & Public Relations Department, Odisha        odisha.gov.in     inpr.odisha.gov.in\n                     Labour and Employee's State Insurance Department        odisha.gov.in          odisha.gov.in\n                                                       Law Department        odisha.gov.in          odisha.gov.in\n                          Micro, Small & Medium Enterprise Department            od.gov.in          odisha.gov.in\n                          Micro, Small & Medium Enterprise Department        odisha.gov.in          odisha.gov.in\n                                              Ministry of Cooperation   cooperation.gov.in www.cooperation.gov.in\n                                                           NITI Aayog          niti.gov.in        www.niti.gov.in\n                        Odia Language Literature & Culture Department        odisha.gov.in          odisha.gov.in\n                           Panchayati Raj & Drinking Water Department        odisha.gov.in          odisha.gov.in\n                                     Parliamentary Affairs Department        odisha.gov.in          odisha.gov.in\n                                    Planning & Convergence Department        odisha.gov.in          odisha.gov.in\nST & SC Development, Minorities & Backward Classes Welfare Department        odisha.gov.in          odisha.gov.in\n                                      Science & Technology Department        odisha.gov.in          odisha.gov.in\n                   Skill Development & Technical Education Department        odisha.gov.in          odisha.gov.in\nSocial Security & Empowerment of Persons with Disabilities Department        odisha.gov.in          odisha.gov.in\n                                   Sports & Youth Services Department        odisha.gov.in          odisha.gov.in\n                                         University Grants Commission           ugc.gov.in         www.ugc.gov.in\n                                                     Works Department               gov.in          odisha.gov.in\n                                                     Works Department        odisha.gov.in          odisha.gov.in"

In [48]:
[x for x in globals() if hasattr(globals()[x], "columns") and "organization_type" in globals()[x].columns]

['__',
 '___',
 'dataset1',
 '_4',
 'dataset2',
 'dataset3',
 '_6',
 '_7',
 'df1',
 'df2',
 'df3',
 '_9',
 '_10',
 '_11',
 'invalid_ids',
 'invalid_emails',
 'invalid_domains',
 'invalid_source_urls',
 'government_df',
 'works_records',
 'tourism_records',
 'wcd_records',
 'msme_records',
 'eit_records']

In [54]:
company_df = dataset1[
    dataset1["organization_type"] == "Company/Executive"
].copy()

company_df["source_domain"] = company_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower()
)

display(
    company_df[
        ["organization", "official_domain", "source_domain"]
    ].drop_duplicates()
    .sort_values(["organization", "official_domain"])
    .to_string(index=False)
)

"                   organization        official_domain              source_domain\n                      ABB India                abb.com                new.abb.com\n                Accenture India          accenture.com          www.accenture.com\n                    Adani Group              adani.com              www.adani.com\n             Aditya Birla Group        adityabirla.com        www.adityabirla.com\n                          Adobe              adobe.com              www.adobe.com\n                   Airtel India              airtel.in              www.airtel.in\n                         Amazon              amazon.in         www.aboutamazon.in\n                   Amazon India              amazon.in         www.aboutamazon.in\n      Amazon Web Services India         aws.amazon.com         www.aboutamazon.in\n               Apollo Hospitals    apollohospitals.com    www.apollohospitals.com\n                   Asian Paints        asianpaints.com        www.asianpaints.com\n                         BYJU'S              byjus.com                  byjus.com\n                     Bajaj Auto          bajajauto.com          www.bajajauto.com\n                  Bajaj Finance        bajajfinserv.in        www.bajajfinserv.in\n                  Bharti Airtel              airtel.in              www.airtel.in\n                         Biocon             biocon.com             www.biocon.com\n                      Birlasoft          birlasoft.com          www.birlasoft.com\n              Bosch Group India               bosch.in               www.bosch.in\n                           CRED              cred.club                  cred.club\n                Capgemini India          capgemini.com          www.capgemini.com\n                          Cipla              cipla.com              www.cipla.com\n                    Cisco India              cisco.com              www.cisco.com\n                Coca-Cola India          coca-cola.com          www.coca-cola.com\n                        Coforge            coforge.com            www.coforge.com\n                      Cognizant          cognizant.com          www.cognizant.com\n                Cognizant India          cognizant.com          www.cognizant.com\n        Colgate-Palmolive India colgatepalmolive.co.in www.colgatepalmolive.co.in\n                         Cyient             cyient.com             www.cyient.com\n                    Dabur India              dabur.com              www.dabur.com\n                      Delhivery          delhivery.com          www.delhivery.com\n        Dell Technologies India               dell.com               www.dell.com\n                 Deloitte India           deloitte.com          www2.deloitte.com\n            Divi's Laboratories          divislabs.com          www.divislabs.com\n               Dr. Lal PathLabs        lalpathlabs.com        www.lalpathlabs.com\n       Dr. Reddy's Laboratories           drreddys.com           www.drreddys.com\n                       Flipkart           flipkart.com           www.flipkart.com\n                     Freshworks         freshworks.com         www.freshworks.com\n       Godrej Consumer Products           godrejcp.com           www.godrejcp.com\n              Godrej Industries   godrejindustries.com   www.godrejindustries.com\n        Godrej Industries Group   godrejindustries.com   www.godrejindustries.com\n             Google Cloud India             google.com               about.google\n                   Google India             google.com               about.google\n              Grasim Industries             grasim.com             www.grasim.com\n                        HCLTech            hcltech.com            www.hcltech.com\n            HDFC Life Insurance           hdfclife.com           www.hdfclife.com\n                       HP India                 hp.com                 www.hp.com\n                  Havells India            havells.com            www.havells.com\n                  Hero MotoCorp       heromotocorp.com       www.heromotocorp.com\n          Hexaware Technologies           hexaware.com               hexaware.com\n     Hindustan Unilever Limited              hul.co.in              www.hul.co.in\n                Honeywell India          honeywell.com          www.honeywell.com\n                      IBM India                ibm.com                www.ibm.com\nICICI Prudential Life Insurance       iciciprulife.com       www.iciciprulife.com\n                    ITC Limited          itcportal.com          www.itcportal.com\n                        Infosys            infosys.com            www.infosys.com\n                    Infosys BPM         infosysbpm.com         www.infosysbpm.com\n                    Intel India               intel.in               www.intel.in\n                     JSW Energy                 jsw.in                 www.jsw.in\n                      JSW Steel                 jsw.in                 www.jsw.in\n                  Jio Platforms                jio.com                www.jio.com\n              KPIT Technologies               kpit.com               www.kpit.com\n           Kotak Mahindra Group              kotak.com              www.kotak.com\n           LG Electronics India                 lg.com                 www.lg.com\n                    LTIMindtree        ltimindtree.com        www.ltimindtree.com\n                Larsen & Toubro       larsentoubro.com       www.larsentoubro.com\n                          Lupin              lupin.com              www.lupin.com\n                 Mahindra Group           mahindra.com           www.mahindra.com\n                 Marico Limited             marico.com                 marico.com\n            Maruti Suzuki India       marutisuzuki.com       www.marutisuzuki.com\n               Mastercard India         mastercard.com         www.mastercard.com\n                 Max Healthcare       maxhealthcare.in       www.maxhealthcare.in\n             Max Life Insurance   maxlifeinsurance.com   www.maxlifeinsurance.com\n                         Meesho             meesho.com                 meesho.com\n                Microsoft India          microsoft.com         news.microsoft.com\n                        Mphasis            mphasis.com            www.mphasis.com\n                   Nestle India              nestle.in              www.nestle.in\n         Nykaa (FSN E-Commerce)              nykaa.com              www.nykaa.com\n                      OYO Rooms           oyorooms.com           www.oyorooms.com\n                   Ola Electric        olaelectric.com        www.olaelectric.com\n                   Oracle India             oracle.com             www.oracle.com\n      PB Fintech (PolicyBazaar)       policybazaar.com       www.policybazaar.com\n   Paytm (One97 Communications)              paytm.com                  paytm.com\n                  PepsiCo India     pepsicoindia.co.in            www.pepsico.com\n             Persistent Systems         persistent.com         www.persistent.com\n                        PhonePe            phonepe.com            www.phonepe.com\n            Pidilite Industries           pidilite.com           www.pidilite.com\n         Procter & Gamble India                 pg.com                 www.pg.com\n                       Razorpay           razorpay.com               razorpay.com\n            Reliance Industries                ril.com                www.ril.com\n          Reliance Jio Infocomm                jio.com                www.jio.com\n                      SAP India                sap.com                www.sap.com\n             SBI Life Insurance          sbilife.co.in          www.sbilife.co.in\n               Salesforce India         salesforce.com         www.salesforce.com\n                  Samsung India            samsung.com            www.samsung.com\n       Schneider Electric India                 se.com                 www.se.com\n               ServiceNow India         servicenow.com         www.servicenow.com\n                  Siemens India            siemens.com            www.siemens.com\n                     Sony India             sony.co.in             www.sony.co.in\n  Sun Pharmaceutical Industries          sunpharma.com          www.sunpharma.com\n                         Swiggy             swiggy.com             www.swiggy.com\n        TML Commercial Vehicles         tatamotors.com         www.tatamotors.com\n              TVS Motor Company           tvsmotor.com           www.tvsmotor.com\n      Tata Consultancy Services                tcs.com                www.tcs.com\n         Tata Consumer Products       tataconsumer.com       www.tataconsumer.com\n                    Tata Motors         tatamotors.com         www.tatamotors.com\n                      Tata Sons               tata.com               www.tata.com\n                     Tata Steel          tatasteel.com          www.tatasteel.com\n                    Tata Trusts               tata.com               www.tata.com\n                  Tech Mahindra       techmahindra.com       www.techmahindra.com\n                  Titan Company        titancompany.in        www.titancompany.in\n        Torrent Pharmaceuticals      torrentpharma.com      www.torrentpharma.com\n                     Uber India               uber.com               www.uber.com\n               UltraTech Cement    ultratechcement.com    www.ultratechcement.com\n                Vedanta Limited     vedantalimited.com     www.vedantalimited.com\n                     Visa India               visa.com             www.visa.co.in\n                          Wipro              wipro.com              www.wipro.com\n            Zensar Technologies             zensar.com             www.zensar.com\n                        Zerodha            zerodha.com                zerodha.com\n               Zoho Corporation               zoho.com               www.zoho.com\n                         Zomato             zomato.com             www.zomato.com"

In [55]:
amazon_records = company_df[
    company_df["organization"].isin([
        "Amazon",
        "Amazon India",
        "Amazon Web Services India"
    ])
].copy()

display(
    amazon_records[
        [
            "identity_id",
            "name",
            "role",
            "official_email",
            "official_domain",
            "source_url",
            "source_type"
        ]
    ].to_string(index=False)
)

'identity_id               name                                    role               official_email official_domain                                   source_url              source_type\n    ID-0273        Samir Kumar                         Country Manager        samir.kumar@amazon.in       amazon.in https://www.aboutamazon.in/news/company-news Official Company Website\n    ID-0274       Amit Agarwal Senior Vice President, Emerging Markets       amit.agarwal@amazon.in       amazon.in https://www.aboutamazon.in/news/company-news Official Company Website\n    ID-0275      Sandeep Dutta           President, India & South Asia sandeep.dutta@aws.amazon.com  aws.amazon.com https://www.aboutamazon.in/news/company-news Official Company Website\n    ID-0276 Saurabh Srivastava                 VP, Category Leadership saurabh.srivastava@amazon.in       amazon.in https://www.aboutamazon.in/news/company-news Official Company Website'

In [56]:
from urllib.parse import urlparse

# Company / Executive records
company_df = dataset1[
    dataset1["organization_type"] == "Company/Executive"
].copy()

# Extract source domain
company_df["source_domain"] = company_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower().replace("www.", "")
)

# Normalize official domain
company_df["official_domain_clean"] = (
    company_df["official_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

# Normalize source domain
company_df["source_domain_clean"] = (
    company_df["source_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

# Exact domain match
company_df["domain_match"] = (
    company_df["official_domain_clean"]
    == company_df["source_domain_clean"]
)

# Display all domain relationships
company_domain_check = (
    company_df[
        [
            "organization",
            "official_domain_clean",
            "source_domain_clean",
            "domain_match"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["domain_match", "organization"],
        ascending=[True, True]
    )
)

print("Total Company/Executive records:", len(company_df))
print(
    "Organizations:",
    company_df["organization"].nunique()
)
print(
    "Exact domain matches:",
    company_domain_check["domain_match"].sum()
)
print(
    "Domain mismatches:",
    (~company_domain_check["domain_match"]).sum()
)

display(company_domain_check.to_string(index=False))

Total Company/Executive records: 160
Organizations: 120
Exact domain matches: 110
Domain mismatches: 10

"                   organization  official_domain_clean    source_domain_clean  domain_match\n                      ABB India                abb.com            new.abb.com         False\n                         Amazon              amazon.in         aboutamazon.in         False\n                   Amazon India              amazon.in         aboutamazon.in         False\n      Amazon Web Services India         aws.amazon.com         aboutamazon.in         False\n                 Deloitte India           deloitte.com      www2.deloitte.com         False\n             Google Cloud India             google.com           about.google         False\n                   Google India             google.com           about.google         False\n                Microsoft India          microsoft.com     news.microsoft.com         False\n                  PepsiCo India     pepsicoindia.co.in            pepsico.com         False\n                     Visa India               visa.com             visa.co.in         False\n                Accenture India          accenture.com          accenture.com          True\n                    Adani Group              adani.com              adani.com          True\n             Aditya Birla Group        adityabirla.com        adityabirla.com          True\n                          Adobe              adobe.com              adobe.com          True\n                   Airtel India              airtel.in              airtel.in          True\n               Apollo Hospitals    apollohospitals.com    apollohospitals.com          True\n                   Asian Paints        asianpaints.com        asianpaints.com          True\n                         BYJU'S              byjus.com              byjus.com          True\n                     Bajaj Auto          bajajauto.com          bajajauto.com          True\n                  Bajaj Finance        bajajfinserv.in        bajajfinserv.in          True\n                  Bharti Airtel              airtel.in              airtel.in          True\n                         Biocon             biocon.com             biocon.com          True\n                      Birlasoft          birlasoft.com          birlasoft.com          True\n              Bosch Group India               bosch.in               bosch.in          True\n                           CRED              cred.club              cred.club          True\n                Capgemini India          capgemini.com          capgemini.com          True\n                          Cipla              cipla.com              cipla.com          True\n                    Cisco India              cisco.com              cisco.com          True\n                Coca-Cola India          coca-cola.com          coca-cola.com          True\n                        Coforge            coforge.com            coforge.com          True\n                      Cognizant          cognizant.com          cognizant.com          True\n                Cognizant India          cognizant.com          cognizant.com          True\n        Colgate-Palmolive India colgatepalmolive.co.in colgatepalmolive.co.in          True\n                         Cyient             cyient.com             cyient.com          True\n                    Dabur India              dabur.com              dabur.com          True\n                      Delhivery          delhivery.com          delhivery.com          True\n        Dell Technologies India               dell.com               dell.com          True\n            Divi's Laboratories          divislabs.com          divislabs.com          True\n               Dr. Lal PathLabs        lalpathlabs.com        lalpathlabs.com          True\n       Dr. Reddy's Laboratories           drreddys.com           drreddys.com          True\n                       Flipkart           flipkart.com           flipkart.com          True\n                     Freshworks         freshworks.com         freshworks.com          True\n       Godrej Consumer Products           godrejcp.com           godrejcp.com          True\n              Godrej Industries   godrejindustries.com   godrejindustries.com          True\n        Godrej Industries Group   godrejindustries.com   godrejindustries.com          True\n              Grasim Industries             grasim.com             grasim.com          True\n                        HCLTech            hcltech.com            hcltech.com          True\n            HDFC Life Insurance           hdfclife.com           hdfclife.com          True\n                       HP India                 hp.com                 hp.com          True\n                  Havells India            havells.com            havells.com          True\n                  Hero MotoCorp       heromotocorp.com       heromotocorp.com          True\n          Hexaware Technologies           hexaware.com           hexaware.com          True\n     Hindustan Unilever Limited              hul.co.in              hul.co.in          True\n                Honeywell India          honeywell.com          honeywell.com          True\n                      IBM India                ibm.com                ibm.com          True\nICICI Prudential Life Insurance       iciciprulife.com       iciciprulife.com          True\n                    ITC Limited          itcportal.com          itcportal.com          True\n                        Infosys            infosys.com            infosys.com          True\n                    Infosys BPM         infosysbpm.com         infosysbpm.com          True\n                    Intel India               intel.in               intel.in          True\n                     JSW Energy                 jsw.in                 jsw.in          True\n                      JSW Steel                 jsw.in                 jsw.in          True\n                  Jio Platforms                jio.com                jio.com          True\n              KPIT Technologies               kpit.com               kpit.com          True\n           Kotak Mahindra Group              kotak.com              kotak.com          True\n           LG Electronics India                 lg.com                 lg.com          True\n                    LTIMindtree        ltimindtree.com        ltimindtree.com          True\n                Larsen & Toubro       larsentoubro.com       larsentoubro.com          True\n                          Lupin              lupin.com              lupin.com          True\n                 Mahindra Group           mahindra.com           mahindra.com          True\n                 Marico Limited             marico.com             marico.com          True\n            Maruti Suzuki India       marutisuzuki.com       marutisuzuki.com          True\n               Mastercard India         mastercard.com         mastercard.com          True\n                 Max Healthcare       maxhealthcare.in       maxhealthcare.in          True\n             Max Life Insurance   maxlifeinsurance.com   maxlifeinsurance.com          True\n                         Meesho             meesho.com             meesho.com          True\n                        Mphasis            mphasis.com            mphasis.com          True\n                   Nestle India              nestle.in              nestle.in          True\n         Nykaa (FSN E-Commerce)              nykaa.com              nykaa.com          True\n                      OYO Rooms           oyorooms.com           oyorooms.com          True\n                   Ola Electric        olaelectric.com        olaelectric.com          True\n                   Oracle India             oracle.com             oracle.com          True\n      PB Fintech (PolicyBazaar)       policybazaar.com       policybazaar.com          True\n   Paytm (One97 Communications)              paytm.com              paytm.com          True\n             Persistent Systems         persistent.com         persistent.com          True\n                        PhonePe            phonepe.com            phonepe.com          True\n            Pidilite Industries           pidilite.com           pidilite.com          True\n         Procter & Gamble India                 pg.com                 pg.com          True\n                       Razorpay           razorpay.com           razorpay.com          True\n            Reliance Industries                ril.com                ril.com          True\n          Reliance Jio Infocomm                jio.com                jio.com          True\n                      SAP India                sap.com                sap.com          True\n             SBI Life Insurance          sbilife.co.in          sbilife.co.in          True\n               Salesforce India         salesforce.com         salesforce.com          True\n                  Samsung India            samsung.com            samsung.com          True\n       Schneider Electric India                 se.com                 se.com          True\n               ServiceNow India         servicenow.com         servicenow.com          True\n                  Siemens India            siemens.com            siemens.com          True\n                     Sony India             sony.co.in             sony.co.in          True\n  Sun Pharmaceutical Industries          sunpharma.com          sunpharma.com          True\n                         Swiggy             swiggy.com             swiggy.com          True\n        TML Commercial Vehicles         tatamotors.com         tatamotors.com          True\n              TVS Motor Company           tvsmotor.com           tvsmotor.com          True\n      Tata Consultancy Services                tcs.com                tcs.com          True\n         Tata Consumer Products       tataconsumer.com       tataconsumer.com          True\n                    Tata Motors         tatamotors.com         tatamotors.com          True\n                      Tata Sons               tata.com               tata.com          True\n                     Tata Steel          tatasteel.com          tatasteel.com          True\n                    Tata Trusts               tata.com               tata.com          True\n                  Tech Mahindra       techmahindra.com       techmahindra.com          True\n                  Titan Company        titancompany.in        titancompany.in          True\n        Torrent Pharmaceuticals      torrentpharma.com      torrentpharma.com          True\n                     Uber India               uber.com               uber.com          True\n               UltraTech Cement    ultratechcement.com    ultratechcement.com          True\n                Vedanta Limited     vedantalimited.com     vedantalimited.com          True\n                          Wipro              wipro.com              wipro.com          True\n            Zensar Technologies             zensar.com             zensar.com          True\n                        Zerodha            zerodha.com            zerodha.com          True\n               Zoho Corporation               zoho.com               zoho.com          True\n                         Zomato             zomato.com             zomato.com          True"

In [57]:
education_df = dataset1[
    dataset1["organization_type"] == "Education"
].copy()

education_df["source_domain"] = education_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower().replace("www.", "")
)

education_df["official_domain_clean"] = (
    education_df["official_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

education_df["source_domain_clean"] = (
    education_df["source_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

education_df["domain_match"] = (
    education_df["official_domain_clean"]
    == education_df["source_domain_clean"]
)

education_domain_check = (
    education_df[
        [
            "organization",
            "official_domain_clean",
            "source_domain_clean",
            "domain_match"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["domain_match", "organization"],
        ascending=[True, True]
    )
)

print("Total Education records:", len(education_df))
print("Organizations:", education_df["organization"].nunique())
print("Exact domain matches:", education_domain_check["domain_match"].sum())
print("Domain mismatches:", (~education_domain_check["domain_match"]).sum())

display(education_domain_check.to_string(index=False))

Total Education records: 68
Organizations: 29
Exact domain matches: 28
Domain mismatches: 1

'                          organization official_domain_clean source_domain_clean  domain_match\n                             IIT Delhi            iitd.ac.in     home.iitd.ac.in         False\n                           AIIMS Delhi             aiims.edu           aiims.edu          True\n                           BITS Pilani     bits-pilani.ac.in   bits-pilani.ac.in          True\n              Banaras Hindu University             bhu.ac.in           bhu.ac.in          True\n                                 IGNOU           ignou.ac.in         ignou.ac.in          True\n                         IIM Ahmedabad            iima.ac.in          iima.ac.in          True\n                         IIM Bangalore            iimb.ac.in          iimb.ac.in          True\n                          IIM Calcutta          iimcal.ac.in        iimcal.ac.in          True\n                            IIM Indore          iimidr.ac.in        iimidr.ac.in          True\n                         IIM Kozhikode            iimk.ac.in          iimk.ac.in          True\n                           IIM Lucknow            iiml.ac.in          iiml.ac.in          True\n                        IISc Bangalore            iisc.ac.in          iisc.ac.in          True\n                       IIT Bhubaneswar          iitbbs.ac.in        iitbbs.ac.in          True\n                            IIT Bombay            iitb.ac.in          iitb.ac.in          True\n                          IIT Guwahati            iitg.ac.in          iitg.ac.in          True\n                         IIT Hyderabad            iith.ac.in          iith.ac.in          True\n                            IIT Kanpur            iitk.ac.in          iitk.ac.in          True\n                         IIT Kharagpur          iitkgp.ac.in        iitkgp.ac.in          True\n                            IIT Madras            iitm.ac.in          iitm.ac.in          True\n                           IIT Roorkee            iitr.ac.in          iitr.ac.in          True\n             Indian School of Business               isb.edu             isb.edu          True\n           Jawaharlal Nehru University             jnu.ac.in           jnu.ac.in          True\n                                 NIEPA           niepa.ac.in         niepa.ac.in          True\n              NIT Karnataka, Surathkal            nitk.ac.in          nitk.ac.in          True\n                          NIT Rourkela          nitrkl.ac.in        nitrkl.ac.in          True\n                   NIT Tiruchirappalli              nitt.edu            nitt.edu          True\n                          NIT Warangal            nitw.ac.in          nitw.ac.in          True\nTata Institute of Fundamental Research           tifr.res.in         tifr.res.in          True\n                   University of Delhi              du.ac.in            du.ac.in          True'

In [58]:
banking_df = dataset1[
    dataset1["organization_type"] == "Banking/Financial"
].copy()

banking_df["source_domain"] = banking_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower().replace("www.", "")
)

banking_df["official_domain_clean"] = (
    banking_df["official_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

banking_df["source_domain_clean"] = (
    banking_df["source_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

banking_df["domain_match"] = (
    banking_df["official_domain_clean"]
    == banking_df["source_domain_clean"]
)

banking_domain_check = (
    banking_df[
        [
            "organization",
            "official_domain_clean",
            "source_domain_clean",
            "domain_match"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["domain_match", "organization"],
        ascending=[True, True]
    )
)

print("Total Banking/Financial records:", len(banking_df))
print("Organizations:", banking_df["organization"].nunique())
print("Exact domain matches:", banking_domain_check["domain_match"].sum())
print("Domain mismatches:", (~banking_domain_check["domain_match"]).sum())

display(banking_domain_check.to_string(index=False))

Total Banking/Financial records: 37
Organizations: 27
Exact domain matches: 12
Domain mismatches: 15

'               organization    official_domain_clean        source_domain_clean  domain_match\n             Bank of Baroda          bankofbaroda.in       bankofbaroda.bank.in         False\n              Bank of India        bankofindia.co.in        bankofindia.bank.in         False\n        Bank of Maharashtra     bankofmaharashtra.in  bankofmaharashtra.bank.in         False\n                Canara Bank           canarabank.com         canarabank.bank.in         False\n      Central Bank of India centralbankofindia.co.in centralbankofindia.bank.in         False\n                  HDFC Bank             hdfcbank.com               hdfc.bank.in         False\n                 ICICI Bank            icicibank.com              icici.bank.in         False\n                Indian Bank            indianbank.in         indianbank.bank.in         False\n       Indian Overseas Bank                   iob.in                iob.bank.in         False\n        Kotak Mahindra Bank                kotak.com              kotak.bank.in         False\n         Punjab & Sind Bank             psbindia.com  punjabandsindbank.bank.in         False\n       Punjab National Bank              pnbindia.in                pnb.bank.in         False\n        State Bank of India                sbi.co.in                sbi.bank.in         False\n                   UCO Bank              ucobank.com            ucobank.bank.in         False\n        Union Bank of India   unionbankofindia.co.in   unionbankofindia.bank.in         False\n                  Axis Bank             axisbank.com               axisbank.com          True\n                        BSE             bseindia.com               bseindia.com          True\n                       CDSL            cdslindia.com              cdslindia.com          True\nExport-Import Bank of India         eximbankindia.in           eximbankindia.in          True\n              IndusInd Bank             indusind.com               indusind.com          True\n                     NABARD               nabard.org                 nabard.org          True\n                       NSDL               nsdl.co.in                 nsdl.co.in          True\n                        NSE             nseindia.com               nseindia.com          True\n      National Housing Bank               nhb.org.in                 nhb.org.in          True\n      Reserve Bank of India               rbi.org.in                 rbi.org.in          True\n                      SIDBI                 sidbi.in                   sidbi.in          True\n                   Yes Bank               yesbank.in                 yesbank.in          True'

In [59]:
banking_df = dataset1[
    dataset1["organization_type"] == "Banking/Financial"
].copy()

banking_df["source_domain"] = banking_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower().replace("www.", "")
)

banking_df["official_domain_clean"] = (
    banking_df["official_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

banking_df["source_domain_clean"] = (
    banking_df["source_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

banking_df["domain_match"] = (
    banking_df["official_domain_clean"]
    == banking_df["source_domain_clean"]
)

banking_domain_check = (
    banking_df[
        [
            "organization",
            "official_domain_clean",
            "source_domain_clean",
            "domain_match"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["domain_match", "organization"],
        ascending=[True, True]
    )
)

print("Total Banking/Financial records:", len(banking_df))
print("Organizations:", banking_df["organization"].nunique())
print("Exact domain matches:", banking_domain_check["domain_match"].sum())
print("Domain mismatches:", (~banking_domain_check["domain_match"]).sum())

display(banking_domain_check.to_string(index=False))

Total Banking/Financial records: 37
Organizations: 27
Exact domain matches: 12
Domain mismatches: 15

'               organization    official_domain_clean        source_domain_clean  domain_match\n             Bank of Baroda          bankofbaroda.in       bankofbaroda.bank.in         False\n              Bank of India        bankofindia.co.in        bankofindia.bank.in         False\n        Bank of Maharashtra     bankofmaharashtra.in  bankofmaharashtra.bank.in         False\n                Canara Bank           canarabank.com         canarabank.bank.in         False\n      Central Bank of India centralbankofindia.co.in centralbankofindia.bank.in         False\n                  HDFC Bank             hdfcbank.com               hdfc.bank.in         False\n                 ICICI Bank            icicibank.com              icici.bank.in         False\n                Indian Bank            indianbank.in         indianbank.bank.in         False\n       Indian Overseas Bank                   iob.in                iob.bank.in         False\n        Kotak Mahindra Bank                kotak.com              kotak.bank.in         False\n         Punjab & Sind Bank             psbindia.com  punjabandsindbank.bank.in         False\n       Punjab National Bank              pnbindia.in                pnb.bank.in         False\n        State Bank of India                sbi.co.in                sbi.bank.in         False\n                   UCO Bank              ucobank.com            ucobank.bank.in         False\n        Union Bank of India   unionbankofindia.co.in   unionbankofindia.bank.in         False\n                  Axis Bank             axisbank.com               axisbank.com          True\n                        BSE             bseindia.com               bseindia.com          True\n                       CDSL            cdslindia.com              cdslindia.com          True\nExport-Import Bank of India         eximbankindia.in           eximbankindia.in          True\n              IndusInd Bank             indusind.com               indusind.com          True\n                     NABARD               nabard.org                 nabard.org          True\n                       NSDL               nsdl.co.in                 nsdl.co.in          True\n                        NSE             nseindia.com               nseindia.com          True\n      National Housing Bank               nhb.org.in                 nhb.org.in          True\n      Reserve Bank of India               rbi.org.in                 rbi.org.in          True\n                      SIDBI                 sidbi.in                   sidbi.in          True\n                   Yes Bank               yesbank.in                 yesbank.in          True'

In [60]:
psu_df = dataset1[
    dataset1["organization_type"] == "PSU/Public Institution"
].copy()

psu_df["source_domain"] = psu_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower().replace("www.", "")
)

psu_df["official_domain_clean"] = (
    psu_df["official_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

psu_df["source_domain_clean"] = (
    psu_df["source_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

psu_df["domain_match"] = (
    psu_df["official_domain_clean"]
    == psu_df["source_domain_clean"]
)

psu_domain_check = (
    psu_df[
        [
            "organization",
            "official_domain_clean",
            "source_domain_clean",
            "domain_match"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["domain_match", "organization"],
        ascending=[True, True]
    )
)

print("Total PSU/Public Institution records:", len(psu_df))
print("Organizations:", psu_df["organization"].nunique())
print("Exact domain matches:", psu_domain_check["domain_match"].sum())
print("Domain mismatches:", (~psu_domain_check["domain_match"]).sum())

display(psu_domain_check.to_string(index=False))

Total PSU/Public Institution records: 18
Organizations: 17
Exact domain matches: 17
Domain mismatches: 0

'                          organization  official_domain_clean    source_domain_clean  domain_match\n                                  BHEL               bhel.com               bhel.com          True\n            Bharat Electronics Limited           bel-india.in           bel-india.in          True\n                      Bharat Petroleum     bharatpetroleum.in     bharatpetroleum.in          True\n                            Coal India           coalindia.in           coalindia.in          True\n                                  GAIL         gailonline.com         gailonline.com          True\n                                  HPCL hindustanpetroleum.com hindustanpetroleum.com          True\n         Hindustan Aeronautics Limited        hal-india.co.in        hal-india.co.in          True\n                Indian Oil Corporation               iocl.com               iocl.com          True\n   Life Insurance Corporation of India            licindia.in            licindia.in          True\n             Mazagon Dock Shipbuilders         mazagondock.in         mazagondock.in          True\n                          NHPC Limited          nhpcindia.com          nhpcindia.com          True\n                                  NTPC             ntpc.co.in             ntpc.co.in          True\nNational Payments Corporation of India            npci.org.in            npci.org.in          True\n                   New India Assurance         newindia.co.in         newindia.co.in          True\n                                  ONGC          ongcindia.com          ongcindia.com          True\n                Power Grid Corporation           powergrid.in           powergrid.in          True\n                                  SAIL             sail.co.in             sail.co.in          True'

In [61]:
regulator_df = dataset1[
    dataset1["organization_type"] == "Regulator"
].copy()

regulator_df["source_domain"] = regulator_df["source_url"].apply(
    lambda x: urlparse(x).netloc.lower().replace("www.", "")
)

regulator_df["official_domain_clean"] = (
    regulator_df["official_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

regulator_df["source_domain_clean"] = (
    regulator_df["source_domain"]
    .str.lower()
    .str.replace("www.", "", regex=False)
)

regulator_df["domain_match"] = (
    regulator_df["official_domain_clean"]
    == regulator_df["source_domain_clean"]
)

regulator_domain_check = (
    regulator_df[
        [
            "organization",
            "official_domain_clean",
            "source_domain_clean",
            "domain_match"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["domain_match", "organization"],
        ascending=[True, True]
    )
)

print("Total Regulator records:", len(regulator_df))
print("Organizations:", regulator_df["organization"].nunique())
print("Exact domain matches:", regulator_domain_check["domain_match"].sum())
print("Domain mismatches:", (~regulator_domain_check["domain_match"]).sum())

display(regulator_domain_check.to_string(index=False))

Total Regulator records: 8
Organizations: 6
Exact domain matches: 6
Domain mismatches: 0

'                                           organization official_domain_clean source_domain_clean  domain_match\n                        Competition Commission of India            cci.gov.in          cci.gov.in          True\n               Insolvency and Bankruptcy Board of India           ibbi.gov.in         ibbi.gov.in          True\nInsurance Regulatory and Development Authority of India          irdai.gov.in        irdai.gov.in          True\n                                  Reserve Bank of India            rbi.org.in          rbi.org.in          True\n                 Securities and Exchange Board of India           sebi.gov.in         sebi.gov.in          True\n                  Telecom Regulatory Authority of India           trai.gov.in         trai.gov.in          True'

In [62]:
email_counts = dataset1["official_email"].str.lower().value_counts()

duplicate_emails = email_counts[email_counts > 1]

print("Total email addresses:", len(email_counts))
print("Unique email addresses:", email_counts.nunique())
print("Duplicate email addresses:", len(duplicate_emails))

if len(duplicate_emails) > 0:
    display(
        duplicate_emails
        .rename("count")
        .reset_index()
        .rename(columns={"index": "official_email"})
        .to_string(index=False)
    )
else:
    print("PASS: No duplicate email addresses found.")

Total email addresses: 388
Unique email addresses: 10
Duplicate email addresses: 30

'                     official_email  count\n                 workssec.od@nic.in     33\n            hthdepartment@gmail.com      9\n                         cmo@nic.in      9\n                   dsmsec.od@nic.in      8\n                    ctsec.od@nic.in      7\n                   labsec.od@nic.in      6\n                    orhealth@nic.in      5\n             secretarysme.od@nic.in      5\n               sportsysec.od@nic.in      4\n                wcdsec.or@od.gov.in      4\n             secy-msme.od@od.gov.in      4\n             excisesec.or@od.gov.in      4\n                   dstsec.od@nic.in      4\n                     hosd@pnb.co.in      4\n                   finsec.or@nic.in      4\n                   lawsec.or@nic.in      3\n               tourismsec.od@nic.in      3\n              ssepdodisha@gmail.com      2\n        itpmu@orissaminerals.gov.in      2\n       investor.relations@wipro.com      2\n         investor.relations@tcs.com      2\ninstitutionalinvestors@mahindra.com      2\n                director@iitd.ac.in      2\n                  stscdev@gmail.com      2\n                   dpesec.od@nic.in      2\n                   gadmin.or@nic.in      2\n                    prsec.od@nic.in      2\n                   hudsec.or@nic.in      2\n                   energy@od.gov.in      2\n                  coopsec.or@nic.in      2'

In [63]:
email_org_check = (
    dataset1.groupby(dataset1["official_email"].str.lower())
    .agg(
        record_count=("identity_id", "count"),
        organization_count=("organization", "nunique"),
        organizations=("organization", lambda x: " | ".join(sorted(x.unique())))
    )
    .reset_index()
)

cross_org_emails = email_org_check[
    email_org_check["organization_count"] > 1
].sort_values(
    ["organization_count", "record_count"],
    ascending=[False, False]
)

print("Emails used across multiple organizations:", len(cross_org_emails))

display(
    cross_org_emails.to_string(index=False)
)

Emails used across multiple organizations: 2

"  official_email  record_count  organization_count                                          organizations\n      cmo@nic.in             9                   2 Chief Minister's Office, Odisha | Government of Odisha\nfinsec.or@nic.in             4                   2        Finance Department | Finance Department, Odisha"

In [64]:
shared_emails = [
    "cmo@nic.in",
    "finsec.or@nic.in"
]

display(
    dataset1[
        dataset1["official_email"]
        .str.lower()
        .isin(shared_emails)
    ][
        [
            "identity_id",
            "name",
            "role",
            "organization",
            "official_email",
            "official_domain",
            "source_url",
            "source_type"
        ]
    ]
    .sort_values(["official_email", "organization"])
    .to_string(index=False)
)

"identity_id                      name                                         role                    organization   official_email official_domain                                                     source_url                   source_type\n    ID-0011            Saswata Mishra Additional Chief Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0012         Manoj Kumar Sahoo          Private Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0013               Anupam Saha       Additional Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0014    Prasanna Kumar Sarangi  OSD-cum-Special Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0015              Mirdha Toppo          Special Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0016            Chitrasen Rout       Additional Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0017    Umesh Chandra Tripathy       Additional Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0018         Trilochan Mohanty            Joint Secretary to Chief Minister Chief Minister's Office, Odisha       cmo@nic.in   odisha.gov.in https://odisha.gov.in/index.php/en/about-us/whos-who/cm-office Official government directory\n    ID-0001        Mohan Charan Majhi                               Chief Minister            Government of Odisha       cmo@nic.in   odisha.gov.in  https://inpr.odisha.gov.in/en/about-us/whos-who/web-directory Official government directory\n    ID-0140 Sri Bijaya Kumar Mangaraj                            Special Secretary              Finance Department finsec.or@nic.in   odisha.gov.in          https://odisha.gov.in/en/about-us/whos-who/department Official government directory\n    ID-0006      Sanjeeb Kumar Mishra                          Principal Secretary      Finance Department, Odisha finsec.or@nic.in   odisha.gov.in            https://finance.odisha.gov.in/en/about-us/whose-who Official government directory\n    ID-0008           Satyapriya Rath   Director (Budget)-cum-Additional Secretary      Finance Department, Odisha finsec.or@nic.in   odisha.gov.in            https://finance.odisha.gov.in/en/about-us/whose-who Official government directory\n    ID-0009  Krushna Chandra Satpathy                         Additional Secretary      Finance Department, Odisha finsec.or@nic.in   odisha.gov.in            https://finance.odisha.gov.in/en/about-us/whose-who Official government directory"

In [65]:
public_email_domains = [
    "gmail.com",
    "yahoo.com",
    "yahoo.co.in",
    "outlook.com",
    "hotmail.com",
    "rediffmail.com"
]

public_email_records = dataset1[
    dataset1["official_email"]
    .str.lower()
    .str.split("@")
    .str[-1]
    .isin(public_email_domains)
].copy()

print("Public-provider email records:", len(public_email_records))
print(
    "Unique public-provider emails:",
    public_email_records["official_email"].str.lower().nunique()
)

display(
    public_email_records[
        [
            "identity_id",
            "name",
            "role",
            "organization",
            "organization_type",
            "official_email",
            "official_domain",
            "source_url"
        ]
    ].to_string(index=False)
)

Public-provider email records: 28
Unique public-provider emails: 18

"identity_id                            name                               role                                                          organization organization_type                          official_email official_domain                                                    source_url\n    ID-0004               Pruthwee Raj Pani            AFA-cum-Under Secretary                     Information & Public Relations Department, Odisha        Government               pruthweeraj1970@gmail.com   odisha.gov.in https://inpr.odisha.gov.in/en/about-us/whos-who/web-directory\n    ID-0010                  Saumyajit Rout                    Joint Secretary                                            Finance Department, Odisha        Government                saumyajit.rout@gmail.com   odisha.gov.in           https://finance.odisha.gov.in/en/about-us/whose-who\n    ID-0105        Dr. Nivedita Prusty, IAS Additional Secretary to Government                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0106       Smt Chinmayee Biswal, OAS Additional Secretary to Government                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0109    Sri Pratap Chandra Hota, IAS Additional Secretary to Government                          Handlooms, Textiles & Handicrafts Department        Government                   mail.pchota@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0115    Smt. Sonia Behera, OAS (SAG)               Additional Secretary Social Security & Empowerment of Persons with Disabilities Department        Government                   ssepdodisha@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0118           Smt Mamata Samantaroy                    Under Secretary                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0120           Mr. Binaya Kumar Dash                  Special Secretary                             Department of Housing & Urban Development        Government                  dashbinaya45@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0128    Smt. Soojata Misra, OAS (SS)                  Special Secretary ST & SC Development, Minorities & Backward Classes Welfare Department        Government                       stscdev@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0129          Sri Manas Ranjan Patra           Assistant Director (Law)                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0137      Smt. Banita Dash, OFS(SAG)           FA-cum-Special Secretary ST & SC Development, Minorities & Backward Classes Welfare Department        Government                       stscdev@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0139           Smt. Rashmi Kabi, OFS       F.A-cum-Additional Secretary                                     Planning & Convergence Department        Government                  giapncodisha@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0143     Shri Bhaskar Raito OAS(SAG)               Additional Secretary Social Security & Empowerment of Persons with Disabilities Department        Government                   ssepdodisha@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0144    Sri Daridryabhanjan MM Patra               Additional Secretary                      Department of Agriculture & Farmers' Empowerment        Government                     dbmmpatra@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0150            Sri Abhijeet Routray          Assistant Section Officer                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0151              Sri Anshuman Nayak          Assistant Section Officer                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0167          Sri Shubhranshu Mishra               Additional Secretary                      Department of Agriculture & Farmers' Empowerment        Government          addl.secretarypolicy@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0170  Sri Deba Prasad Dash, OAS (SS)    Special Secretary to Government                         Odia Language Literature & Culture Department        Government specialsecretarycultureodisha@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0175 Shri Sukanta Kumar Pradhan, OAS               Additional Secretary                    Skill Development & Technical Education Department        Government                     sdte.addl@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0182     Smt. Madhusmita Behera, OFS       F.A-cum-Additional Secretary                          Handlooms, Textiles & Handicrafts Department        Government          madhusmitabehera0711@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0183          Sri Arindam Dakua, IAS   DMA & Ex-officio Addl. Secretary                             Department of Housing & Urban Development        Government                       dmahudd@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0193               Sri Ganeswar Jena               Additional Secretary                      Department of Agriculture & Farmers' Empowerment        Government                 ganeswarjena2@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0199    Sri Subrat Kumar Behera, OAS                   Deputy Secretary                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0203         Sri Nilamani Nayak, OSS            Under Secretary to Govt                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0204           Sri Saroj Kumar Sahoo            Deputy Director Geology                                           Department of Steel & Mines        Government                    sksahoo667@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0212               Er. Gayatri Patel                           SE (DPQ)                                                      Works Department        Government                  gayatriuce@yahoo.co.in   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0251              Er. Satyaban Patel                    SE - Jharsuguda                                                      Works Department        Government                       eenhjsg@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department\n    ID-0258           Smt Mamata Nayak, OAS                    Joint Secretary                          Handlooms, Textiles & Handicrafts Department        Government                 hthdepartment@gmail.com   odisha.gov.in         https://odisha.gov.in/en/about-us/whos-who/department"

In [66]:
public_email_org_check = (
    public_email_records
    .groupby(public_email_records["official_email"].str.lower())
    .agg(
        record_count=("identity_id", "count"),
        organization_count=("organization", "nunique"),
        organizations=("organization", lambda x: " | ".join(sorted(x.unique())))
    )
    .reset_index()
)

cross_org_public_emails = public_email_org_check[
    public_email_org_check["organization_count"] > 1
].sort_values(
    ["organization_count", "record_count"],
    ascending=[False, False]
)

print(
    "Public emails used across multiple organizations:",
    len(cross_org_public_emails)
)

display(
    cross_org_public_emails.to_string(index=False)
)

Public emails used across multiple organizations: 0

'Empty DataFrame\nColumns: [official_email, record_count, organization_count, organizations]\nIndex: []'

In [67]:
import re

def normalize_name(name):
    name = re.sub(r"\b(Dr|Mr|Mrs|Ms|Smt|Shri|Sri|Er)\.?\b", "", str(name), flags=re.I)
    name = re.sub(r"\b(IAS|OAS|OFS|OSS|SAG|SS)\b", "", name, flags=re.I)
    return re.sub(r"[^a-z0-9]", "", name.lower())

def email_local(email):
    return str(email).lower().split("@")[0]

dataset1["name_clean"] = dataset1["name"].apply(normalize_name)
dataset1["email_local"] = dataset1["official_email"].apply(email_local)

# Check whether at least part of the person's name appears in the email
def name_email_match(row):
    name = row["name_clean"]
    email = row["email_local"].replace(".", "").replace("_", "").replace("-", "")
    
    if len(name) < 4:
        return True
    
    # first name / last name tokens
    original_name = re.sub(
        r"\b(Dr|Mr|Mrs|Ms|Smt|Shri|Sri|Er|IAS|OAS|OFS|OSS|SAG|SS)\.?\b",
        "",
        str(row["name"]),
        flags=re.I
    )
    
    tokens = [
        re.sub(r"[^a-z]", "", x.lower())
        for x in original_name.split()
    ]
    tokens = [x for x in tokens if len(x) >= 4]

    return any(token in email for token in tokens)

dataset1["name_email_match"] = dataset1.apply(
    name_email_match,
    axis=1
)

print("Name-email match:", dataset1["name_email_match"].sum())
print("Name-email flagged:", (~dataset1["name_email_match"]).sum())

display(
    dataset1[~dataset1["name_email_match"]][
        [
            "identity_id",
            "name",
            "organization",
            "official_email",
            "official_domain"
        ]
    ].to_string(index=False)
)

Name-email match: 272
Name-email flagged: 228

"identity_id                                    name                                                          organization                          official_email          official_domain\n    ID-0001                      Mohan Charan Majhi                                                  Government of Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0002                           Hemant Sharma                                                  Government of Odisha                        iprsec.or@nic.in            odisha.gov.in\n    ID-0003                Anuj Kumar Das Pattanaik                     Information & Public Relations Department, Odisha                  director-ipr.od@gov.in            odisha.gov.in\n    ID-0005                   Parthasarathi Mallick                     Information & Public Relations Department, Odisha                          rti-ori@nic.in            odisha.gov.in\n    ID-0006                    Sanjeeb Kumar Mishra                                            Finance Department, Odisha                        finsec.or@nic.in            odisha.gov.in\n    ID-0008                         Satyapriya Rath                                            Finance Department, Odisha                        finsec.or@nic.in            odisha.gov.in\n    ID-0009                Krushna Chandra Satpathy                                            Finance Department, Odisha                        finsec.or@nic.in            odisha.gov.in\n    ID-0011                          Saswata Mishra                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0012                       Manoj Kumar Sahoo                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0013                             Anupam Saha                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0014                  Prasanna Kumar Sarangi                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0015                            Mirdha Toppo                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0016                          Chitrasen Rout                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0017                  Umesh Chandra Tripathy                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0018                       Trilochan Mohanty                                       Chief Minister's Office, Odisha                              cmo@nic.in            odisha.gov.in\n    ID-0019                      Pradip Kumar Samal                                       Chief Minister's Office, Odisha                           cmo@od.gov.in            odisha.gov.in\n    ID-0020                           Hemant Sharma                                               Home Department, Odisha                    homesec.od@od.gov.in            odisha.gov.in\n    ID-0051                            Uma Kanjilal                                                                 IGNOU                          vc@ignou.ac.in              ignou.ac.in\n    ID-0052                            Yogesh Singh                                                   University of Delhi                             vc@du.ac.in                 du.ac.in\n    ID-0053                            Balaram Pani                                                   University of Delhi                  dean_colleges@du.ac.in                 du.ac.in\n    ID-0054                      Shireesh B. Kedare                                                            IIT Bombay                     director@iitb.ac.in               iitb.ac.in\n    ID-0055                        Ravindra D. Gudi                                                            IIT Bombay                       dd.fia@iitb.ac.in               iitb.ac.in\n    ID-0056                               Murty B S                                                         IIT Hyderabad                     director@iith.ac.in               iith.ac.in\n    ID-0057                           V Venkata Rao                                                         IIT Hyderabad                    registrar@iith.ac.in               iith.ac.in\n    ID-0058                             V. Kamakoti                                                            IIT Madras                     director@iitm.ac.in               iitm.ac.in\n    ID-0059                      Kamal Kishore Pant                                                           IIT Roorkee                     director@iitr.ac.in               iitr.ac.in\n    ID-0060             Shashikala Gulabrao Wanjari                                                                 NIEPA                          vc@niepa.ac.in              niepa.ac.in\n    ID-0061                           Ashok Chandra                                                  Punjab National Bank                          mdps@pnb.co.in              pnbindia.in\n    ID-0062                            Kalyan Kumar                                                  Punjab National Bank                          hosd@pnb.co.in              pnbindia.in\n    ID-0063                          M. Paramasivam                                                  Punjab National Bank                          hosd@pnb.co.in              pnbindia.in\n    ID-0064                  Bibhu Prasad Mahapatra                                                  Punjab National Bank                          hosd@pnb.co.in              pnbindia.in\n    ID-0065                            D. Surendran                                                  Punjab National Bank                          hosd@pnb.co.in              pnbindia.in\n    ID-0066                             Rajiv Anand                                                         IndusInd Bank           managingdirector@indusind.com             indusind.com\n    ID-0067                    Kesavan Ramachandran                                                 Reserve Bank of India                      helpdoc@rbi.org.in               rbi.org.in\n    ID-0068                  Indranil Bhattacharyya                                                 Reserve Bank of India                ibhattacharya@rbi.org.in               rbi.org.in\n    ID-0069                     Ajit Ratnakar Joshi                                                 Reserve Bank of India                      pradsim@rbi.org.in               rbi.org.in\n    ID-0070                             Aviral Jain                                                 Reserve Bank of India                        aaria@rbi.org.in               rbi.org.in\n    ID-0071                            Salil Parekh                                                               Infosys                   investors@infosys.com              infosys.com\n    ID-0073                            Srini Pallia                                                                 Wipro            investor.relations@wipro.com                wipro.com\n    ID-0074                           Rishad Premji                                                                 Wipro            investor.relations@wipro.com                wipro.com\n    ID-0075                          K. Krithivasan                                             Tata Consultancy Services              Investor.Relations@tcs.com                  tcs.com\n    ID-0076                      Aarthi Subramanian                                             Tata Consultancy Services              Investor.Relations@tcs.com                  tcs.com\n    ID-0077                          Anand Mahindra                                                        Mahindra Group     institutionalinvestors@mahindra.com             mahindra.com\n    ID-0078                              Anish Shah                                                        Mahindra Group     institutionalinvestors@mahindra.com             mahindra.com\n    ID-0079                           Sunil D'Souza                                                Tata Consumer Products     investor.relations@tataconsumer.com         tataconsumer.com\n    ID-0081                    Ashish Kumar Bhutani                                               Ministry of Cooperation                        secy-coop@gov.in       cooperation.gov.in\n    ID-0082                     Pankaj Kumar Bansal                                               Ministry of Cooperation                       as.cd-coop@gov.in       cooperation.gov.in\n    ID-0083                             Raman Kumar                                               Ministry of Cooperation                       js.cd-coop@gov.in       cooperation.gov.in\n    ID-0084                               S Sathiya                                               Ministry of Cooperation                     director-cd1@gov.in       cooperation.gov.in\n    ID-0085                              Amit Kumar                                               Ministry of Cooperation                          dir-ctp@gov.in       cooperation.gov.in\n    ID-0086                             Vipin Singh                                               Ministry of Cooperation                    dd.media-coop@gov.in       cooperation.gov.in\n    ID-0087                             Afsar Ahmed                                               Ministry of Cooperation                       dirol-coop@gov.in       cooperation.gov.in\n    ID-0088                    Devendra Kumar Singh                                               Ministry of Cooperation              chairperson-coop.ea@gov.in       cooperation.gov.in\n    ID-0089                            Ravneet Kaur                                       Competition Commission of India                     cci-chairman@nic.in               cci.gov.in\n    ID-0090                  Inder Pal Singh Bindra                                       Competition Commission of India                         secy@cci.gov.in               cci.gov.in\n    ID-0101                     Sri Raghunandan Das                                         Department of Water Resources                         wrsec.od@nic.in            odisha.gov.in\n    ID-0102              Dr. Mrinalini Darswal, IAS                             Department of Women and Child Development                     wcdsec.or@od.gov.in                od.gov.in\n    ID-0103                 Ms. Rashmita Panda, IAS                           Micro, Small & Medium Enterprise Department                  secy-msme.od@od.gov.in                od.gov.in\n    ID-0104              Dr. N. Thirumala Naik, IAS                               Department of School and Mass Education                  Secretarysme.od@nic.in            odisha.gov.in\n    ID-0105                Dr. Nivedita Prusty, IAS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com            odisha.gov.in\n    ID-0106               Smt Chinmayee Biswal, OAS                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com            odisha.gov.in\n    ID-0107           Dr. Pabitra Mohan Samal, OSJS                                                        Law Department                        lawsec.or@nic.in            odisha.gov.in\n    ID-0108    Shri Rajesh Kumar Agarwala, OAS(SAG)                      Labour and Employee's State Insurance Department                        labsec.od@nic.in            odisha.gov.in\n    ID-0110                      Smt. Urmila Kanhar                                       Commerce & Transport Department                         ctsec.od@nic.in            odisha.gov.in\n    ID-0111                    Shri Biswombar Sethi                                       Commerce & Transport Department                         ctsec.od@nic.in            odisha.gov.in\n    ID-0112  Shri Saroj Kanta Mohanty, O.A.S. (SAG)                                                 Industries Department                        indsec.or@nic.in            odisha.gov.in\n    ID-0113                     Smt. Sarita Dhanwar                      Department of Agriculture & Farmers' Empowerment                        agrsec.or@nic.in            odisha.gov.in\n    ID-0115            Smt. Sonia Behera, OAS (SAG) Social Security & Empowerment of Persons with Disabilities Department                   ssepdodisha@gmail.com            odisha.gov.in\n    ID-0116                     Sri Gangadhar Nayak                             Department of Housing & Urban Development                        hudsec.or@nic.in            odisha.gov.in\n    ID-0117              Smt. Nirmala Kumari Biswal                                       Commerce & Transport Department                         ctsec.od@nic.in            odisha.gov.in\n    ID-0118                   Smt Mamata Samantaroy                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com            odisha.gov.in\n    ID-0119                 Smt. Urmiprava Maharana                                       Science & Technology Department                        dstsec.od@nic.in            odisha.gov.in\n    ID-0121                       Bishnupriya Sahoo                                            Department of Co-operation                       coopsec.or@nic.in            odisha.gov.in\n    ID-0122                       Smt. Smita Biswal                                 Department of Health & Family Welfare                         orhealth@nic.in            odisha.gov.in\n    ID-0123                    Sri Gaurahari Behera                                 Department of Health & Family Welfare                         orhealth@nic.in            odisha.gov.in\n    ID-0124            Shri Lalit Kumar Kanhar, OAS                    Skill Development & Technical Education Department                          etet.od@nic.in            odisha.gov.in\n    ID-0125                   Shri Manoranjan Panda                                           Department of Steel & Mines                        dsmsec.od@nic.in            odisha.gov.in\n    ID-0126                    Shri Shaktikanta Ray                                           Department of Steel & Mines             itpmu@orissaminerals.gov.in            odisha.gov.in\n    ID-0127                        Sri Dillip Sahoo                                           Department of Steel & Mines        mo.cuttack@orissaminerals.gov.in            odisha.gov.in\n    ID-0128            Smt. Soojata Misra, OAS (SS) ST & SC Development, Minorities & Backward Classes Welfare Department                       stscdev@gmail.com            odisha.gov.in\n    ID-0129                  Sri Manas Ranjan Patra                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com            odisha.gov.in\n    ID-0130                  Puspanjali Bisoi (OSS)                                      Department of Public Enterprises                        dpesec.od@nic.in            odisha.gov.in\n    ID-0131   Shri Durgaprasad Mohapatra, OAS (SAG)                               Department of School and Mass Education                  Secretarysme.od@nic.in            odisha.gov.in\n    ID-0132                     Shri Narottam Sahoo                                           Department of Steel & Mines                        dsmsec.od@nic.in            odisha.gov.in\n    ID-0133                    Rajat Kumar Kar, ADG                                           Department of Steel & Mines                        dsmsec.od@nic.in            odisha.gov.in\n    ID-0134                   Chinmayee Chetna Dash                                       Science & Technology Department                        dstsec.od@nic.in            odisha.gov.in\n    ID-0135          Sri Probodh Kumar Dwibedy, OSS                                                  Department of Excise                  excisesec.or@od.gov.in            odisha.gov.in\n    ID-0136                 Sri Parakhita Bhoi, OSS                                                  Department of Excise                  excisesec.or@od.gov.in            odisha.gov.in\n    ID-0137              Smt. Banita Dash, OFS(SAG) ST & SC Development, Minorities & Backward Classes Welfare Department                       stscdev@gmail.com            odisha.gov.in\n    ID-0139                   Smt. Rashmi Kabi, OFS                                     Planning & Convergence Department                  giapncodisha@gmail.com            odisha.gov.in\n    ID-0140               Sri Bijaya Kumar Mangaraj                                                    Finance Department                        finsec.or@nic.in            odisha.gov.in\n    ID-0141               Dr. Jagadish Sarangi, OAS                                                 Department of Tourism                    tourismsec.od@nic.in            odisha.gov.in\n    ID-0142               Shri Dharmendra Satapathy                                       Commerce & Transport Department                         ctsec.od@nic.in            odisha.gov.in\n    ID-0143             Shri Bhaskar Raito OAS(SAG) Social Security & Empowerment of Persons with Disabilities Department                   ssepdodisha@gmail.com            odisha.gov.in\n    ID-0145                Sri Amit Kumar Nayak,OAS                                    Sports & Youth Services Department                    sportsysec.od@nic.in            odisha.gov.in\n    ID-0146                Sri Krutibash Routh, OAS                             Department of Women and Child Development                     wcdsec.or@od.gov.in            odisha.gov.in\n    ID-0147                     Smt. Soumitri Nayak                      Labour and Employee's State Insurance Department                        labsec.od@nic.in            odisha.gov.in\n    ID-0148                      Sri Umakanta Barik                                       Commerce & Transport Department                         ctsec.od@nic.in            odisha.gov.in\n    ID-0149            Shri Rama Chandra Kisku, OAS                                           Department of Steel & Mines                 dsm.edespatch@od.gov.in            odisha.gov.in\n    ID-0150                    Sri Abhijeet Routray                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com            odisha.gov.in\n    ID-0151                      Sri Anshuman Nayak                          Handlooms, Textiles & Handicrafts Department                 hthdepartment@gmail.com            odisha.gov.in\n    ID-0152 Smt. Sumitra Kumari Pattnaik, OAS (SAG)                             Department of Women and Child Development                     wcdsec.or@od.gov.in            odisha.gov.in\n    ID-0154         Sri Bibekananda Sahoo, OAS(SAG)                             Department of Women and Child Development                     wcdsec.or@od.gov.in            odisha.gov.in\n    ID-0155                 Shri Santosh Kumar Suar                                                    Finance Department                        finsec.od@nic.in            odisha.gov.in\n    ID-0156             Shri Daulat Chandrakar, OAS                                           Department of Steel & Mines                        dsmsec.od@nic.in            odisha.gov.in\n    ID-0157             Sri Sibashis Dhal, OFS (SS)                    

In [68]:
role_keywords = [
    "director",
    "vc",
    "registrar",
    "secretary",
    "secy",
    "sec",
    "chairman",
    "chairperson",
    "cmo",
    "finance",
    "finsec",
    "investor",
    "institutional",
    "info",
    "admin",
    "office",
    "help",
    "support",
    "rti",
    "media",
    "department",
    "labsec",
    "workssec",
    "sportsysec",
    "wcdsec",
    "dsmsec",
    "ctsec",
    "lawsec",
    "orhealth"
]

def is_role_based_email(email):
    local = str(email).lower().split("@")[0]
    return any(keyword in local for keyword in role_keywords)

dataset1["role_based_email"] = dataset1["official_email"].apply(
    is_role_based_email
)

print(
    "Role/shared email records:",
    dataset1["role_based_email"].sum()
)

print(
    "Non-role/personal-looking email records:",
    (~dataset1["role_based_email"]).sum()
)

display(
    dataset1[
        ~dataset1["role_based_email"]
    ][
        [
            "identity_id",
            "name",
            "organization",
            "official_email",
            "official_domain"
        ]
    ].to_string(index=False)
)

Role/shared email records: 190
Non-role/personal-looking email records: 310

"identity_id                                  name                                                          organization                           official_email          official_domain\n    ID-0004                     Pruthwee Raj Pani                     Information & Public Relations Department, Odisha                pruthweeraj1970@gmail.com            odisha.gov.in\n    ID-0007                        Yamini Sarangi                                            Finance Department, Odisha                    yamini.sarangi@nic.in            odisha.gov.in\n    ID-0010                        Saumyajit Rout                                            Finance Department, Odisha                 saumyajit.rout@gmail.com            odisha.gov.in\n    ID-0021                      Pranati Chhotray                                               Home Department, Odisha           pranati.chhotray@odisha.gov.in            odisha.gov.in\n    ID-0022                      Samarendra Nayak                                               Home Department, Odisha           samarendra.nayak@odisha.gov.in            odisha.gov.in\n    ID-0023                      G. Jagdish Kumar                                               Home Department, Odisha            gjagadish.kumar@odisha.gov.in            odisha.gov.in\n    ID-0024                    Amiya Kumar Udgata                                               Home Department, Odisha          amiyakumar.udgata@odisha.gov.in            odisha.gov.in\n    ID-0025                     Siba Prasad Panda                                               Home Department, Odisha                 siba.panda@odisha.gov.in            odisha.gov.in\n    ID-0026                     Tarun Kumar Panda                                               Home Department, Odisha           tarunkumar.panda@odisha.gov.in            odisha.gov.in\n    ID-0027                   Pradip Kumar Behera                                               Home Department, Odisha         pradipkumar.behera@odisha.gov.in            odisha.gov.in\n    ID-0028                       Ratikanta Panda                                               Home Department, Odisha            ratikanta.panda@odisha.gov.in            odisha.gov.in\n    ID-0029                      Suryanarayan Kar                                               Home Department, Odisha           suryanarayan.kar@odisha.gov.in            odisha.gov.in\n    ID-0030                       Rajkishore Rout                                               Home Department, Odisha            rajkishore.rout@odisha.gov.in            odisha.gov.in\n    ID-0031                       Aatish Anshuman                                                       IIT Bhubaneswar                   aanshuman@iitbbs.ac.in             iitbbs.ac.in\n    ID-0032                          Abhinav Arya                                                       IIT Bhubaneswar                       aarya@iitbbs.ac.in             iitbbs.ac.in\n    ID-0033                      Abhineet Prakash                                                       IIT Bhubaneswar                    abhineet@iitbbs.ac.in             iitbbs.ac.in\n    ID-0034                    Akshaya Kumar Rath                                                       IIT Bhubaneswar                      akrath@iitbbs.ac.in             iitbbs.ac.in\n    ID-0035                         Aparna Pandey                                                       IIT Bhubaneswar                aparnapandey@iitbbs.ac.in             iitbbs.ac.in\n    ID-0036                   Abhijit Datta Banik                                                       IIT Bhubaneswar                 adattabanik@iitbbs.ac.in             iitbbs.ac.in\n    ID-0037                            Abhik Jana                                                       IIT Bhubaneswar                   abhikjana@iitbbs.ac.in             iitbbs.ac.in\n    ID-0038                    Abhishek Chowdhury                                                       IIT Bhubaneswar                  achowdhury@iitbbs.ac.in             iitbbs.ac.in\n    ID-0039                         Akash Jaiswal                                                       IIT Bhubaneswar                    ajaiswal@iitbbs.ac.in             iitbbs.ac.in\n    ID-0040                  Akhilesh Kumar Singh                                                       IIT Bhubaneswar                     aksingh@iitbbs.ac.in             iitbbs.ac.in\n    ID-0041                              Akshay K                                                       IIT Bhubaneswar                      akshay@iitbbs.ac.in             iitbbs.ac.in\n    ID-0042                      Amar Deep Sarkar                                                       IIT Bhubaneswar                        amar@iitbbs.ac.in             iitbbs.ac.in\n    ID-0043                         Amrit B. Sahu                                                       IIT Bhubaneswar                  amritbsahu@iitbbs.ac.in             iitbbs.ac.in\n    ID-0044                      Amrita Satapathy                                                       IIT Bhubaneswar                  asatapathy@iitbbs.ac.in             iitbbs.ac.in\n    ID-0045                         Anamitra Basu                                                       IIT Bhubaneswar                anamitrabasu@iitbbs.ac.in             iitbbs.ac.in\n    ID-0046                  Anasuya Roychowdhury                                                       IIT Bhubaneswar               aroychowdhury@iitbbs.ac.in             iitbbs.ac.in\n    ID-0047                        Animesh Mandal                                                       IIT Bhubaneswar                     animesh@iitbbs.ac.in             iitbbs.ac.in\n    ID-0048                  Anirban Bhattacharya                                                       IIT Bhubaneswar                     anirban@iitbbs.ac.in             iitbbs.ac.in\n    ID-0049                           Ankit Dalal                                                       IIT Bhubaneswar                  ankitdalal@iitbbs.ac.in             iitbbs.ac.in\n    ID-0050               Ankit Ravindra Deshmukh                                                       IIT Bhubaneswar                      ankitd@iitbbs.ac.in             iitbbs.ac.in\n    ID-0053                          Balaram Pani                                                   University of Delhi                   dean_colleges@du.ac.in                 du.ac.in\n    ID-0055                      Ravindra D. Gudi                                                            IIT Bombay                        dd.fia@iitb.ac.in               iitb.ac.in\n    ID-0061                         Ashok Chandra                                                  Punjab National Bank                           mdps@pnb.co.in              pnbindia.in\n    ID-0062                          Kalyan Kumar                                                  Punjab National Bank                           hosd@pnb.co.in              pnbindia.in\n    ID-0063                        M. Paramasivam                                                  Punjab National Bank                           hosd@pnb.co.in              pnbindia.in\n    ID-0064                Bibhu Prasad Mahapatra                                                  Punjab National Bank                           hosd@pnb.co.in              pnbindia.in\n    ID-0065                          D. Surendran                                                  Punjab National Bank                           hosd@pnb.co.in              pnbindia.in\n    ID-0068                Indranil Bhattacharyya                                                 Reserve Bank of India                 ibhattacharya@rbi.org.in               rbi.org.in\n    ID-0069                   Ajit Ratnakar Joshi                                                 Reserve Bank of India                       pradsim@rbi.org.in               rbi.org.in\n    ID-0070                           Aviral Jain                                                 Reserve Bank of India                         aaria@rbi.org.in               rbi.org.in\n    ID-0072                     Jayesh Sanghrajka                                                               Infosys            jayesh.sanghrajka@infosys.com              infosys.com\n    ID-0080                           Amit Syngle                                                          Asian Paints              amit.syngle@asianpaints.com          asianpaints.com\n    ID-0082                   Pankaj Kumar Bansal                                               Ministry of Cooperation                        as.cd-coop@gov.in       cooperation.gov.in\n    ID-0083                           Raman Kumar                                               Ministry of Cooperation                        js.cd-coop@gov.in       cooperation.gov.in\n    ID-0085                            Amit Kumar                                               Ministry of Cooperation                           dir-ctp@gov.in       cooperation.gov.in\n    ID-0087                           Afsar Ahmed                                               Ministry of Cooperation                        dirol-coop@gov.in       cooperation.gov.in\n    ID-0091                             Anuj Dash                                                       IIT Bhubaneswar                    anujdash@iitbbs.ac.in             iitbbs.ac.in\n    ID-0092                        Arindam Sarkar                                                       IIT Bhubaneswar                     asarkar@iitbbs.ac.in             iitbbs.ac.in\n    ID-0093                               Arjun S                                                       IIT Bhubaneswar                      arjuns@iitbbs.ac.in             iitbbs.ac.in\n    ID-0094                             Arpan Das                                                       IIT Bhubaneswar                    arpandas@iitbbs.ac.in             iitbbs.ac.in\n    ID-0095                    Arun Kumar Pradhan                                                       IIT Bhubaneswar                   akpradhan@iitbbs.ac.in             iitbbs.ac.in\n    ID-0096                          Ashis Biswas                                                       IIT Bhubaneswar                     abiswas@iitbbs.ac.in             iitbbs.ac.in\n    ID-0097                       Debadatta Swain                                                       IIT Bhubaneswar                      dswain@iitbbs.ac.in             iitbbs.ac.in\n    ID-0098                        Debalina Ghosh                                                       IIT Bhubaneswar                     deghosh@iitbbs.ac.in             iitbbs.ac.in\n    ID-0099                       Gaurav Bartarya                                                       IIT Bhubaneswar                    bartarya@iitbbs.ac.in             iitbbs.ac.in\n    ID-0100                    Niharika Mohapatra                                                       IIT Bhubaneswar                    niharika@iitbbs.ac.in             iitbbs.ac.in\n    ID-0109          Sri Pratap Chandra Hota, IAS                          Handlooms, Textiles & Handicrafts Department                    mail.pchota@gmail.com            odisha.gov.in\n    ID-0114                  Shri Sabyasachi Hota                       Electronics & Information Technology Department                   sabyasachi.hota@gov.in                   gov.in\n    ID-0115          Smt. Sonia Behera, OAS (SAG) Social Security & Empowerment of Persons with Disabilities Department                    ssepdodisha@gmail.com            odisha.gov.in\n    ID-0120                 Mr. Binaya Kumar Dash                             Department of Housing & Urban Development                   dashbinaya45@gmail.com            odisha.gov.in\n    ID-0124          Shri Lalit Kumar Kanhar, OAS                    Skill Development & Technical Education Department                           etet.od@nic.in            odisha.gov.in\n    ID-0126                  Shri Shaktikanta Ray                                           Department of Steel & Mines              itpmu@orissaminerals.gov.in            odisha.gov.in\n    ID-0127                      Sri Dillip Sahoo                                           Department of Steel & Mines         mo.cuttack@orissaminerals.gov.in            odisha.gov.in\n    ID-0128          Smt. Soojata Misra, OAS (SS) ST & SC Development, Minorities & Backward Classes Welfare Department                        stscdev@gmail.com            odisha.gov.in\n    ID-0137            Smt. Banita Dash, OFS(SAG) ST & SC Development, Minorities & Backward Classes Welfare Department                        stscdev@gmail.com            odisha.gov.in\n    ID-0138 Shri Shailendra Narayan Nayak, O.I.S.                                                 Industries Department           shailendra.nayak@odisha.gov.in            odisha.gov.in\n    ID-0139                 Smt. Rashmi Kabi, OFS                                     Planning & Convergence Department                   giapncodisha@gmail.com            odisha.gov.in\n    ID-0143           Shri Bhaskar Raito OAS(SAG) Social Security & Empowerment of Persons with Disabilities Department                    ssepdodisha@gmail.com            odisha.gov.in\n    ID-0144          Sri Daridryabhanjan MM Patra                      Department of Agriculture & Farmers' Empowerment                      dbmmpatra@gmail.com            odisha.gov.in\n    ID-0149          Shri Rama Chandra Kisku, OAS                                           Department of Steel & Mines                  dsm.edespatch@od.gov.in            odisha.gov.in\n    ID-0153                 Sri Bimbadhar Pradhan                                                 Industries Department          bimbadhar.pradhan@odisha.gov.in            odisha.gov.in\n    ID-0162            Sri Laxmikanta Mishra, OSS                                                     Energy Department                         energy@od.gov.in            odisha.gov.in\n    ID-0175       Shri Sukanta Kumar Pradhan, OAS                    Skill Development & Technical Education Department                      sdte.addl@gmail.com            odisha.gov.in\n    ID-0182           Smt. Madhusmita Behera, OFS                          Handlooms, Textiles & Handicrafts Department           madhusmitabehera0711@gmail.com            odisha.gov.in\n    ID-0183                Sri Arindam Dakua, IAS                             Department of Housing & Urban Development                        dmahudd@gmail.com            odisha.gov.in\n    ID-0184               Smt. Lipsa Das, OAS(SS)                                      Department of Public Enterprises                 lipsa.das2@odisha.gov.in            odisha.gov.in\n    ID-0185                     Sri Lingaraj Otta                     Forest, Environment and Climate Change Department              lingaraj.otta@odisha.gov.in            odisha.gov.in\n    ID-0188          Dr. Debi Dutta Tripathy, OFS                                                     Energy Department                         energy@od.gov.in            odisha.gov.in\n    ID-0191              Ms. Rajani Jani, OAS(SS) Social Security & Empowerment of Persons with Disabilities Department                rajani.jani@odisha.gov.in            odisha.gov.in\n    ID-0193                     Sri Ganeswar Jena                      Department of Agriculture & Farmers' Empowerment                  ganeswarjena2@gmail.com            odisha.gov.in\n    ID-0204                 Sri Saroj Kumar Sahoo                                           Department of Steel & Mines                     sksahoo667@gmail.com            odisha.gov.in\n    ID-0205                     Smt. Lipsa Prusty                                           Department of Steel & Mines              itpmu@orissaminerals.gov.in            odisha.gov.in\n    ID-0206             Shri Jitendra Kumar Panda                                           Department of Steel & Mines        mo.baripada@orissaminerals.gov.in            odisha.gov.in\n    ID-0208             Sri Biswajit Routray, OTS                                                 Department of Tourism          ad.tourism@odishatourism.gov.in     odishatourism.gov.in\n    ID-0210             Er. Kshiradhar Kandhapani                                                      Works Department                        eenhjpr.od@gov.in                   gov.in\n    ID-0212                     Er. Gayatri Patel                                                      Works Department                   gayatriuce@yahoo.co.in            odisha.gov.in\n    ID-0215                   Er. Tara Pr. Mishra                                                      Works Department                       ceroads.owd@gov.in                   gov.in\n    ID-0216                 Er. Rama Kr. Moharana                                                      Works Department                         cewbp.owd@gov.in                   gov.in\n    ID-0222            Er. Subhransu Sekhar Swain                                                      Works Department                      ssswain@pmuosrp.org            odisha.gov.in\n    ID-0224               Er. Sudhi Ranjan Mishra                                                      Works Department                   eepwdboudha.owd@gov.in            odisha.gov.in\n    ID-0233                     Er. Gouranga Sahu                                                      Works Department                   cebuildings.owd@gov.in                   gov.in\n    ID-0239               Dr. Narayan Chandra Pal                                                      Works Department                     cedesigns.owd@gov.in                   gov.in\n    ID-0250                  Er. Binod Bihari Das                                                      Works Department                        eenhsbp.od@gov.in                   gov.in\n    ID-0251                    Er. Satyaban Patel                                                      Works Department                        eenhjsg@gmail.com            odisha.gov.in\n    ID-0252        Er. Archana Das Pattanaik, IAS                                                  Department of Excise                        archana.dp@gov.in            odisha.gov.in\n    ID-0261                     Smt. Usharani Das                                            Department of Co-operation               usharani.das@odisha.gov.in            odisha.gov.in\n    ID-0264                        Puneet Chandok                                                       Microsoft India             puneet.chandok@microsoft.com            microsoft.com\n    ID-0265                           Rajiv Kumar                                                       Microsoft India                rajiv.kumar@microsoft.com            microsoft.com\n    ID-0266                        Himani Agrawal                                                       Microsoft India             himani.agrawal@microsoft.com            microsoft.com\n    ID-0267                           Aruna Singh                                                       Microsoft India                aruna.singh@microsoft.com            microsoft.com\n    ID-0268                      Dahnesh Dilkhush                                                       Microsoft India           dahnesh.dilkhush@microsoft.com            microsoft.com\n    ID-0269                     Aparna Kondaboina                                                       Microsoft India          aparna.kondaboina@microsoft.com            microsoft.com\n    ID-0270                         Preeti Lobana                                                          Google India                 preeti.lobana@google.com               go

In [69]:
personal_emails = dataset1[
    ~dataset1["role_based_email"]
].copy()

print("Personal-looking emails:", len(personal_emails))

display(
    personal_emails[
        [
            "identity_id",
            "name",
            "official_email",
            "organization"
        ]
    ].to_string(index=False)
)

Personal-looking emails: 310

"identity_id                                  name                           official_email                                                          organization\n    ID-0004                     Pruthwee Raj Pani                pruthweeraj1970@gmail.com                     Information & Public Relations Department, Odisha\n    ID-0007                        Yamini Sarangi                    yamini.sarangi@nic.in                                            Finance Department, Odisha\n    ID-0010                        Saumyajit Rout                 saumyajit.rout@gmail.com                                            Finance Department, Odisha\n    ID-0021                      Pranati Chhotray           pranati.chhotray@odisha.gov.in                                               Home Department, Odisha\n    ID-0022                      Samarendra Nayak           samarendra.nayak@odisha.gov.in                                               Home Department, Odisha\n    ID-0023                      G. Jagdish Kumar            gjagadish.kumar@odisha.gov.in                                               Home Department, Odisha\n    ID-0024                    Amiya Kumar Udgata          amiyakumar.udgata@odisha.gov.in                                               Home Department, Odisha\n    ID-0025                     Siba Prasad Panda                 siba.panda@odisha.gov.in                                               Home Department, Odisha\n    ID-0026                     Tarun Kumar Panda           tarunkumar.panda@odisha.gov.in                                               Home Department, Odisha\n    ID-0027                   Pradip Kumar Behera         pradipkumar.behera@odisha.gov.in                                               Home Department, Odisha\n    ID-0028                       Ratikanta Panda            ratikanta.panda@odisha.gov.in                                               Home Department, Odisha\n    ID-0029                      Suryanarayan Kar           suryanarayan.kar@odisha.gov.in                                               Home Department, Odisha\n    ID-0030                       Rajkishore Rout            rajkishore.rout@odisha.gov.in                                               Home Department, Odisha\n    ID-0031                       Aatish Anshuman                   aanshuman@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0032                          Abhinav Arya                       aarya@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0033                      Abhineet Prakash                    abhineet@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0034                    Akshaya Kumar Rath                      akrath@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0035                         Aparna Pandey                aparnapandey@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0036                   Abhijit Datta Banik                 adattabanik@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0037                            Abhik Jana                   abhikjana@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0038                    Abhishek Chowdhury                  achowdhury@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0039                         Akash Jaiswal                    ajaiswal@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0040                  Akhilesh Kumar Singh                     aksingh@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0041                              Akshay K                      akshay@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0042                      Amar Deep Sarkar                        amar@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0043                         Amrit B. Sahu                  amritbsahu@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0044                      Amrita Satapathy                  asatapathy@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0045                         Anamitra Basu                anamitrabasu@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0046                  Anasuya Roychowdhury               aroychowdhury@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0047                        Animesh Mandal                     animesh@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0048                  Anirban Bhattacharya                     anirban@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0049                           Ankit Dalal                  ankitdalal@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0050               Ankit Ravindra Deshmukh                      ankitd@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0053                          Balaram Pani                   dean_colleges@du.ac.in                                                   University of Delhi\n    ID-0055                      Ravindra D. Gudi                        dd.fia@iitb.ac.in                                                            IIT Bombay\n    ID-0061                         Ashok Chandra                           mdps@pnb.co.in                                                  Punjab National Bank\n    ID-0062                          Kalyan Kumar                           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0063                        M. Paramasivam                           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0064                Bibhu Prasad Mahapatra                           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0065                          D. Surendran                           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0068                Indranil Bhattacharyya                 ibhattacharya@rbi.org.in                                                 Reserve Bank of India\n    ID-0069                   Ajit Ratnakar Joshi                       pradsim@rbi.org.in                                                 Reserve Bank of India\n    ID-0070                           Aviral Jain                         aaria@rbi.org.in                                                 Reserve Bank of India\n    ID-0072                     Jayesh Sanghrajka            jayesh.sanghrajka@infosys.com                                                               Infosys\n    ID-0080                           Amit Syngle              amit.syngle@asianpaints.com                                                          Asian Paints\n    ID-0082                   Pankaj Kumar Bansal                        as.cd-coop@gov.in                                               Ministry of Cooperation\n    ID-0083                           Raman Kumar                        js.cd-coop@gov.in                                               Ministry of Cooperation\n    ID-0085                            Amit Kumar                           dir-ctp@gov.in                                               Ministry of Cooperation\n    ID-0087                           Afsar Ahmed                        dirol-coop@gov.in                                               Ministry of Cooperation\n    ID-0091                             Anuj Dash                    anujdash@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0092                        Arindam Sarkar                     asarkar@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0093                               Arjun S                      arjuns@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0094                             Arpan Das                    arpandas@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0095                    Arun Kumar Pradhan                   akpradhan@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0096                          Ashis Biswas                     abiswas@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0097                       Debadatta Swain                      dswain@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0098                        Debalina Ghosh                     deghosh@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0099                       Gaurav Bartarya                    bartarya@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0100                    Niharika Mohapatra                    niharika@iitbbs.ac.in                                                       IIT Bhubaneswar\n    ID-0109          Sri Pratap Chandra Hota, IAS                    mail.pchota@gmail.com                          Handlooms, Textiles & Handicrafts Department\n    ID-0114                  Shri Sabyasachi Hota                   sabyasachi.hota@gov.in                       Electronics & Information Technology Department\n    ID-0115          Smt. Sonia Behera, OAS (SAG)                    ssepdodisha@gmail.com Social Security & Empowerment of Persons with Disabilities Department\n    ID-0120                 Mr. Binaya Kumar Dash                   dashbinaya45@gmail.com                             Department of Housing & Urban Development\n    ID-0124          Shri Lalit Kumar Kanhar, OAS                           etet.od@nic.in                    Skill Development & Technical Education Department\n    ID-0126                  Shri Shaktikanta Ray              itpmu@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0127                      Sri Dillip Sahoo         mo.cuttack@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0128          Smt. Soojata Misra, OAS (SS)                        stscdev@gmail.com ST & SC Development, Minorities & Backward Classes Welfare Department\n    ID-0137            Smt. Banita Dash, OFS(SAG)                        stscdev@gmail.com ST & SC Development, Minorities & Backward Classes Welfare Department\n    ID-0138 Shri Shailendra Narayan Nayak, O.I.S.           shailendra.nayak@odisha.gov.in                                                 Industries Department\n    ID-0139                 Smt. Rashmi Kabi, OFS                   giapncodisha@gmail.com                                     Planning & Convergence Department\n    ID-0143           Shri Bhaskar Raito OAS(SAG)                    ssepdodisha@gmail.com Social Security & Empowerment of Persons with Disabilities Department\n    ID-0144          Sri Daridryabhanjan MM Patra                      dbmmpatra@gmail.com                      Department of Agriculture & Farmers' Empowerment\n    ID-0149          Shri Rama Chandra Kisku, OAS                  dsm.edespatch@od.gov.in                                           Department of Steel & Mines\n    ID-0153                 Sri Bimbadhar Pradhan          bimbadhar.pradhan@odisha.gov.in                                                 Industries Department\n    ID-0162            Sri Laxmikanta Mishra, OSS                         energy@od.gov.in                                                     Energy Department\n    ID-0175       Shri Sukanta Kumar Pradhan, OAS                      sdte.addl@gmail.com                    Skill Development & Technical Education Department\n    ID-0182           Smt. Madhusmita Behera, OFS           madhusmitabehera0711@gmail.com                          Handlooms, Textiles & Handicrafts Department\n    ID-0183                Sri Arindam Dakua, IAS                        dmahudd@gmail.com                             Department of Housing & Urban Development\n    ID-0184               Smt. Lipsa Das, OAS(SS)                 lipsa.das2@odisha.gov.in                                      Department of Public Enterprises\n    ID-0185                     Sri Lingaraj Otta              lingaraj.otta@odisha.gov.in                     Forest, Environment and Climate Change Department\n    ID-0188          Dr. Debi Dutta Tripathy, OFS                         energy@od.gov.in                                                     Energy Department\n    ID-0191              Ms. Rajani Jani, OAS(SS)                rajani.jani@odisha.gov.in Social Security & Empowerment of Persons with Disabilities Department\n    ID-0193                     Sri Ganeswar Jena                  ganeswarjena2@gmail.com                      Department of Agriculture & Farmers' Empowerment\n    ID-0204                 Sri Saroj Kumar Sahoo                     sksahoo667@gmail.com                                           Department of Steel & Mines\n    ID-0205                     Smt. Lipsa Prusty              itpmu@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0206             Shri Jitendra Kumar Panda        mo.baripada@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0208             Sri Biswajit Routray, OTS          ad.tourism@odishatourism.gov.in                                                 Department of Tourism\n    ID-0210             Er. Kshiradhar Kandhapani                        eenhjpr.od@gov.in                                                      Works Department\n    ID-0212                     Er. Gayatri Patel                   gayatriuce@yahoo.co.in                                                      Works Department\n    ID-0215                   Er. Tara Pr. Mishra                       ceroads.owd@gov.in                                                      Works Department\n    ID-0216                 Er. Rama Kr. Moharana                         cewbp.owd@gov.in                                                      Works Department\n    ID-0222            Er. Subhransu Sekhar Swain                      ssswain@pmuosrp.org                                                      Works Department\n    ID-0224               Er. Sudhi Ranjan Mishra                   eepwdboudha.owd@gov.in                                                      Works Department\n    ID-0233                     Er. Gouranga Sahu                   cebuildings.owd@gov.in                                                      Works Department\n    ID-0239               Dr. Narayan Chandra Pal                     cedesigns.owd@gov.in                                                      Works Department\n    ID-0250                  Er. Binod Bihari Das                        eenhsbp.od@gov.in                                                      Works Department\n    ID-0251                    Er. Satyaban Patel                        eenhjsg@gmail.com                                                      Works Department\n    ID-0252        Er. Archana Das Pattanaik, IAS                        archana.dp@gov.in                                                  Department of Excise\n    ID-0261                     Smt. Usharani Das               usharani.das@odisha.gov.in                                            Department of Co-operation\n    ID-0264                        Puneet Chandok             puneet.chandok@microsoft.com                                                       Microsoft India\n    ID-0265                           Rajiv Kumar                rajiv.kumar@microsoft.com                                                       Microsoft India\n    ID-0266                        Himani Agrawal             himani.agrawal@microsoft.com                                                       Microsoft India\n    ID-0267                           Aruna Singh                aruna.singh@microsoft.com                                                       Microsoft India\n    ID-0268                      Dahnesh Dilkhush           dahnesh.dilkhush@microsoft.com                                                       Microsoft India\n    ID-0269                     Aparna Kondaboina          aparna.kondaboina@microsoft.com                                                       Microsoft India\n    ID-0270                         Preeti Lobana                 preeti.lobana@google.com                                                          Google India\n    ID-0271                     Roma Datta Chobey                   roma.chobey@google.com                                                          Google India\n    ID-0272                 Sashikumar Sreedharan         sashikumar.sreedharan@google.com                                                    Google Cloud India\n    ID-0273                           Samir Kumar                    samir.kumar@amazon.in                                                          Amazon India\n    ID-0274                          Amit Agarwal                   amit.agarwal@amazon.in                                                                Amazon\n    ID-0275                         Sandeep Dutta             sandeep.dutta@aws.amazon.com                                             Amazon Web Services India\n    ID-0276                    Saurabh Srivastava             saurabh.srivastava@amazon.in                                                          Amazon India\n    ID-0277                 Roshni Nadar Malhotra              roshni.malhotra@hcltech.com                                                               HCLTech\n    ID-0278                        C. Vijayakumar                  vijayakumar@hcltech.com                                                               HCLTech\n    ID-0279                            Shiv Walia                   shiv.walia@hcltech.com                                                               HCLTech\n    ID-0280                     Jagadeshwar Gattu            jagadeshwar.gattu@hcltech.com                                                               HCLTech\n    ID-0281                          Vijay Guntur                 vijay.guntur@hcltech.com                                                               HCLTech\n    ID-0282             Ramachandran Sundararajan    ramachandran.sundararajan@hcltech.com                                                               HCLTech\n    ID-0283                           Mohit Joshi             mohit.joshi@techmahindra.com                                                         Tech Mahindra\n    ID-0284                           Atul Soneja             atul.soneja@techmahindra.com                                                         Tech Mahindra\n    ID-0285                           Rohit Anand             rohit.anand@techmahindra.com                                                         Tech Mahindra\n    ID-0286                          Richard Lobo            richard.lobo@techmahindra.com                                                         Tech Mahindra\n    ID-0287                          Sahil Dhawan            sahil.dhawan

In [72]:
# Create a new email using the person's name
def generate_email(name, domain):
    name = re.sub(
        r"\b(Dr|Mr|Mrs|Ms|Smt|Shri|Sri|Er|IAS|OAS|OFS|OSS|SAG|SS)\.?\b",
        "",
        str(name),
        flags=re.I
    )

    parts = re.findall(r"[a-zA-Z]+", name.lower())

    if len(parts) >= 2:
        first = parts[0]
        last = parts[-1]
        email_name = f"{first}.{last}"
    else:
        email_name = parts[0]

    return f"{email_name}@{domain}"

In [73]:
print(generate_email("Pranati Chhotray", "odisha.gov.in"))
print(generate_email("Sandeep Bakhshi", "icicibank.com"))
print(generate_email("Amit Agarwal", "amazon.in"))

pranati.chhotray@odisha.gov.in
sandeep.bakhshi@icicibank.com
amit.agarwal@amazon.in

In [74]:
import re

def is_suspicious_email(row):
    email = row["official_email"].lower()
    local = email.split("@")[0]

    # Remove separators
    clean_local = re.sub(r"[^a-z]", "", local)

    # Extract name parts
    name = re.sub(
        r"\b(Dr|Mr|Mrs|Ms|Smt|Shri|Sri|Er|IAS|OAS|OFS|OSS|SAG|SS)\.?\b",
        "",
        str(row["name"]),
        flags=re.I
    )

    name_parts = re.findall(r"[a-zA-Z]+", name.lower())
    name_parts = [x for x in name_parts if len(x) >= 3]

    # Check whether any meaningful name part appears in the email
    name_match = any(part in clean_local for part in name_parts)

    # Detect obvious random patterns
    has_numbers = bool(re.search(r"\d", local))
    random_words = ["random", "test", "temp", "dummy", "sample", "user123"]

    has_random_word = any(word in local for word in random_words)

    return (not name_match) and (has_numbers or has_random_word)


suspicious_emails = personal_emails[
    personal_emails.apply(is_suspicious_email, axis=1)
].copy()

print("Suspicious emails:", len(suspicious_emails))

display(
    suspicious_emails[
        ["identity_id", "name", "official_email", "organization"]
    ].to_string(index=False)
)

Suspicious emails: 0

'Empty DataFrame\nColumns: [identity_id, name, official_email, organization]\nIndex: []'

In [75]:
def name_email_match(row):
    # Clean name
    name = re.sub(
        r"\b(Dr|Mr|Mrs|Ms|Smt|Shri|Sri|Er|IAS|OAS|OFS|OSS|SAG|SS)\.?\b",
        "",
        str(row["name"]),
        flags=re.I
    )

    name_parts = re.findall(r"[a-zA-Z]+", name.lower())
    name_parts = [p for p in name_parts if len(p) >= 3]

    # Email local part
    local = row["official_email"].split("@")[0].lower()
    local_clean = re.sub(r"[^a-z]", "", local)

    # At least one name component should appear
    return any(part in local_clean for part in name_parts)


personal_emails["name_match"] = personal_emails.apply(
    name_email_match,
    axis=1
)

possible_wrong = personal_emails[
    personal_emails["name_match"] == False
].copy()

print("Possible wrong name/email combinations:", len(possible_wrong))

display(
    possible_wrong[
        [
            "identity_id",
            "name",
            "official_email",
            "organization"
        ]
    ].to_string(index=False)
)

Possible wrong name/email combinations: 38

'identity_id                            name                    official_email                                                          organization\n    ID-0053                    Balaram Pani            dean_colleges@du.ac.in                                                   University of Delhi\n    ID-0055                Ravindra D. Gudi                 dd.fia@iitb.ac.in                                                            IIT Bombay\n    ID-0061                   Ashok Chandra                    mdps@pnb.co.in                                                  Punjab National Bank\n    ID-0062                    Kalyan Kumar                    hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0063                  M. Paramasivam                    hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0064          Bibhu Prasad Mahapatra                    hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0065                    D. Surendran                    hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0068          Indranil Bhattacharyya          ibhattacharya@rbi.org.in                                                 Reserve Bank of India\n    ID-0069             Ajit Ratnakar Joshi                pradsim@rbi.org.in                                                 Reserve Bank of India\n    ID-0070                     Aviral Jain                  aaria@rbi.org.in                                                 Reserve Bank of India\n    ID-0082             Pankaj Kumar Bansal                 as.cd-coop@gov.in                                               Ministry of Cooperation\n    ID-0083                     Raman Kumar                 js.cd-coop@gov.in                                               Ministry of Cooperation\n    ID-0085                      Amit Kumar                    dir-ctp@gov.in                                               Ministry of Cooperation\n    ID-0087                     Afsar Ahmed                 dirol-coop@gov.in                                               Ministry of Cooperation\n    ID-0115    Smt. Sonia Behera, OAS (SAG)             ssepdodisha@gmail.com Social Security & Empowerment of Persons with Disabilities Department\n    ID-0124    Shri Lalit Kumar Kanhar, OAS                    etet.od@nic.in                    Skill Development & Technical Education Department\n    ID-0126            Shri Shaktikanta Ray       itpmu@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0127                Sri Dillip Sahoo  mo.cuttack@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0128    Smt. Soojata Misra, OAS (SS)                 stscdev@gmail.com ST & SC Development, Minorities & Backward Classes Welfare Department\n    ID-0137      Smt. Banita Dash, OFS(SAG)                 stscdev@gmail.com ST & SC Development, Minorities & Backward Classes Welfare Department\n    ID-0139           Smt. Rashmi Kabi, OFS            giapncodisha@gmail.com                                     Planning & Convergence Department\n    ID-0143     Shri Bhaskar Raito OAS(SAG)             ssepdodisha@gmail.com Social Security & Empowerment of Persons with Disabilities Department\n    ID-0149    Shri Rama Chandra Kisku, OAS           dsm.edespatch@od.gov.in                                           Department of Steel & Mines\n    ID-0162      Sri Laxmikanta Mishra, OSS                  energy@od.gov.in                                                     Energy Department\n    ID-0175 Shri Sukanta Kumar Pradhan, OAS               sdte.addl@gmail.com                    Skill Development & Technical Education Department\n    ID-0183          Sri Arindam Dakua, IAS                 dmahudd@gmail.com                             Department of Housing & Urban Development\n    ID-0188    Dr. Debi Dutta Tripathy, OFS                  energy@od.gov.in                                                     Energy Department\n    ID-0205               Smt. Lipsa Prusty       itpmu@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0206       Shri Jitendra Kumar Panda mo.baripada@orissaminerals.gov.in                                           Department of Steel & Mines\n    ID-0208       Sri Biswajit Routray, OTS   ad.tourism@odishatourism.gov.in                                                 Department of Tourism\n    ID-0210       Er. Kshiradhar Kandhapani                 eenhjpr.od@gov.in                                                      Works Department\n    ID-0215             Er. Tara Pr. Mishra                ceroads.owd@gov.in                                                      Works Department\n    ID-0216           Er. Rama Kr. Moharana                  cewbp.owd@gov.in                                                      Works Department\n    ID-0224         Er. Sudhi Ranjan Mishra            eepwdboudha.owd@gov.in                                                      Works Department\n    ID-0233               Er. Gouranga Sahu            cebuildings.owd@gov.in                                                      Works Department\n    ID-0239         Dr. Narayan Chandra Pal              cedesigns.owd@gov.in                                                      Works Department\n    ID-0250            Er. Binod Bihari Das                 eenhsbp.od@gov.in                                                      Works Department\n    ID-0251              Er. Satyaban Patel                 eenhjsg@gmail.com                                                      Works Department'

In [76]:

# Separate obvious role/office emails from genuinely suspicious ones

role_patterns = [
    "director", "dean", "registrar", "secretary", "secy",
    "sec", "chairman", "chairperson", "cmo", "finance",
    "finsec", "admin", "office", "department", "dept",
    "investor", "institutional", "info", "support", "help",
    "rti", "media", "lab", "works", "tourism", "energy",
    "coop", "cooperation", "education", "health", "welfare",
    "development", "despatch", "pmu", "mo.", "ad.", "dd.",
    "as.", "js.", "dir-", "ce", "ee", "ae"
]

def looks_like_role_email(email):
    local = email.split("@")[0].lower()
    return any(pattern in local for pattern in role_patterns)


possible_wrong["role_email"] = possible_wrong["official_email"].apply(
    looks_like_role_email
)

genuine_suspicious = possible_wrong[
    possible_wrong["role_email"] == False
].copy()

print("Potentially genuine wrong emails:", len(genuine_suspicious))

display(
    genuine_suspicious[
        [
            "identity_id",
            "name",
            "official_email",
            "organization"
        ]
    ].to_string(index=False)
)

Potentially genuine wrong emails: 16

'identity_id                            name           official_email                                                          organization\n    ID-0061                   Ashok Chandra           mdps@pnb.co.in                                                  Punjab National Bank\n    ID-0062                    Kalyan Kumar           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0063                  M. Paramasivam           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0064          Bibhu Prasad Mahapatra           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0065                    D. Surendran           hosd@pnb.co.in                                                  Punjab National Bank\n    ID-0068          Indranil Bhattacharyya ibhattacharya@rbi.org.in                                                 Reserve Bank of India\n    ID-0069             Ajit Ratnakar Joshi       pradsim@rbi.org.in                                                 Reserve Bank of India\n    ID-0070                     Aviral Jain         aaria@rbi.org.in                                                 Reserve Bank of India\n    ID-0115    Smt. Sonia Behera, OAS (SAG)    ssepdodisha@gmail.com Social Security & Empowerment of Persons with Disabilities Department\n    ID-0124    Shri Lalit Kumar Kanhar, OAS           etet.od@nic.in                    Skill Development & Technical Education Department\n    ID-0128    Smt. Soojata Misra, OAS (SS)        stscdev@gmail.com ST & SC Development, Minorities & Backward Classes Welfare Department\n    ID-0137      Smt. Banita Dash, OFS(SAG)        stscdev@gmail.com ST & SC Development, Minorities & Backward Classes Welfare Department\n    ID-0139           Smt. Rashmi Kabi, OFS   giapncodisha@gmail.com                                     Planning & Convergence Department\n    ID-0143     Shri Bhaskar Raito OAS(SAG)    ssepdodisha@gmail.com Social Security & Empowerment of Persons with Disabilities Department\n    ID-0175 Shri Sukanta Kumar Pradhan, OAS      sdte.addl@gmail.com                    Skill Development & Technical Education Department\n    ID-0183          Sri Arindam Dakua, IAS        dmahudd@gmail.com                             Department of Housing & Urban Development'

In [77]:
import re
import pandas as pd

# -----------------------------------------
# 1. Extract email parts
# -----------------------------------------

def clean_name(name):
    name = re.sub(
        r"\b(Dr|Mr|Mrs|Ms|Smt|Shri|Sri|Er|IAS|OAS|OFS|OSS|SAG|SS)\.?\b",
        "",
        str(name),
        flags=re.I
    )
    return re.findall(r"[a-zA-Z]+", name.lower())


def email_local(email):
    return str(email).split("@")[0].lower()


def email_domain(email):
    parts = str(email).lower().split("@")
    return parts[1] if len(parts) == 2 else ""


# -----------------------------------------
# 2. Name ↔ Email check
# -----------------------------------------

def check_name_match(row):

    parts = clean_name(row["name"])
    local = re.sub(r"[^a-z]", "", email_local(row["official_email"]))

    # Remove very short initials
    meaningful_parts = [p for p in parts if len(p) >= 3]

    if not meaningful_parts:
        return "UNKNOWN"

    if any(part in local for part in meaningful_parts):
        return "MATCH"

    return "NO_MATCH"


# -----------------------------------------
# 3. Domain ↔ Official Domain check
# -----------------------------------------

def check_domain_match(row):

    email_dom = email_domain(row["official_email"])
    official_dom = str(row["official_domain"]).lower().strip()

    if not email_dom or not official_dom:
        return "INVALID"

    if email_dom == official_dom:
        return "MATCH"

    # Allow subdomains
    if email_dom.endswith("." + official_dom):
        return "SUBDOMAIN"

    if official_dom.endswith("." + email_dom):
        return "PARENT_DOMAIN"

    return "MISMATCH"


# -----------------------------------------
# 4. Detect public email providers
# -----------------------------------------

public_domains = {
    "gmail.com",
    "yahoo.com",
    "yahoo.co.in",
    "outlook.com",
    "hotmail.com",
    "rediffmail.com"
}


def check_public_email(row):
    return email_domain(row["official_email"]) in public_domains


# -----------------------------------------
# 5. Detect obvious role/shared addresses
# -----------------------------------------

role_patterns = [
    "director", "dean", "registrar", "secretary", "secy",
    "chairman", "chairperson", "cmo", "finance", "finsec",
    "admin", "office", "department", "dept", "investor",
    "institutional", "info", "support", "help", "rti",
    "media", "lab", "works", "tourism", "energy", "coop",
    "education", "health", "welfare", "development",
    "despatch", "pmu", "mo.", "ad.", "dd.", "as.",
    "js.", "dir-", "ce", "ee", "ae"
]


def check_role_email(row):

    local = email_local(row["official_email"])

    for pattern in role_patterns:
        if pattern in local:
            return True

    return False


# -----------------------------------------
# 6. Create full 500-record audit
# -----------------------------------------

email_audit = dataset1.copy()

email_audit["email_domain"] = email_audit.apply(
    email_domain, axis=1
)

email_audit["name_email_check"] = email_audit.apply(
    check_name_match, axis=1
)

email_audit["domain_check"] = email_audit.apply(
    check_domain_match, axis=1
)

email_audit["public_email"] = email_audit.apply(
    check_public_email, axis=1
)

email_audit["role_or_shared_email"] = email_audit.apply(
    check_role_email, axis=1
)


# -----------------------------------------
# 7. Duplicate email count
# -----------------------------------------

email_counts = (
    email_audit["official_email"]
    .str.lower()
    .value_counts()
)

email_audit["email_usage_count"] = (
    email_audit["official_email"]
    .str.lower()
    .map(email_counts)
)


# -----------------------------------------
# 8. Overall review category
# -----------------------------------------

def classify_email(row):

    # Clearly invalid domain
    if row["domain_check"] == "INVALID":
        return "INVALID"

    # Domain does not match recorded official domain
    if row["domain_check"] == "MISMATCH":
        return "DOMAIN_REVIEW"

    # Shared/role address
    if row["role_or_shared_email"]:
        return "ROLE_OR_SHARED_REVIEW"

    # Public provider
    if row["public_email"]:
        return "PUBLIC_PROVIDER_REVIEW"

    # Individual email doesn't relate to name
    if row["name_email_check"] == "NO_MATCH":
        return "NAME_REVIEW"

    return "PASS"


email_audit["email_status"] = email_audit.apply(
    classify_email,
    axis=1
)


# -----------------------------------------
# 9. Summary
# -----------------------------------------

print("Total records:", len(email_audit))
print("\nEmail status:")
print(email_audit["email_status"].value_counts())

print("\nName ↔ Email:")
print(email_audit["name_email_check"].value_counts())

print("\nDomain check:")
print(email_audit["domain_check"].value_counts())

print("\nPublic provider emails:",
      email_audit["public_email"].sum())

print("\nShared/duplicate emails:",
      (email_audit["email_usage_count"] > 1).sum())


# -----------------------------------------
# 10. Show ALL records needing review
# -----------------------------------------

review = email_audit[
    email_audit["email_status"] != "PASS"
].copy()

display(
    review[
        [
            "identity_id",
            "name",
            "organization",
            "official_email",
            "official_domain",
            "email_domain",
            "name_email_check",
            "domain_check",
            "public_email",
            "role_or_shared_email",
            "email_usage_count",
            "email_status"
        ]
    ].to_string(index=False)
)

Total records: 500

Email status:
email_status
PASS                     232
DOMAIN_REVIEW            169
ROLE_OR_SHARED_REVIEW     89
NAME_REVIEW               10
Name: count, dtype: int64

Name ↔ Email:
name_email_check
MATCH       273
NO_MATCH    227
Name: count, dtype: int64

Domain check:
domain_check
MATCH            318
MISMATCH         169
PARENT_DOMAIN     12
SUBDOMAIN          1
Name: count, dtype: int64

Public provider emails: 28

Shared/duplicate emails: 142

"identity_id                                    name                                                          organization                          official_email        official_domain                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             email_domain name_email_check  domain_check  public_email  role_or_shared_email  email_usage_count          email_status\n    ID-0001                      Mohan Charan Majhi                                                  Government of Odisha                              cmo@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://inpr.odisha.gov.in/en/about-us/whos-wh...\\nsource_type                              official government directory\\nname_clean                                            mohancharanmajhi\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 0, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0002                           Hemant Sharma                                                  Government of Odisha                        iprsec.or@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://inpr.odisha.gov.in/en/about-us/whos-wh...\\nsource_type                              official government directory\\nname_clean                                                hemantsharma\\nemail_local                                                  iprsec.or\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 1, dtype: object         NO_MATCH      MISMATCH         False                 False                  1         DOMAIN_REVIEW\n    ID-0003                Anuj Kumar Das Pattanaik                     Information & Public Relations Department, Odisha                  director-ipr.od@gov.in          odisha.gov.in                   gov.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://inpr.odisha.gov.in/en/about-us/whos-wh...\\nsource_type                              official government directory\\nname_clean                                       anujkumardaspattanaik\\nemail_local                                            director-ipr.od\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 2, dtype: object         NO_MATCH PARENT_DOMAIN         False                  True                  1 ROLE_OR_SHARED_REVIEW\n    ID-0004                       Pruthwee Raj Pani                     Information & Public Relations Department, Odisha               pruthweeraj1970@gmail.com          odisha.gov.in                gmail.com\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://inpr.odisha.gov.in/en/about-us/whos-wh...\\nsource_type                              official government directory\\nname_clean                                             pruthweerajpani\\nemail_local                                            pruthweeraj1970\\nname_email_match                                                  true\\nrole_based_email                                                 false\\nname: 3, dtype: object            MATCH      MISMATCH          True                  True                  1         DOMAIN_REVIEW\n    ID-0005                   Parthasarathi Mallick                     Information & Public Relations Department, Odisha                          rti-ori@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://inpr.odisha.gov.in/en/about-us/whos-wh...\\nsource_type                              official government directory\\nname_clean                                        parthasarathimallick\\nemail_local                                                    rti-ori\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 4, dtype: object         NO_MATCH      MISMATCH         False                  True                  1         DOMAIN_REVIEW\n    ID-0006                    Sanjeeb Kumar Mishra                                            Finance Department, Odisha                        finsec.or@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://finance.odisha.gov.in/en/about-us/whos...\\nsource_type                              official government directory\\nname_clean                                          sanjeebkumarmishra\\nemail_local                                                  finsec.or\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 5, dtype: object         NO_MATCH      MISMATCH         False                  True                  4         DOMAIN_REVIEW\n    ID-0007                          Yamini Sarangi                                            Finance Department, Odisha                   yamini.sarangi@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://finance.odisha.gov.in/en/about-us/whos...\\nsource_type                              official government directory\\nname_clean                                               yaminisarangi\\nemail_local                                             yamini.sarangi\\nname_email_match                                                  true\\nrole_based_email                                                 false\\nname: 6, dtype: object            MATCH      MISMATCH         False                 False                  1         DOMAIN_REVIEW\n    ID-0008                         Satyapriya Rath                                            Finance Department, Odisha                        finsec.or@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://finance.odisha.gov.in/en/about-us/whos...\\nsource_type                              official government directory\\nname_clean                                              satyapriyarath\\nemail_local                                                  finsec.or\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 7, dtype: object         NO_MATCH      MISMATCH         False                  True                  4         DOMAIN_REVIEW\n    ID-0009                Krushna Chandra Satpathy                                            Finance Department, Odisha                        finsec.or@nic.in          odisha.gov.in                   nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://finance.odisha.gov.in/en/about-us/whos...\\nsource_type                              official government directory\\nname_clean                                      krushnachandrasatpathy\\nemail_local                                                  finsec.or\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 8, dtype: object         NO_MATCH      MISMATCH         False                  True                  4         DOMAIN_REVIEW\n    ID-0010                          Saumyajit Rout                                            Finance Department, Odisha                saumyajit.rout@gmail.com          odisha.gov.in                gmail.com\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://finance.odisha.gov.in/en/about-us/whos...\\nsource_type                              official government directory\\nname_clean                                               saumyajitrout\\nemail_local                                             saumyajit.rout\\nname_email_match                                                  true\\nrole_based_email                                                 false\\nname: 9, dtype: object            MATCH      MISMATCH          True                 False                  1         DOMAIN_REVIEW\n    ID-0011                          Saswata Mishra                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                               saswatamishra\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 10, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0012                       Manoj Kumar Sahoo                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                             manojkumarsahoo\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 11, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0013                             Anupam Saha                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                                  anupamsaha\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 12, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0014                  Prasanna Kumar Sarangi                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                        prasannakumarsarangi\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 13, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0015                            Mirdha Toppo                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                                 mirdhatoppo\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 14, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0016                          Chitrasen Rout                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                               chitrasenrout\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 15, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0017                  Umesh Chandra Tripathy                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                        umeshchandratripathy\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 16, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0018                       Trilochan Mohanty                                       Chief Minister's Office, Odisha                              cmo@nic.in          odisha.gov.in                  nic.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                            trilochanmohanty\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 17, dtype: object         NO_MATCH      MISMATCH         False                  True                  9         DOMAIN_REVIEW\n    ID-0019                      Pradip Kumar Samal                                       Chief Minister's Office, Odisha                           cmo@od.gov.in          odisha.gov.in               od.gov.in\\nofficial_domain                                          odisha.gov.in\\norganization_type                                           government\\ncountry                                                          india\\nsource_url           https://odisha.gov.in/index.php/en/about-us/wh...\\nsource_type                              official government directory\\nname_clean                                            pradipkumarsamal\\nemail_local                                                        cmo\\nname_email_match                                                 false\\nrole_based_email                                                  true\\nname: 18, dtype: object         NO_MATCH      MISMATCH         False                  True                  1         DOMA

In [5]:

# DATASET 1 — FINAL VALIDATION

import re
import pandas as pd

df = df1.copy()

results = {}

# 1. Row count
results["Rows = 500"] = len(df) == 500

# 2. Required columns
required_cols = [
    "identity_id", "name", "role", "organization",
    "official_email", "official_domain",
    "organization_type", "country",
    "source_url", "source_type"
]
results["Required columns"] = set(required_cols).issubset(df.columns)

# 3. Identity IDs
expected_ids = {f"ID-{i:04d}" for i in range(1, 501)}
actual_ids = set(df["identity_id"].astype(str))

results["500 unique identity IDs"] = (
    df["identity_id"].nunique() == 500
)

results["IDs ID-0001 to ID-0500"] = (
    actual_ids == expected_ids
)

# 4. Missing values
results["No missing values"] = (
    df[required_cols].isna().sum().sum() == 0
)

# 5. Blank strings
results["No blank strings"] = (
    df[required_cols]
    .astype(str)
    .apply(lambda col: col.str.strip().eq("").sum())
    .sum() == 0
)

# 6. Duplicate rows
results["No duplicate rows"] = (
    df.duplicated().sum() == 0
)

# 7. Email syntax
email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_emails = df[
    ~df["official_email"].astype(str).str.match(
        email_pattern, na=False
    )
]

results["Valid email syntax"] = (
    len(invalid_emails) == 0
)

# 8. Domain syntax
domain_pattern = r"^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

invalid_domains = df[
    ~df["official_domain"].astype(str).str.match(
        domain_pattern, na=False
    )
]

results["Valid domain syntax"] = (
    len(invalid_domains) == 0
)

# 9. Country
results["Country = India"] = (
    df["country"].astype(str).str.strip().str.lower().eq("india").all()
)

# 10. Organization type
allowed_types = {
    "Government",
    "Company/Executive",
    "Education",
    "Banking/Financial",
    "PSU/Public Institution",
    "Regulator"
}

invalid_types = df[
    ~df["organization_type"].isin(allowed_types)
]

results["Valid organization types"] = (
    len(invalid_types) == 0
)

# 11. Email duplicates — informational only
email_counts = (
    df["official_email"]
    .str.lower()
    .value_counts()
)

duplicate_email_count = (
    (email_counts > 1).sum()
)

duplicate_email_records = (
    email_counts[email_counts > 1].sum()
)

# 12. Public-provider emails — informational only
public_domains = {
    "gmail.com",
    "yahoo.com",
    "yahoo.co.in",
    "outlook.com",
    "hotmail.com",
    "rediffmail.com"
}

public_email_count = df[
    df["official_email"]
    .str.lower()
    .str.split("@")
    .str[-1]
    .isin(public_domains)
].shape[0]

# -----------------------------------------
# FINAL REPORT
# -----------------------------------------

print("=" * 55)
print("DATASET 1 — FINAL VALIDATION REPORT")
print("=" * 55)

for check, passed in results.items():
    print(f"{'PASS' if passed else 'FAIL':6} | {check}")

print("\nInformational checks:")
print(f"Unique email addresses       : {df['official_email'].nunique()}")
print(f"Shared/duplicate email types : {duplicate_email_count}")
print(f"Records using shared emails  : {duplicate_email_records}")
print(f"Public-provider emails       : {public_email_count}")

print("\n" + "=" * 55)

if all(results.values()):
    print("FINAL STATUS: PASS ✅")
    print("DATASET 1 IS READY TO FREEZE.")
else:
    print("FINAL STATUS: REVIEW REQUIRED ⚠️")

    print("\nFailed checks:")
    for check, passed in results.items():
        if not passed:
            print(" -", check)

=======================================================
DATASET 1 — FINAL VALIDATION REPORT
=======================================================
PASS   | Rows = 500
PASS   | Required columns
PASS   | 500 unique identity IDs
PASS   | IDs ID-0001 to ID-0500
PASS   | No missing values
PASS   | No blank strings
PASS   | No duplicate rows
PASS   | Valid email syntax
PASS   | Valid domain syntax
PASS   | Country = India
PASS   | Valid organization types

Informational checks:
Unique email addresses       : 388
Shared/duplicate email types : 30
Records using shared emails  : 142
Public-provider emails       : 28

=======================================================
FINAL STATUS: PASS ✅
DATASET 1 IS READY TO FREEZE.

# dataset 2 testing

In [9]:
df2

,message_id,identity_id,identity_name,identity_role,organization,organization_type,organization_domain,sender_name,sender_email,receiver_name,...,urgency_level,has_link,has_attachment,link_domain_class,data_type,generation_version,generation_batch,generator_type,generation_seed,research_source
0,2f2bfd59-a7dd-4b01-b5d3-5a9a25b4b16b,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Mohan Charan Majhi,cmo@nic.in,Anita Sharma,...,NORMAL,False,False,NONE,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
1,2f3f52c3-c970-45d9-82c0-a2704a1b5b5b,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Mohan Charan Majhi,cmo@nic.in,Sneha Sen,...,NORMAL,True,False,VENDOR,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
2,2785a537-b1d6-43f8-9266-6175cfdda32b,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Sasmita Verma,sasmita.verma@induscabling.co.in,Mohan Charan Majhi,...,NORMAL,False,False,NONE,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
3,93d8a1b4-74ba-4938-b3e2-6b58cb8587a3,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Rohit Acharya,rohit.acharya@odisha.gov.in,Mohan Charan Majhi,...,NORMAL,False,False,NONE,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
4,b1dc7f51-5ffa-4fcd-a604-4149f2ace1b7,ID-0001,Mohan Charan Majhi,Chief Minister,Government of Odisha,Government,odisha.gov.in,Preeti Acharya,preetia@odisha.gov.in,Mohan Charan Majhi,...,NORMAL,True,False,PARTNER,train,v7,BATCH_01,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,c6c06265-ec84-4f85-ad24-d8043207622b,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Sandip Trivedi,director@tifr.res.in,Geeta Reddy,...,NORMAL,True,False,CLOUD,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9996,5e0145b6-6a14-4c6f-a951-a2df7f1d07a9,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Nandini Menon,nandini.menon@tifr.res.in,Sandip Trivedi,...,MEDIUM,True,False,ORG,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9997,48ceacc5-d104-4d73-8dac-9cd01c69bc43,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Itishree Dutta,itishree.dutta@icai.info,Sandip Trivedi,...,NORMAL,True,False,PARTNER,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9998,fa9f73a3-b28a-43c7-a5fc-de559cb67ed9,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Amit Iyer,amit.iyer@kpmg-office.com,Sandip Trivedi,...,NORMAL,False,False,NONE,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05
9999,519775e2-64f8-4628-9766-09f22ed2918b,ID-0500,Sandip Trivedi,Director,Tata Institute of Fundamental Research,Education,tifr.res.in,Sandip Trivedi,director@tifr.res.in,Prakash Trivedi,...,NORMAL,True,False,SHORTENED,train,v7,BATCH_05,COMPOSITIONAL_GRAMMAR,20260919,CYBERGUARD_V7_BATCH_05

In [13]:
data=df2[1]

KeyError: 1

In [14]:
df2.loc[0]

message_id                              2f2bfd59-a7dd-4b01-b5d3-5a9a25b4b16b
identity_id                                                          ID-0001
identity_name                                             Mohan Charan Majhi
identity_role                                                 Chief Minister
organization                                            Government of Odisha
organization_type                                                 Government
organization_domain                                            odisha.gov.in
sender_name                                               Mohan Charan Majhi
sender_email                                                      cmo@nic.in
receiver_name                                                   Anita Sharma
receiver_email                                     anita.sharma@meity.gov.in
reply_to                                                                 NaN
date                                                    2026-01-02T13:55:00Z
subject                                         Payment schedule for January
message                    Dear Anita,\n\nOur status on the digital recor...
label                                                             LEGITIMATE
attack_type                                                             NONE
impersonation_mechanism                                                 NONE
sender_relationship                                            SELF_OUTBOUND
scenario_family                             LEGIT/payment/MOVE_MONEY:payment
request_category                                                     payment
domain_match                                                           False
reply_to_match                                                          True
risk_signals                                 DOMAIN_MISMATCH;PAYMENT_REQUEST
urgency_level                                                         NORMAL
has_link                                                               False
has_attachment                                                         False
link_domain_class                                                       NONE
data_type                                                              train
generation_version                                                        v7
generation_batch                                                    BATCH_01
generator_type                                         COMPOSITIONAL_GRAMMAR
generation_seed                                                     20260919
research_source                                       CYBERGUARD_V7_BATCH_01
Name: 0, dtype: object

In [16]:
# DATASET 2 v7 — CHECK 1
# Basic structure validation

print("Shape:", df2.shape)

print("\nColumns:")
for i, col in enumerate(df2.columns, 1):
    print(i, col)

print("\nNumber of columns:", len(df2.columns))
print("Number of rows:", len(df2))

Shape: (10000, 34)

Columns:
1 message_id
2 identity_id
3 identity_name
4 identity_role
5 organization
6 organization_type
7 organization_domain
8 sender_name
9 sender_email
10 receiver_name
11 receiver_email
12 reply_to
13 date
14 subject
15 message
16 label
17 attack_type
18 impersonation_mechanism
19 sender_relationship
20 scenario_family
21 request_category
22 domain_match
23 reply_to_match
24 risk_signals
25 urgency_level
26 has_link
27 has_attachment
28 link_domain_class
29 data_type
30 generation_version
31 generation_batch
32 generator_type
33 generation_seed
34 research_source

Number of columns: 34
Number of rows: 10000

In [17]:
# DATASET 2 v7 — CHECK 2
# Missing-value validation

missing = df2.isna().sum()

print("Total missing cells:", missing.sum())

print("\nColumns with missing values:")
print(missing[missing > 0])

Total missing cells: 8110

Columns with missing values:
reply_to    8110
dtype: int64

In [18]:
# DATASET 2 v7 — CHECK 3
# Duplicate validation

print("Total rows:", len(df2))

print("\nDuplicate complete rows:",
      df2.duplicated().sum())

print("Duplicate message_id:",
      df2["message_id"].duplicated().sum())

print("Unique message_id:",
      df2["message_id"].nunique())

print("\nDuplicate message IDs:")
print(
    df2.loc[
        df2["message_id"].duplicated(keep=False),
        ["message_id", "identity_id", "label"]
    ]
    .sort_values("message_id")
    .to_string(index=False)
)

Total rows: 10000

Duplicate complete rows: 0
Duplicate message_id: 0
Unique message_id: 10000

Duplicate message IDs:
Empty DataFrame
Columns: [message_id, identity_id, label]
Index: []

In [19]:
# DATASET 2 v7 — CHECK 4
# Identity coverage validation

print("Unique identities in df2:",
      df2["identity_id"].nunique())

print("\nIdentity ID range:")
print("First:", df2["identity_id"].min())
print("Last :", df2["identity_id"].max())

# Expected Dataset 1 IDs
expected_ids = {f"ID-{i:04d}" for i in range(1, 501)}

actual_ids = set(df2["identity_id"].dropna().astype(str))

missing_ids = expected_ids - actual_ids
extra_ids = actual_ids - expected_ids

print("\nMissing Dataset 1 identities:", len(missing_ids))
print("Extra/invalid identities:", len(extra_ids))

if missing_ids:
    print("\nMissing IDs:")
    print(sorted(missing_ids))

if extra_ids:
    print("\nExtra/invalid IDs:")
    print(sorted(extra_ids))

Unique identities in df2: 500

Identity ID range:
First: ID-0001
Last : ID-0500

Missing Dataset 1 identities: 0
Extra/invalid identities: 0

In [20]:
# DATASET 2 v7 — CHECK 5
# Records per identity

identity_counts = df2["identity_id"].value_counts()

print("Minimum records per identity:", identity_counts.min())
print("Maximum records per identity:", identity_counts.max())

print("\nNumber of identities with exactly 20 records:",
      (identity_counts == 20).sum())

print("Number of identities with != 20 records:",
      (identity_counts != 20).sum())

# Show problematic identities, if any
problem_ids = identity_counts[identity_counts != 20]

if len(problem_ids) > 0:
    print("\nProblematic identities:")
    print(problem_ids.to_string())
else:
    print("\nAll 500 identities have exactly 20 records. ✅")

Minimum records per identity: 20
Maximum records per identity: 20

Number of identities with exactly 20 records: 500
Number of identities with != 20 records: 0

All 500 identities have exactly 20 records. ✅

In [21]:
# DATASET 2 v7 — CHECK 6
# Label distribution per identity

print("Overall label distribution:")
print(df2["label"].value_counts())

print("\nLabels per identity:")

label_counts = (
    df2.groupby(["identity_id", "label"])
    .size()
    .unstack(fill_value=0)
)

print(label_counts["LEGITIMATE"].value_counts())
print(label_counts["IMPERSONATION"].value_counts())

# Find identities that are not 10/10
problem_labels = label_counts[
    (label_counts.get("LEGITIMATE", 0) != 10) |
    (label_counts.get("IMPERSONATION", 0) != 10)
]

print("\nIdentities not having 10 LEGITIMATE + 10 IMPERSONATION:",
      len(problem_labels))

if len(problem_labels) > 0:
    print("\nProblematic identities:")
    print(problem_labels)
else:
    print("\nAll 500 identities have exactly 10/10 labels. ✅")

Overall label distribution:
label
LEGITIMATE       5000
IMPERSONATION    5000
Name: count, dtype: int64

Labels per identity:
LEGITIMATE
10    500
Name: count, dtype: int64
IMPERSONATION
10    500
Name: count, dtype: int64

Identities not having 10 LEGITIMATE + 10 IMPERSONATION: 0

All 500 identities have exactly 10/10 labels. ✅

In [22]:
# DATASET 2 v7 — CHECK 7
# Identity metadata consistency

identity_fields = [
    "identity_name",
    "identity_role",
    "organization",
    "organization_type",
    "organization_domain"
]

for col in identity_fields:
    counts = df2.groupby("identity_id")[col].nunique(dropna=False)

    inconsistent = counts[counts > 1]

    print(f"\n{col}")
    print("-" * 40)
    print("Identities with inconsistent values:", len(inconsistent))

    if len(inconsistent) > 0:
        print(inconsistent.to_string())

print("\nOverall check completed.")

identity_name
----------------------------------------
Identities with inconsistent values: 0

identity_role
----------------------------------------
Identities with inconsistent values: 0

organization
----------------------------------------
Identities with inconsistent values: 0

organization_type
----------------------------------------
Identities with inconsistent values: 0

organization_domain
----------------------------------------
Identities with inconsistent values: 0

Overall check completed.

In [24]:
# DATASET 2 v7 — CHECK 8
# Compare Dataset 2 identity metadata against frozen Dataset 1

fields = [
    "name",
    "role",
    "organization",
    "organization_type",
    "official_domain"
]

# Keep one identity-level row from Dataset 2
df2_identity = (
    df2[
        [
            "identity_id",
            "identity_name",
            "identity_role",
            "organization",
            "organization_type",
            "organization_domain"
        ]
    ]
    .drop_duplicates("identity_id")
)

# Prepare Dataset 1
df1_identity = df1[
    [
        "identity_id",
        "name",
        "role",
        "organization",
        "organization_type",
        "official_domain"
    ]
].copy()

# Merge
comparison = df2_identity.merge(
    df1_identity,
    on="identity_id",
    how="outer",
    suffixes=("_df2", "_df1"),
    indicator=True
)

# Compare each field
comparison["name_match"] = (
    comparison["identity_name"].astype(str).str.strip()
    ==
    comparison["name"].astype(str).str.strip()
)

comparison["role_match"] = (
    comparison["identity_role"].astype(str).str.strip()
    ==
    comparison["role"].astype(str).str.strip()
)

comparison["organization_match"] = (
    comparison["organization_df2"].astype(str).str.strip()
    ==
    comparison["organization_df1"].astype(str).str.strip()
)

comparison["type_match"] = (
    comparison["organization_type_df2"].astype(str).str.strip()
    ==
    comparison["organization_type_df1"].astype(str).str.strip()
)

comparison["domain_match"] = (
    comparison["organization_domain"].astype(str).str.lower().str.strip()
    ==
    comparison["official_domain"].astype(str).str.lower().str.strip()
)

print("Dataset 2 identities:", len(df2_identity))
print("Dataset 1 identities:", len(df1_identity))

print("\nName mismatches:",
      (~comparison["name_match"]).sum())

print("Role mismatches:",
      (~comparison["role_match"]).sum())

print("Organization mismatches:",
      (~comparison["organization_match"]).sum())

print("Organization type mismatches:",
      (~comparison["type_match"]).sum())

print("Official domain mismatches:",
      (~comparison["domain_match"]).sum())

# Show records with any mismatch
problem_comparison = comparison[
    (~comparison["name_match"]) |
    (~comparison["role_match"]) |
    (~comparison["organization_match"]) |
    (~comparison["type_match"]) |
    (~comparison["domain_match"])
]

print("\nIdentities with any mismatch:",
      len(problem_comparison))

if len(problem_comparison) > 0:
    display(problem_comparison.to_string(index=False))

Dataset 2 identities: 500
Dataset 1 identities: 500

Name mismatches: 0
Role mismatches: 0
Organization mismatches: 2
Organization type mismatches: 0
Official domain mismatches: 7

Identities with any mismatch: 9

'identity_id             identity_name                      identity_role                                organization_df2 organization_type_df2 organization_domain                      name                               role                                organization_df1 organization_type_df1 official_domain _merge  name_match  role_match  organization_match  type_match  domain_match\n    ID-0114      Shri Sabyasachi Hota Additional Secretary to Government Electronics & Information Technology Department            Government              gov.in      Shri Sabyasachi Hota Additional Secretary to Government Electronics & Information Technology Department            Government   odisha.gov.in   both        True        True                True        True         False\n    ID-0140 Sri Bijaya Kumar Mangaraj                  Special Secretary                              Finance Department            Government       odisha.gov.in Sri Bijaya Kumar Mangaraj                  Special Secretary                      Finance Department, Odisha            Government   odisha.gov.in   both        True        True               False        True          True\n    ID-0155   Shri Santosh Kumar Suar                  Special Secretary                              Finance Department            Government       odisha.gov.in   Shri Santosh Kumar Suar                  Special Secretary                      Finance Department, Odisha            Government   odisha.gov.in   both        True        True               False        True          True\n    ID-0210 Er. Kshiradhar Kandhapani       E.E (N.H. Division, Jeypore)                                Works Department            Government              gov.in Er. Kshiradhar Kandhapani       E.E (N.H. Division, Jeypore)                                Works Department            Government   odisha.gov.in   both        True        True                True        True         False\n    ID-0215       Er. Tara Pr. Mishra                     C.E. DPI&Roads                                Works Department            Government              gov.in       Er. Tara Pr. Mishra                     C.E. DPI&Roads                                Works Department            Government   odisha.gov.in   both        True        True                True        True         False\n    ID-0216     Er. Rama Kr. Moharana                    C.E. World Bank                                Works Department            Government              gov.in     Er. Rama Kr. Moharana                    C.E. World Bank                                Works Department            Government   odisha.gov.in   both        True        True                True        True         False\n    ID-0233         Er. Gouranga Sahu                 EIC-C.E. Buildings                                Works Department            Government              gov.in         Er. Gouranga Sahu                 EIC-C.E. Buildings                                Works Department            Government   odisha.gov.in   both        True        True                True        True         False\n    ID-0239   Dr. Narayan Chandra Pal                      E.I.C Designs                                Works Department            Government              gov.in   Dr. Narayan Chandra Pal                      E.I.C Designs                                Works Department            Government   odisha.gov.in   both        True        True                True        True         False\n    ID-0250      Er. Binod Bihari Das     E.E.(N.H. Division, Sambalpur)                                Works Department            Government              gov.in      Er. Binod Bihari Das     E.E.(N.H. Division, Sambalpur)                                Works Department            Government   odisha.gov.in   both        True        True                True        True         False'

In [25]:
# DATASET 2 v7 — CHECK 9
# Check organization/domain metadata consistency across all 10,000 records

problem_ids = [
    "ID-0114", "ID-0140", "ID-0155",
    "ID-0210", "ID-0215", "ID-0216",
    "ID-0233", "ID-0239", "ID-0250"
]

check9 = df2[
    df2["identity_id"].isin(problem_ids)
][
    [
        "identity_id",
        "identity_name",
        "organization",
        "organization_domain"
    ]
].drop_duplicates()

print("Unique metadata combinations for the 9 affected identities:")
print(check9.to_string(index=False))

Unique metadata combinations for the 9 affected identities:
identity_id             identity_name                                    organization organization_domain
    ID-0114      Shri Sabyasachi Hota Electronics & Information Technology Department              gov.in
    ID-0140 Sri Bijaya Kumar Mangaraj                              Finance Department       odisha.gov.in
    ID-0155   Shri Santosh Kumar Suar                              Finance Department       odisha.gov.in
    ID-0210 Er. Kshiradhar Kandhapani                                Works Department              gov.in
    ID-0215       Er. Tara Pr. Mishra                                Works Department              gov.in
    ID-0216     Er. Rama Kr. Moharana                                Works Department              gov.in
    ID-0233         Er. Gouranga Sahu                                Works Department              gov.in
    ID-0239   Dr. Narayan Chandra Pal                                Works Department              gov.in
    ID-0250      Er. Binod Bihari Das                                Works Department              gov.in

In [26]:
# DATASET 2 v7 — CHECK 9
# Sender email consistency with identity

# Get one row per identity/label/email combination
sender_check = (
    df2.groupby(
        ["identity_id", "identity_name", "label", "sender_name", "sender_email"],
        dropna=False
    )
    .size()
    .reset_index(name="record_count")
)

print("Unique sender identity combinations:", len(sender_check))

# Show sender emails for the 9 identities where Dataset 2
# metadata previously differed from Dataset 1
affected_ids = [
    "ID-0114", "ID-0140", "ID-0155",
    "ID-0210", "ID-0215", "ID-0216",
    "ID-0233", "ID-0239", "ID-0250"
]

affected_sender = sender_check[
    sender_check["identity_id"].isin(affected_ids)
]

display(
    affected_sender.sort_values(
        ["identity_id", "label", "sender_email"]
    ).to_string(index=False)
)

Unique sender identity combinations: 7854

'identity_id             identity_name         label                                  sender_name                           sender_email  record_count\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                                  Anita Nayak                     anita.nayak@gov.in             1\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                               Preeti Mohanty          preeti.mohanty@nimbuist.co.in             1\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                Rakesh Naidu (EA to Chairman)               rakesh.naidu@hotmail.com             1\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                              Sabyasachi Hota  sabyasachi.hota.office@protonmail.com             1\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                              Sabyasachi Hota             sabyasachi.hota30@yahoo.in             1\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                              Sabyasachi Hota                 sabyasachi.hota@gov.in             3\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                              Sabyasachi Hota             sabyasachi.hota@gov.org.in             1\n    ID-0114      Shri Sabyasachi Hota IMPERSONATION                            Snehasish Acharya               snehasish.acharya@gov.in             1\n    ID-0114      Shri Sabyasachi Hota    LEGITIMATE                             Debasish Acharya           debasish.acharya@bluepeak.in             1\n    ID-0114      Shri Sabyasachi Hota    LEGITIMATE                              Nandini Rastogi               nandini.rastogi@icai.org             1\n    ID-0114      Shri Sabyasachi Hota    LEGITIMATE                             Pratyush Mohanty               pratyush.mohanty@tcs.com             1\n    ID-0114      Shri Sabyasachi Hota    LEGITIMATE                              Sabyasachi Hota                 sabyasachi.hota@gov.in             6\n    ID-0114      Shri Sabyasachi Hota    LEGITIMATE                                    Vivek Rao                       vivek.rao@gov.in             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION                        Bijaya Kumar Mangaraj              bijaya.mangaraj@gmail.com             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION                        Bijaya Kumar Mangaraj         bijaya.mangaraj@rediffmail.com             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION                        Bijaya Kumar Mangaraj                       finsec.or@nic.in             3\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION                                  Lakshmi Das                  lakshmi.das@icai.info             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION                               Omkar Varghese          omkar.varghese@wiproindia.com             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION                               Prakash Mishra           prakash.mishra@odisha.gov.in             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION             Rajesh Tripathy (EA to Chairman)            rajesh.tripathy@hotmail.com             1\n    ID-0140 Sri Bijaya Kumar Mangaraj IMPERSONATION    Sarika Bansal (o/o Bijaya Kumar Mangaraj)               sarika.bansal@odisha.net             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                                 Ananya Sahoo             ananya.sahoo@odisha.gov.in             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                        Bijaya Kumar Mangaraj                       finsec.or@nic.in             3\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                                  Jyoti Joshi                  jyoti.joshi@yahoo.com             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                                Madhu Khuntia         madhu.khuntia@ecolinewaste.net             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                                 Naveen Ghosh             naveen.ghosh@odisha.gov.in             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                                  Rajesh Bose              rajesh.bose@odisha.gov.in             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                                  Ritu Thomas                    ritut@odisha.gov.in             1\n    ID-0140 Sri Bijaya Kumar Mangaraj    LEGITIMATE                              Snehasish Sahoo        snehasish.p.sahoo@odisha.gov.in             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                Ananya Reddy (EA to Chairman)               ananya.reddy@outlook.com             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                           Santosh Kumar Suar                       finsec.od@nic.in             2\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                                  Naveen Iyer                naveen.iyer@inofsys.com             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                                 Rajesh Dutta              rajesh.dutta@nic-india.in             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                           Santosh Kumar Suar          santosh.suar.office@gmail.com             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                           Santosh Kumar Suar     santosh.suar.office@protonmail.com             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                           Santosh Kumar Suar     santosh.suar.office@rediffmail.com             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                           Santosh Kumar Suar                santosh.suar@odisha.com             1\n    ID-0155   Shri Santosh Kumar Suar IMPERSONATION                           Santosh Kumar Suar             santosh.suar@odisha.gov.in             1\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                           Santosh Kumar Suar                       finsec.od@nic.in             4\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                             Lalit Chatterjee            lalit.chatterjee@ntpc.co.in             1\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                                 Neha Acharya              neha.acharya@axisbank.com             1\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                                Nikhil Sharma                   nikhil.sharma@nic.in             1\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                                Sandeep Verma sandeep.verma@silverlinecatering.co.in             1\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                              Shalini Pradhan  shalini.pradhan@vertexconsultancy.com             1\n    ID-0155   Shri Santosh Kumar Suar    LEGITIMATE                                   Zoya Barik                 zoya.barik@outlook.com             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION     Aditya Nayak (o/o Kshiradhar Kandhapani)                   aditya.nayak@gov.com             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION                        Administration Office          administration.office@gov.org             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION                        Administration Office                 administration@gov.net             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION                        Kshiradhar Kandhapani           kshiradhar.kandhapani@gov.in             2\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION                        Kshiradhar Kandhapani      kshiradhar.kandhapani@govindia.in             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION Lalit Chatterjee (o/o Kshiradhar Kandhapani)           lalit.chatterjee@govindia.in             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION               Sanjay Parida (EA to Chairman)                sanjay.parida@yahoo.com             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION                                 Tarun Pillai      tarun.pillai@meridianfaciiity.com             1\n    ID-0210 Er. Kshiradhar Kandhapani IMPERSONATION                 Usha Sharma (EA to Chairman)                  usha.sharma@gmail.com             1\n    ID-0210 Er. Kshiradhar Kandhapani    LEGITIMATE                        Kshiradhar Kandhapani                      eenhjpr.od@gov.in             6\n    ID-0210 Er. Kshiradhar Kandhapani    LEGITIMATE                                 Mohit Bansal     mohit.bansal@skylinenetworks.co.in             1\n    ID-0210 Er. Kshiradhar Kandhapani    LEGITIMATE                                 Sarika Sethi                 sarika.sethi@wipro.com             1\n    ID-0210 Er. Kshiradhar Kandhapani    LEGITIMATE                                    Sneha Rao               sneha.rao@protonmail.com             1\n    ID-0210 Er. Kshiradhar Kandhapani    LEGITIMATE                                  Varun Sethi                     varun.sethi@gov.in             1\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION          Ananya Kapoor (o/o Tara Pr. Mishra)                ananya.kapoor@gov.co.in             1\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION                              Tara Pr. Mishra                     ceroads.owd@gov.in             4\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION                               Lakshmi Kurien           lakshmi.kurien@nic-office.in             1\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION                                 Omkar Kurien               omkar.kurien@nabaard.org             1\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION            Omkar Naidu (o/o Tara Pr. Mishra)                  omkar.naidu@gov.co.in             1\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION                              Projects Office          projects.office@gov-office.in             1\n    ID-0215       Er. Tara Pr. Mishra IMPERSONATION                              Tara Pr. Mishra tara.mishra@gov.portal.docs-portal.com             1\n    ID-0215       Er. Tara Pr. Mishra    LEGITIMATE                            Ashirbad Banerjee            ashirbad.banerjee@yahoo.com             1\n    ID-0215       Er. Tara Pr. Mishra    LEGITIMATE                              Tara Pr. Mishra                     ceroads.owd@gov.in             8\n    ID-0215       Er. Tara Pr. Mishra    LEGITIMATE                                 Meera Thomas      meera.thomas@utkalelectricals.net             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                            Rama Kr. Moharana                       cewbp.owd@gov.in             3\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                              Planning Office                  planning@gov-india.in             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                                  Preeti Bose          preeti.bose@sagartrasport.net             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                            Rama Kr. Moharana                rama.moharana@gmail.com             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                            Rama Kr. Moharana             rama.moharana@gov-india.in             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                            Rama Kr. Moharana                   rama.moharana@gov.in             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                                  Ritu Thomas                     ritu.thomas@gov.in             1\n    ID-0216     Er. Rama Kr. Moharana IMPERSONATION                                 Suresh Malik                    suresh.malik@gov.in             1\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                            Rama Kr. Moharana                       cewbp.owd@gov.in             4\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                                Imran Khuntia              imran.khuntia@outlook.com             1\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                                Legal Section               legal.desk.office@gov.in             1\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                               Manish Routray                         manishr@gov.in             1\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                                  Rahul Naidu                     rahul.naidu@gov.in             1\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                                Shalini Naidu                  shalini.naidu@cdac.in             1\n    ID-0216     Er. Rama Kr. Moharana    LEGITIMATE                                   Zoya Ahuja         zoya.ahuja@skylinenetworks.com             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                                Gouranga Sahu                 cebuildings.owd@gov.in             3\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                                Gouranga Sahu                   gouranga.sahu@gov.in             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                                Gouranga Sahu                  gouranga.sahu@gov.org             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                                Gouranga Sahu               gouranga.sahu@gov.org.in             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                               Lalit Varghese                  lalit.varghese@gov.in             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION            Payal Agarwal (o/o Gouranga Sahu)               payal.agarwal@gov.org.in             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                                 Rohit Kapoor                    rohit.kapoor@gov.in             1\n    ID-0233         Er. Gouranga Sahu IMPERSONATION                                  Zoya Thomas                  zoya.thomas@cdac.info             1\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                                    Amit Seth                       amit.seth@gov.in             1\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                                 Bijaya Reddy       bijaya.reddy@prabhatprinting.com             1\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                                Gouranga Sahu                 cebuildings.owd@gov.in             4\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                                  Pooja Ahuja                     pooja.ahuja@gov.in             1\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                               Pratyush Panda                  pratyush.panda@gov.in             1\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                               Sandeep Kurien                        sandeepk@gov.in             1\n    ID-0233         Er. Gouranga Sahu    LEGITIMATE                                Smruti Chopra              smruti.chopra@niti.gov.in             1\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                          Narayan Chandra Pal                   cedesigns.owd@gov.in             2\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                          Narayan Chandra Pal            narayan.pal.office@yahoo.in             1\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                          Narayan Chandra Pal                    narayan.pal@gov.com             1\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                          Narayan Chandra Pal                     narayan.pal@gov.in             3\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                                 Suresh Nayak                    suresh.nayak@gov.in             1\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                                  Tarun Reddy                    tarun.reddy@gov.net             1\n    ID-0239   Dr. Narayan Chandra Pal IMPERSONATION                                    Usha Seth                       usha.seth@gov.in             1\n    ID-0239   Dr. Narayan Chandra Pal    LEGITIMATE                                  Anita Malik                  anita.malik@sbi.co.in             1\n    ID-0239   Dr. Narayan Chandra Pal    LEGITIMATE                                 Anjali Ghosh              anjali.ghosh@hdfcbank.com             1\n    ID-0239   Dr. Narayan Chandra Pal    LEGITIMATE                          Narayan Chandra Pal                   cedesigns.owd@gov.in             5\n    ID-0239   Dr. Narayan Chandra Pal    LEGITIMATE                              Naveen Varghese                 naveen.varghese@gov.in             1\n    ID-0239   Dr. Narayan Chandra Pal    LEGITIMATE                                 Nikhil Panda                         nikhilp@gov.in             1\n    ID-0239   Dr. Narayan Chandra Pal    LEGITIMATE                                 Payal Bansal                    payal.bansal@gov.in             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION                             Binod Bihari Das                     binod.das@gov.info             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION                                    Divya Sen                       divya.sen@gov.in             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION                             Binod Bihari Das                      eenhsbp.od@gov.in             3\n    ID-0250      Er. Binod Bihari Das IMPERSONATION                                 Service Desk                   it.support@gov.co.in             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION              Itishree Naidu (EA to Chairman)             itishree.naidu@hotmail.com             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION                Kavita Nayak (EA to Chairman)                 kavita.nayak@yahoo.com             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION           Snehasish Trivedi (EA to Chairman)            snehasish.trivedi@gmail.com             1\n    ID-0250      Er. Binod Bihari Das IMPERSONATION                             Vigilance Office               vigilance.office@gov.com             1\n    ID-0250      Er. Binod Bihari Das    LEGITIMATE                             Binod Bihari Das                      eenhsbp.od@gov.in             7\n    ID-0250      Er. Binod Bihari Das    LEGITIMATE                               Legal Helpdesk           legal.helpdesk.office@gov.in             1\n    ID-0250      Er. Binod Bihari Das    LEGITIMATE                              Shalini Routray shalini.routray@novatechinstruments.in             1\n    ID-0250      Er. Binod Bihari Das    LEGITIMATE                               Yashwant Gupta                  yashwant.gupta@gov.in             1'

In [27]:
# DATASET 2 v7 — CHECK 10
# Receiver name/email consistency

print("Missing receiver_name:", df2["receiver_name"].isna().sum())
print("Missing receiver_email:", df2["receiver_email"].isna().sum())

print("\nUnique receiver names:", df2["receiver_name"].nunique())
print("Unique receiver emails:", df2["receiver_email"].nunique())

print("\nMost common receiver emails:")
print(df2["receiver_email"].value_counts().head(20))

Missing receiver_name: 0
Missing receiver_email: 0

Unique receiver names: 3246
Unique receiver emails: 4891

Most common receiver emails:
receiver_email
workssec.od@nic.in             357
cmo@nic.in                     105
hthdepartment@gmail.com         91
ctsec.od@nic.in                 76
dsmsec.od@nic.in                74
labsec.od@nic.in                62
Secretarysme.od@nic.in          53
orhealth@nic.in                 53
secy-msme.od@od.gov.in          49
sportsysec.od@nic.in            48
dstsec.od@nic.in                46
wcdsec.or@od.gov.in             45
hosd@pnb.co.in                  43
finsec.or@nic.in                43
tourismsec.od@nic.in            36
excisesec.or@od.gov.in          32
lawsec.or@nic.in                28
itpmu@orissaminerals.gov.in     24
Investor.Relations@tcs.com      23
coopsec.or@nic.in               23
Name: count, dtype: int64

In [28]:
# DATASET 2 v7 — CHECK 11
# Check whether receiver_name and receiver_email stay consistent

receiver_check = (
    df2.groupby(["receiver_name", "receiver_email"], dropna=False)
    .size()
    .reset_index(name="record_count")
)

# How many different emails are associated with the same receiver name?
name_to_email = (
    receiver_check.groupby("receiver_name")["receiver_email"]
    .nunique()
)

# How many different names are associated with the same receiver email?
email_to_name = (
    receiver_check.groupby("receiver_email")["receiver_name"]
    .nunique()
)

print("Receiver names linked to multiple emails:",
      (name_to_email > 1).sum())

print("Receiver emails linked to multiple names:",
      (email_to_name > 1).sum())

print("\nExamples: receiver names with multiple emails")
print(
    name_to_email[name_to_email > 1]
    .sort_values(ascending=False)
    .head(20)
)

print("\nExamples: receiver emails with multiple names")
print(
    email_to_name[email_to_name > 1]
    .sort_values(ascending=False)
    .head(20)
)

Receiver names linked to multiple emails: 1271
Receiver emails linked to multiple names: 30

Examples: receiver names with multiple emails
receiver_name
Chirag Parida          7
Rahul Rao              6
Kavita Acharya         6
Tanvi Bansal           5
Tanvi Roy              5
Sunita Routray         5
Sneha Verma            5
Usha Trivedi           5
Suresh Acharya         5
Subrata Patnaik        5
Sunita Khuntia         5
Rajesh Bhattacharya    5
Suresh Dutta           5
Vikram Deshpande       5
Vikram Ghosh           5
Preeti Iyer            5
Nikhil Verma           5
Neha Bhat              5
Karan Varghese         5
Swati Kurien           4
Name: receiver_email, dtype: int64

Examples: receiver emails with multiple names
receiver_email
workssec.od@nic.in            33
cmo@nic.in                     9
hthdepartment@gmail.com        9
dsmsec.od@nic.in               8
ctsec.od@nic.in                7
labsec.od@nic.in               6
orhealth@nic.in                5
Secretarysme.od@nic.in         5
wcdsec.or@od.gov.in            4
sportsysec.od@nic.in           4
hosd@pnb.co.in                 4
excisesec.or@od.gov.in         4
dstsec.od@nic.in               4
finsec.or@nic.in               4
secy-msme.od@od.gov.in         4
lawsec.or@nic.in               3
tourismsec.od@nic.in           3
energy@od.gov.in               2
coopsec.or@nic.in              2
Investor.Relations@tcs.com     2
Name: receiver_name, dtype: int64

In [29]:
# DATASET 2 v7 — CHECK 11A
# Inspect receiver name/email inconsistencies

# Names associated with multiple receiver emails
name_multi = (
    receiver_check.groupby("receiver_name")
    .filter(lambda x: x["receiver_email"].nunique() > 1)
    .sort_values(["receiver_name", "receiver_email"])
)

print("=== RECEIVER NAMES WITH MULTIPLE EMAILS ===")
print(name_multi.head(100).to_string(index=False))

print("\n" + "="*80)

# Emails associated with multiple receiver names
email_multi = (
    receiver_check.groupby("receiver_email")
    .filter(lambda x: x["receiver_name"].nunique() > 1)
    .sort_values(["receiver_email", "receiver_name"])
)

print("=== RECEIVER EMAILS WITH MULTIPLE NAMES ===")
print(email_multi.head(100).to_string(index=False))

=== RECEIVER NAMES WITH MULTIPLE EMAILS ===
    receiver_name                        receiver_email  record_count
   Aditya Acharya          aditya.acharya@cognizant.com             1
   Aditya Acharya          aditya.acharya@ongcindia.com             1
   Aditya Acharya            aditya.acharya@pnbindia.in             1
   Aditya Agarwal             aditya.agarwal@meesho.com             1
   Aditya Agarwal          aditya.agarwal@odisha.gov.in             1
     Aditya Ahuja                aditya.ahuja@amazon.in             1
     Aditya Ahuja               aditya.ahuja@rbi.org.in             1
     Aditya Ahuja                  aditya.ahuja@tcs.com             1
   Aditya Chauhan         aditya.chauhan@mazagondock.in             1
   Aditya Chauhan          aditya.chauhan@odisha.gov.in             1
    Aditya Chopra           aditya.chopra@odisha.gov.in             1
    Aditya Chopra                  aditya.chopra@pwc.in             1
       Aditya Das              aditya.das@delhivery.com             1
       Aditya Das                 aditya.das@iitm.ac.in             1
      Aditya Iyer                    aditya.iyer@gov.in             1
      Aditya Iyer               aditya.iyer@npci.org.in             1
  Aditya Kulkarni            aditya.kulkarni@bsnl.co.in             1
  Aditya Kulkarni      aditya.kulkarni@maxhealthcare.in             1
  Aditya Kulkarni            aditya.kulkarni@yesbank.in             1
     Aditya Malik                  aditya.malik@cdac.in             1
     Aditya Malik            aditya.malik@honeywell.com             1
     Aditya Malik             aditya.malik@psbindia.com             1
   Aditya Mohanty aditya.mohanty@colgatepalmolive.co.in             1
   Aditya Mohanty           aditya.mohanty@iitbbs.ac.in             1
   Aditya Mohanty          aditya.mohanty@odisha.gov.in             1
     Aditya Naidu             aditya.naidu@iitbbs.ac.in             1
     Aditya Naidu            aditya.naidu@odisha.gov.in             1
     Aditya Naidu             aditya.naidu@psbindia.com             1
      Aditya Nair                aditya.nair@iitd.ac.in             1
      Aditya Nair                 aditya.nair@lupin.com             1
      Aditya Nair                 aditya.nair@nestle.in             1
     Aditya Nayak             aditya.nayak@iitbbs.ac.in             1
     Aditya Nayak            aditya.nayak@odisha.gov.in             1
     Aditya Panda            aditya.panda@capgemini.com             1
     Aditya Panda               aditya.panda@iitd.ac.in             1
     Aditya Panda                 aditya.panda@tata.com             1
       Aditya Rao             aditya.rao@aws.amazon.com             1
       Aditya Rao                aditya.rao@infosys.com             1
       Aditya Rao            aditya.rao@titancompany.in             1
   Aditya Routray     aditya.routray@cooperation.gov.in             1
   Aditya Routray             aditya.routray@nabard.org             1
       Aditya Roy                aditya.roy@hcltech.com             1
       Aditya Roy              aditya.roy@odisha.gov.in             1
       Aditya Sen              aditya.sen@capgemini.com             1
       Aditya Sen               aditya.sen@iitbbs.ac.in             1
       Aditya Sen              aditya.sen@odisha.gov.in             1
       Aditya Sen          aditya.sen@torrentpharma.com             1
    Aditya Sharma                 aditya.sharma@cdac.in             1
    Aditya Sharma            aditya.sharma@mahindra.com             1
    Aditya Sharma               aditya.sharma@sbi.co.in             1
     Aditya Singh          aditya.singh@adityabirla.com             1
     Aditya Singh              aditya.singh@isro.gov.in             1
     Aditya Singh               aditya.singh@rbi.org.in             1
  Aditya Tripathy          aditya.tripathy@iitbbs.ac.in             1
  Aditya Tripathy             aditya.tripathy@od.gov.in             1
   Aditya Trivedi             aditya.trivedi@biocon.com             1
   Aditya Trivedi           aditya.trivedi@hdfcbank.com             1
     Aditya Verma                aditya.verma@sbi.co.in             1
     Aditya Verma               aditya.verma@ugc.gov.in             1
     Alok Acharya             alok.acharya@iitbbs.ac.in             1
     Alok Acharya                alok.acharya@wipro.com             1
     Alok Agarwal        alok.agarwal@bits-pilani.ac.in             1
     Alok Agarwal            alok.agarwal@odisha.gov.in             1
       Alok Ahuja              alok.ahuja@microsoft.com             1
       Alok Ahuja                alok.ahuja@mphasis.com             1
       Alok Ahuja              alok.ahuja@odisha.gov.in             1
    Alok Banerjee           alok.banerjee@cognizant.com             1
    Alok Banerjee              alok.banerjee@iitk.ac.in             1
    Alok Banerjee           alok.banerjee@odisha.gov.in             1
      Alok Bansal              alok.bansal@iimcal.ac.in             1
      Alok Bansal             alok.bansal@itcportal.com             1
      Alok Bansal                alok.bansal@oracle.com             1
       Alok Barik              alok.barik@birlasoft.com             1
       Alok Barik               alok.barik@iitbbs.ac.in             1
       Alok Barik              alok.barik@odisha.gov.in             1
Alok Bhattacharya     alok.bhattacharya@ltimindtree.com             1
Alok Bhattacharya       alok.bhattacharya@odisha.gov.in             2
  Alok Chatterjee          alok.chatterjee@nitrkl.ac.in             1
  Alok Chatterjee         alok.chatterjee@odisha.gov.in             1
        Alok Dash                alok.dash@axisbank.com             1
        Alok Dash                alok.dash@drreddys.com             1
        Alok Dash               alok.dash@odisha.gov.in             1
        Alok Dash                      alok.dash@pwc.in             1
       Alok Gupta               alok.gupta@iitbbs.ac.in             2
       Alok Gupta              alok.gupta@odisha.gov.in             3
       Alok Joshi              alok.joshi@odisha.gov.in             1
       Alok Joshi                    alok.joshi@ril.com             1
      Alok Parida            alok.parida@canarabank.com             1
      Alok Parida               alok.parida@pnbindia.in             1
     Alok Patnaik                   alok.patnaik@gov.in             1
     Alok Patnaik            alok.patnaik@odisha.gov.in             1
     Alok Pradhan             alok.pradhan@coalindia.in             1
     Alok Pradhan             alok.pradhan@iitbbs.ac.in             1
     Alok Pradhan            alok.pradhan@odisha.gov.in             1
     Alok Rastogi                alok.rastogi@jnu.ac.in             1
     Alok Rastogi            alok.rastogi@odisha.gov.in             1
         Alok Roy         alok.roy@bankofmaharashtra.in             1
         Alok Roy                alok.roy@odisha.gov.in             1
         Alok Sen               alok.sen@newindia.co.in             1
         Alok Sen                alok.sen@odisha.gov.in             1

================================================================================
=== RECEIVER EMAILS WITH MULTIPLE NAMES ===
              receiver_name                      receiver_email  record_count
         Aarthi Subramanian          Investor.Relations@tcs.com            14
             K. Krithivasan          Investor.Relations@tcs.com             9
      Durgaprasad Mohapatra              Secretarysme.od@nic.in            10
       Girish Chandra Singh              Secretarysme.od@nic.in            12
          Manoj Kumar Padhy              Secretarysme.od@nic.in            15
          N. Thirumala Naik              Secretarysme.od@nic.in             6
              Sibashis Dhal              Secretarysme.od@nic.in            10
                Anupam Saha                          cmo@nic.in             9
             Chitrasen Rout                          cmo@nic.in            12
          Manoj Kumar Sahoo                          cmo@nic.in            12
               Mirdha Toppo                          cmo@nic.in            18
         Mohan Charan Majhi                          cmo@nic.in             7
     Prasanna Kumar Sarangi                          cmo@nic.in            12
             Saswata Mishra                          cmo@nic.in            13
          Trilochan Mohanty                          cmo@nic.in            12
     Umesh Chandra Tripathy                          cmo@nic.in            10
          Bishnupriya Sahoo                   coopsec.or@nic.in            11
       Surendra Kumar Sahoo                   coopsec.or@nic.in            12
         Amar Kumar Pradhan                     ctsec.od@nic.in            11
            Biswombar Sethi                     ctsec.od@nic.in             9
       Dharmendra Satapathy                     ctsec.od@nic.in             9
      Nirmala Kumari Biswal                     ctsec.od@nic.in            12
     Pradyumna Kumar Muduli                     ctsec.od@nic.in            12
             Umakanta Barik                     ctsec.od@nic.in            14
              Urmila Kanhar                     ctsec.od@nic.in             9
             Arvind K. Nema                 director@iitd.ac.in            11
            Rangan Banerjee                 director@iitd.ac.in             8
         Puspanjali Bisoi (                    dpesec.od@nic.in             8
        Susanta Kumar Singh                    dpesec.od@nic.in             5
          Daulat Chandrakar                    dsmsec.od@nic.in            10
           Ganapati Pradhan                    dsmsec.od@nic.in            12
       Gobinda Ch. Samantra                    dsmsec.od@nic.in             9
           Manoranjan Panda                    dsmsec.od@nic.in            10
             Narottam Sahoo                    dsmsec.od@nic.in             7
          Pradip Kumar Naik                    dsmsec.od@nic.in            10
            Rajat Kumar Kar                    dsmsec.od@nic.in             7
               Salil Behera                    dsmsec.od@nic.in             9
          Bidyut Prava Rout                    dstsec.od@nic.in             9
      Chinmayee Chetna Dash                    dstsec.od@nic.in            13
              Sunaram Murmu                    dstsec.od@nic.in            10
         Urmiprava Maharana                    dstsec.od@nic.in            14
        Debi Dutta Tripathy                    energy@od.gov.in            11
          Laxmikanta Mishra                    energy@od.gov.in             9
           Debashis Patnaik              excisesec.or@od.gov.in             8
             Parakhita Bhoi              excisesec.or@od.gov.in             7
      Probodh Kumar Dwibedy              excisesec.or@od.gov.in             6
            Trilochan Patra              excisesec.or@od.gov.in            11
      Bijaya Kumar Mangaraj                    finsec.or@nic.in            11
   Krushna Chandra Satpathy                    finsec.or@nic.in             8
       Sanjeeb Kumar Mishra                    finsec.or@nic.in            10
            Satyapriya Rath                    finsec.or@nic.in            14
         Bijay Kumar Prusty                    gadmin.or@nic.in            10
             Ghasiram Murmu                    gadmin.or@nic.in             9
     Bibhu Prasad Mahapatra                      hosd@pnb.co.in            12
               D. Surendran                      hosd@pnb.co.in            12
               Kalyan Kumar                      hosd@pnb.co.in            11
             M. Paramasivam                      hosd@pnb.co.in             8
           Abhijeet Routray             hthdepartment@gmail.com            12
             Anshuman Nayak             hthdepartment@gmail.com            10
           Chinmayee Biswal             hthdepartment@gmail.com            12
               Mamata Nayak             hthdepartment@gmail.com             9
          Mamata Samantaroy             hthdepartment@gmail.com             7
         Manas Ranjan Patra             hthdepartment@gmail.com            11
             Nilamani Nayak             hthdepartment@gmail.com            11
            Nivedita Prusty             hthdepartment@gmail.com            10
        Subrat Kumar Behera             hthdepartment@gmail.com             9
            Gangadhar Nayak                    hudsec.or@nic.in             8
       Subhananda Mohapatra                    hudsec.or@nic.in            13
             Anand Mahindra institutionalinvestors@mahindra.com             8
                 Anish Shah institutionalinvestors@mahindra.com             6
              Rishad Premji        investor.relations@wipro.com            11
               Srini Pallia        investor.relations@wipro.com            11
               Lipsa Prusty         itpmu@orissaminerals.gov.in            14
            Shaktikanta Ray         itpmu@orissaminerals.gov.in            10
          Ashok Kumar Panda                    labsec.od@nic.in             9
      Manoranjan Samantaray                    labsec.od@nic.in            10
             Niranjana Jena                    labsec.od@nic.in            11
            Niti Ranjan Sen                    labsec.od@nic.in             7
      Rajesh Kumar Agarwala                    labsec.od@nic.in            12
             Soumitri Nayak                    labsec.od@nic.in            13
  Arun Kumar Sahoo, O.S.J.S                    lawsec.or@nic.in             9
  Pabitra Mohan Samal, OSJS                    lawsec.or@nic.in            10
Siba Prasad Mohapatra, OSJS                    lawsec.or@nic.in             9
           Gaurahari Behera                     orhealth@nic.in            15
      Kailash Chandra Nayak                     orhealth@nic.in            10
               Smita Biswal                     orhealth@nic.in             8
               Supriya Jena                     orhealth@nic.in            10
             Usharani Sahoo                     orhealth@nic.in            10
            Indramani Nayak                     prsec.od@nic.in            11
       Monica Priyadarshini                     prsec.od@nic.in             8
              Bhagala Sirka              secy-msme.od@od.gov.in            16
        Chandrapati Pradhan              secy-msme.od@od.gov.in            13
      Narayan Chandra Nayak              secy-msme.od@od.gov.in            12
             Rashmita Panda              secy-msme.od@od.gov.in             8
           Amit Kumar Nayak                sportsysec.od@nic.in            12
               Nelson Lakra                sportsysec.od@nic.in            13
             Sudhakar Nayak                sportsysec.od@nic.in            10
              Yeddula Vijay                sportsysec.od@nic.in            13
              Bhaskar Raito               ssepdodisha@gmail.com             9
               Sonia Behera               ssepdodisha@gmail.com            10

In [30]:
# DATASET 2 v7 — CHECK 11B
# Check whether receiver emails correspond to known Dataset 1 official emails

# Load frozen Dataset 1
df1 = pd.read_csv("unique_professional_identities_500_repaired (1).csv")

# Known official emails from Dataset 1
official_emails = set(
    df1["official_email"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
)

# Normalize Dataset 2 receiver emails
df2_receiver_emails = (
    df2["receiver_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Check how many receiver emails are present in Dataset 1
receiver_known = df2_receiver_emails.isin(official_emails)

print("Total Dataset 2 receiver records:", len(df2))
print("Receiver records using Dataset 1 official email:",
      receiver_known.sum())
print("Receiver records using other emails:",
      (~receiver_known).sum())

print("\nPercentage using Dataset 1 official email:",
      round(receiver_known.mean() * 100, 2), "%")

# Show the most frequent receiver emails NOT found in Dataset 1
unknown_receiver_counts = (
    df2.loc[~receiver_known, "receiver_email"]
    .value_counts()
    .head(30)
)

print("\nTop receiver emails NOT found in Dataset 1:")
print(unknown_receiver_counts)

FileNotFoundError: [Errno 2] No such file or directory: 'unique_professional_identities_500_repaired (1).csv'

In [31]:
import os

# Show CSV files in the current Jupyter folder
csv_files = [f for f in os.listdir(".") if f.lower().endswith(".csv")]

print("CSV files in current folder:")
for f in csv_files:
    print(f)

CSV files in current folder:
dataset2_500_final_v7.csv
dataset3_500_final_v4.csv
unique_professional_identities_500_repaired.csv

In [32]:
# DATASET 2 v7 — CHECK 11B
# Check receiver emails against Dataset 1 official emails

df1 = pd.read_csv("unique_professional_identities_500_repaired.csv")

# Dataset 1 official emails
official_emails = set(
    df1["official_email"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
)

# Normalize Dataset 2 receiver emails
receiver_emails = (
    df2["receiver_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Check whether receiver email exists in Dataset 1
receiver_known = receiver_emails.isin(official_emails)

print("Total Dataset 2 receiver records:", len(df2))
print("Receiver records using Dataset 1 official email:",
      receiver_known.sum())
print("Receiver records using other emails:",
      (~receiver_known).sum())

print(
    "\nPercentage using Dataset 1 official email:",
    round(receiver_known.mean() * 100, 2),
    "%"
)

print("\nTop receiver emails NOT found in Dataset 1:")
print(
    df2.loc[~receiver_known, "receiver_email"]
    .value_counts()
    .head(30)
)

Total Dataset 2 receiver records: 10000
Receiver records using Dataset 1 official email: 5200
Receiver records using other emails: 4800

Percentage using Dataset 1 official email: 52.0 %

Top receiver emails NOT found in Dataset 1:
receiver_email
arjun.bhattacharya@odisha.gov.in       5
geeta.gupta@odisha.gov.in              5
imran.menon@odisha.gov.in              3
shalini.chatterjee@odisha.gov.in       3
alok.gupta@odisha.gov.in               3
neha.gupta@odisha.gov.in               3
sarika.bansal@odisha.gov.in            3
deepak.saxena@odisha.gov.in            3
pooja.bansal@odisha.gov.in             3
arjun.saxena@odisha.gov.in             3
vikram.behera@odisha.gov.in            3
vikram.iyer@odisha.gov.in              3
rohit.khuntia@odisha.gov.in            3
tarun.agarwal@odisha.gov.in            3
pratyush.sahoo@odisha.gov.in           3
bijaya.swain@odisha.gov.in             3
tanvi.sethi@odisha.gov.in              3
nikhil.ghosh@odisha.gov.in             3
shalini.swain@odisha.gov.in            3
pratyush.bhattacharya@odisha.gov.in    3
usha.sharma@odisha.gov.in              3
tanvi.chauhan@odisha.gov.in            3
rahul.ahuja@odisha.gov.in              3
prakash.kurien@odisha.gov.in           3
sasmita.bhat@odisha.gov.in             3
bijaya.iyer@odisha.gov.in              3
geeta.jena@odisha.gov.in               3
snehasish.acharya@odisha.gov.in        3
neha.sharma@odisha.gov.in              3
swati.pradhan@odisha.gov.in            3
Name: count, dtype: int64

In [33]:
# DATASET 2 v7 — CHECK 11C
# Analyze receiver emails not present in Dataset 1 by label

unknown_receiver = df2.loc[~receiver_known].copy()

print("Unknown receiver records:", len(unknown_receiver))

print("\nBy label:")
print(
    unknown_receiver["label"]
    .value_counts()
)

print("\nPercentage by label:")
print(
    unknown_receiver["label"]
    .value_counts(normalize=True).mul(100).round(2)
)

print("\nUnknown receiver emails by label:")
print(
    pd.crosstab(
        unknown_receiver["receiver_email"],
        unknown_receiver["label"]
    )
    .sort_values(
        by=list(pd.crosstab(
            unknown_receiver["receiver_email"],
            unknown_receiver["label"]
        ).columns),
        ascending=False
    )
    .head(30)
)

Unknown receiver records: 4800

By label:
label
IMPERSONATION    2810
LEGITIMATE       1990
Name: count, dtype: int64

Percentage by label:
label
IMPERSONATION    58.54
LEGITIMATE       41.46
Name: proportion, dtype: float64

Unknown receiver emails by label:
label                                IMPERSONATION  LEGITIMATE
receiver_email
arjun.bhattacharya@odisha.gov.in                 4           1
geeta.gupta@odisha.gov.in                        3           2
bijaya.iyer@odisha.gov.in                        3           0
imran.menon@odisha.gov.in                        3           0
pooja.bansal@odisha.gov.in                       3           0
sarika.bansal@odisha.gov.in                      3           0
snehasish.acharya@odisha.gov.in                  3           0
suresh.ahuja@odisha.gov.in                       3           0
tarun.agarwal@odisha.gov.in                      3           0
usha.sharma@odisha.gov.in                        3           0
vikram.iyer@odisha.gov.in                        3           0
alok.gupta@odisha.gov.in                         2           1
arjun.saxena@odisha.gov.in                       2           1
geeta.jena@odisha.gov.in                         2           1
neha.sharma@odisha.gov.in                        2           1
prakash.kurien@odisha.gov.in                     2           1
pratyush.bhattacharya@odisha.gov.in              2           1
sasmita.bhat@odisha.gov.in                       2           1
shalini.chatterjee@odisha.gov.in                 2           1
tanvi.chauhan@odisha.gov.in                      2           1
tanvi.sethi@odisha.gov.in                        2           1
vikram.behera@odisha.gov.in                      2           1
alok.bhattacharya@odisha.gov.in                  2           0
ananya.malik@odisha.gov.in                       2           0
anita.routray@odisha.gov.in                      2           0
anjali.bhat@odisha.gov.in                        2           0
anjali.mohanty@odisha.gov.in                     2           0
ashirbad.acharya@odisha.gov.in                   2           0
ashirbad.panda@odisha.gov.in                     2           0
bhavna.ahuja@odisha.gov.in                       2           0

# DATASET 2 v7 — CHECK 11D
# Check receiver name/email consistency within each identity

receiver_pair_check = (
    df2.groupby(
        ["identity_id", "receiver_name", "receiver_email"],
        dropna=False
    )
    .size()
    .reset_index(name="record_count")
)

# Number of different receiver emails used by each identity
emails_per_identity = (
    receiver_pair_check
    .groupby("identity_id")["receiver_email"]
    .nunique()
)

# Number of different receiver names used by each identity
names_per_identity = (
    receiver_pair_check
    .groupby("identity_id")["receiver_name"]
    .nunique()
)

print("Identities with multiple receiver emails:",
      (emails_per_identity > 1).sum())

print("Identities with multiple receiver names:",
      (names_per_identity > 1).sum())

print("\nTop identities by number of receiver emails:")
print(
    emails_per_identity
    .sort_values(ascending=False)
    .head(20)
)

print("\nTop identities by number of receiver names:")
print(
    names_per_identity
    .sort_values(ascending=False)
    .head(20)
)

In [34]:
# DATASET 2 v7 — CHECK 11D
# Check receiver name/email consistency within each identity

receiver_pair_check = (
    df2.groupby(
        ["identity_id", "receiver_name", "receiver_email"],
        dropna=False
    )
    .size()
    .reset_index(name="record_count")
)

# Number of different receiver emails used by each identity
emails_per_identity = (
    receiver_pair_check
    .groupby("identity_id")["receiver_email"]
    .nunique()
)

# Number of different receiver names used by each identity
names_per_identity = (
    receiver_pair_check
    .groupby("identity_id")["receiver_name"]
    .nunique()
)

print("Identities with multiple receiver emails:",
      (emails_per_identity > 1).sum())

print("Identities with multiple receiver names:",
      (names_per_identity > 1).sum())

print("\nTop identities by number of receiver emails:")
print(
    emails_per_identity
    .sort_values(ascending=False)
    .head(20)
)

print("\nTop identities by number of receiver names:")
print(
    names_per_identity
    .sort_values(ascending=False)
    .head(20)
)

Identities with multiple receiver emails: 500
Identities with multiple receiver names: 500

Top identities by number of receiver emails:
identity_id
ID-0035    18
ID-0465    17
ID-0084    17
ID-0391    16
ID-0192    16
ID-0215    16
ID-0267    16
ID-0406    16
ID-0078    15
ID-0308    15
ID-0341    15
ID-0295    15
ID-0418    15
ID-0408    15
ID-0104    15
ID-0095    15
ID-0213    15
ID-0135    15
ID-0318    14
ID-0303    14
Name: receiver_email, dtype: int64

Top identities by number of receiver names:
identity_id
ID-0035    18
ID-0465    17
ID-0084    17
ID-0391    16
ID-0192    16
ID-0215    16
ID-0267    16
ID-0406    16
ID-0078    15
ID-0308    15
ID-0341    15
ID-0295    15
ID-0418    15
ID-0408    15
ID-0104    15
ID-0095    15
ID-0213    15
ID-0135    15
ID-0318    14
ID-0303    14
Name: receiver_name, dtype: int64

In [36]:
# DATASET 2 v7 — CHECK 11E
# Check receiver email -> receiver name consistency within each identity

email_name_check = (
    df2.groupby(
        ["identity_id", "receiver_email"],
        dropna=False
    )["receiver_name"]
    .nunique()
    .reset_index(name="name_count")
)

# Cases where the same receiver email has multiple names
inconsistent_receiver_emails = email_name_check[
    email_name_check["name_count"] > 1
]

print(
    "Identity + receiver_email combinations:",
    len(email_name_check)
)

print(
    "Same receiver email linked to multiple names within an identity:",
    len(inconsistent_receiver_emails)
)

if len(inconsistent_receiver_emails) > 0:
    print("\nExamples:")
    print(inconsistent_receiver_emails.head(30).to_string(index=False))
else:
    print("\nPASS — No receiver email is linked to multiple names within the same identity.")

Identity + receiver_email combinations: 5295
Same receiver email linked to multiple names within an identity: 0

PASS — No receiver email is linked to multiple names within the same identity.

In [42]:
# DATASET 2 v7 — CHECK 12
# Validate domain_match against sender_email and identity official domain

# Build Dataset 1 identity -> official domain mapping
identity_domain_map = (
    df1.set_index("identity_id")["official_domain"]
    .astype(str)
    .str.strip()
    .str.lower()
    .to_dict()
)

# Extract sender domain from sender_email
sender_domain = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Expected official domain for each identity
expected_domain = (
    df2["identity_id"]
    .map(identity_domain_map)
    .astype(str)
    .str.strip()
    .str.lower()
)

# Normalize domain_match
domain_match_normalized = (
    df2["domain_match"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Calculate whether sender domain exactly matches identity official domain
actual_domain_match = sender_domain == expected_domain

# Compare with stored domain_match
stored_match = domain_match_normalized.isin(
    ["true", "1", "yes", "match", "matched"]
)

# Basic distribution
print("Stored domain_match distribution:")
print(df2["domain_match"].value_counts(dropna=False))

print("\nActual sender-domain match:")
print(actual_domain_match.value_counts())

# Compare only records where domain_match is clearly boolean-like
boolean_like = domain_match_normalized.isin(
    ["true", "false", "1", "0", "yes", "no", "match", "mismatch"]
)

print("\nBoolean-like domain_match records:", boolean_like.sum())
print("Non-standard domain_match records:", (~boolean_like).sum())

# Mismatches between stored and calculated values
domain_errors = df2.loc[
    boolean_like & (stored_match != actual_domain_match),
    [
        "identity_id",
        "identity_name",
        "sender_email",
        "domain_match"
    ]
]

print("\nStored domain_match vs calculated mismatch:", len(domain_errors))

if len(domain_errors) > 0:
    print("\nExamples:")
    print(domain_errors.head(30).to_string(index=False))

Stored domain_match distribution:
domain_match
False    5533
True     4467
Name: count, dtype: int64

Actual sender-domain match:
False    5533
True     4467
Name: count, dtype: int64

Boolean-like domain_match records: 10000
Non-standard domain_match records: 0

Stored domain_match vs calculated mismatch: 0

In [41]:
# DATASET 2 v7 — FIX CHECK 12
# Correct domain_match using the actual sender domain
# and Dataset 1 official domain

# Extract sender domain
sender_domain = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Dataset 1 official domain for each identity
expected_domain = (
    df2["identity_id"]
    .map(identity_domain_map)
    .astype(str)
    .str.strip()
    .str.lower()
)

# Recalculate domain_match
df2["domain_match"] = sender_domain == expected_domain

print("domain_match corrected.")

print("\nNew domain_match distribution:")
print(df2["domain_match"].value_counts())

print("\nTrue:", (df2["domain_match"] == True).sum())
print("False:", (df2["domain_match"] == False).sum())

domain_match corrected.

New domain_match distribution:
domain_match
False    5533
True     4467
Name: count, dtype: int64

True: 4467
False: 5533

In [43]:
# DATASET 2 v7 — FIX CHECK 12
# Correct domain_match using the actual sender domain
# and Dataset 1 official domain

# Extract sender domain
sender_domain = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Dataset 1 official domain for each identity
expected_domain = (
    df2["identity_id"]
    .map(identity_domain_map)
    .astype(str)
    .str.strip()
    .str.lower()
)

# Recalculate domain_match
df2["domain_match"] = sender_domain == expected_domain

print("domain_match corrected.")

print("\nNew domain_match distribution:")
print(df2["domain_match"].value_counts())

print("\nTrue:", (df2["domain_match"] == True).sum())
print("False:", (df2["domain_match"] == False).sum())

domain_match corrected.

New domain_match distribution:
domain_match
False    5533
True     4467
Name: count, dtype: int64

True: 4467
False: 5533

In [44]:
# DATASET 2 v7 — CHECK 12
# Validate domain_match against sender_email and identity official domain

# Build Dataset 1 identity -> official domain mapping
identity_domain_map = (
    df1.set_index("identity_id")["official_domain"]
    .astype(str)
    .str.strip()
    .str.lower()
    .to_dict()
)

# Extract sender domain from sender_email
sender_domain = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Expected official domain for each identity
expected_domain = (
    df2["identity_id"]
    .map(identity_domain_map)
    .astype(str)
    .str.strip()
    .str.lower()
)

# Normalize domain_match
domain_match_normalized = (
    df2["domain_match"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Calculate whether sender domain exactly matches identity official domain
actual_domain_match = sender_domain == expected_domain

# Compare with stored domain_match
stored_match = domain_match_normalized.isin(
    ["true", "1", "yes", "match", "matched"]
)

# Basic distribution
print("Stored domain_match distribution:")
print(df2["domain_match"].value_counts(dropna=False))

print("\nActual sender-domain match:")
print(actual_domain_match.value_counts())

# Compare only records where domain_match is clearly boolean-like
boolean_like = domain_match_normalized.isin(
    ["true", "false", "1", "0", "yes", "no", "match", "mismatch"]
)

print("\nBoolean-like domain_match records:", boolean_like.sum())
print("Non-standard domain_match records:", (~boolean_like).sum())

# Mismatches between stored and calculated values
domain_errors = df2.loc[
    boolean_like & (stored_match != actual_domain_match),
    [
        "identity_id",
        "identity_name",
        "sender_email",
        "domain_match"
    ]
]

print("\nStored domain_match vs calculated mismatch:", len(domain_errors))

if len(domain_errors) > 0:
    print("\nExamples:")
    print(domain_errors.head(30).to_string(index=False))

Stored domain_match distribution:
domain_match
False    5533
True     4467
Name: count, dtype: int64

Actual sender-domain match:
False    5533
True     4467
Name: count, dtype: int64

Boolean-like domain_match records: 10000
Non-standard domain_match records: 0

Stored domain_match vs calculated mismatch: 0

In [45]:
# DATASET 2 v7 — CHECK 12 VERIFICATION

# Recalculate sender domain
sender_domain_check = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Expected Dataset 1 official domain
expected_domain_check = (
    df2["identity_id"]
    .map(identity_domain_map)
    .astype(str)
    .str.strip()
    .str.lower()
)

# Recalculate expected value
expected_domain_match = (
    sender_domain_check == expected_domain_check
)

# Compare with df2
verification_errors = (
    df2["domain_match"] != expected_domain_match
)

print("Domain_match verification errors:", verification_errors.sum())

if verification_errors.sum() == 0:
    print("PASS — domain_match is now fully consistent.")
else:
    print("\nRemaining errors:")
    print(
        df2.loc[
            verification_errors,
            ["identity_id", "sender_email", "domain_match"]
        ].head(20).to_string(index=False)
    )

Domain_match verification errors: 0
PASS — domain_match is now fully consistent.

In [46]:
# DATASET 2 v7 — CHECK 13
# Inspect reply_to coverage and distribution by label

print("Total records:", len(df2))

print("\nMissing reply_to:")
print(df2["reply_to"].isna().sum())

print("\nPresent reply_to:")
print(df2["reply_to"].notna().sum())

print("\nReply_to coverage by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["reply_to"].notna(),
        margins=True
    )
)

print("\nTop reply_to values:")
print(
    df2["reply_to"]
    .value_counts(dropna=True)
    .head(30)
)

Total records: 10000

Missing reply_to:
8110

Present reply_to:
1890

Reply_to coverage by label:
reply_to       False  True    All
label
IMPERSONATION   4011   989   5000
LEGITIMATE      4099   901   5000
All             8110  1890  10000

Top reply_to values:
reply_to
procurement.cell@odisha.gov.in          12
secretariat.cell@odisha.gov.in          10
establishment.cell@odisha.gov.in        10
administration.cell@odisha.gov.in       10
legal.section@odisha.gov.in             10
projects.office@odisha.gov.in            9
projects.section@odisha.gov.in           9
it.support@odisha.org                    9
human resources.office@odisha.gov.in     9
estate.desk@odisha.gov.in                9
estate.cell@odisha.gov.in                9
finance.section@odisha.gov.in            8
accounts.desk@odisha.gov.in              8
secretariat.office@odisha.gov.in         8
internal audit.cell@odisha.gov.in        8
internal audit.section@odisha.gov.in     8
accounts.office@odisha.gov.in            8
legal.desk@odisha.gov.in                 8
human resources.cell@odisha.gov.in       7
projects.desk@odisha.gov.in              7
procurement.section@odisha.gov.in        7
planning.desk@odisha.gov.in              6
planning.cell@odisha.gov.in              6
administration.office@odisha.gov.in      6
procurement.desk@odisha.gov.in           6
establishment.section@odisha.gov.in      6
administration.desk@odisha.gov.in        6
it services.cell@odisha.gov.in           6
stores.cell@odisha.gov.in                6
secretariat.desk@odisha.gov.in           6
Name: count, dtype: int64

In [49]:
# DATASET 2 v7 — CHECK 13A (CORRECTED)
# Compare Reply-To domain with sender domain

reply_df = df2[df2["reply_to"].notna()].copy()

# Extract sender domain
reply_df["sender_domain"] = (
    reply_df["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Extract Reply-To domain
reply_df["reply_domain"] = (
    reply_df["reply_to"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Compare domains
reply_df["same_domain"] = (
    reply_df["sender_domain"] == reply_df["reply_domain"]
)

print("Reply-To records:", len(reply_df))

print(
    "\nReply-To domain same as sender domain:",
    reply_df["same_domain"].sum()
)

print(
    "Reply-To domain different from sender domain:",
    (~reply_df["same_domain"]).sum()
)

print(
    "\nPercentage same:",
    round(reply_df["same_domain"].mean() * 100, 2),
    "%"
)

print("\nExamples where Reply-To domain differs:")
print(
    reply_df.loc[
        ~reply_df["same_domain"],
        ["identity_id", "label", "sender_email", "reply_to"]
    ]
    .head(30)
    .to_string(index=False)
)

Reply-To records: 1890

Reply-To domain same as sender domain: 490
Reply-To domain different from sender domain: 1400

Percentage same: 25.93 %

Examples where Reply-To domain differs:
identity_id         label                          sender_email                          reply_to
    ID-0001 IMPERSONATION               preeti.ahuja@odisha.com         mohan.majhi92@hotmail.com
    ID-0001 IMPERSONATION             mohan.majhi@odisha.gov.in      mohan.majhi47@protonmail.com
    ID-0002 IMPERSONATION bikash.rao@meridianfacility-india.net            records@oddisha.gov.in
    ID-0002 IMPERSONATION           kiran.patnaik@odlsha.gov.in       hemant.sharma23@outlook.com
    ID-0002 IMPERSONATION    internalaudit@odisha-office.gov.in                 docs.20@gmail.com
    ID-0002 IMPERSONATION              estate.office@odisha.net              accounts.32@yahoo.in
    ID-0003 IMPERSONATION             omkar.trivedi@outlook.com            accounts@odsiha.gov.in
    ID-0003 IMPERSONATION                sandeep.seth@yahoo.com             records@odlsha.gov.in
    ID-0004 IMPERSONATION          finance.office@oidsha.gov.in             accounts.13@yahoo.com
    ID-0004 IMPERSONATION      pruthwee.pani@odishaindia.gov.in       pruthwee.pani12@hotmail.com
    ID-0005 IMPERSONATION   parthasarathi.mallick@odlsha.gov.in parthasarathi.mallick71@gmail.com
    ID-0006    LEGITIMATE                      finsec.or@nic.in     projects.office@odisha.gov.in
    ID-0006    LEGITIMATE              pooja.pillai@outlook.com     finance.section@odisha.gov.in
    ID-0006    LEGITIMATE   debasish.kapoor@anvilfabrication.in          legal.desk@odisha.gov.in
    ID-0006 IMPERSONATION               secretariat@odisha.info             it.support@odisha.org
    ID-0007    LEGITIMATE                    prakash.sen@pwc.in       legal.section@odisha.gov.in
    ID-0007 IMPERSONATION          yamini.sarangi@odisha.gov.in        yamini.sarangi83@yahoo.com
    ID-0007 IMPERSONATION          yamini.sarangi@odlsha.gov.in       accounts@odishaindia.gov.in
    ID-0008 IMPERSONATION   rekha.malik@novatcehinstruments.net             payments@odisha.co.in
    ID-0008 IMPERSONATION         satyapriya.rath@odisha.gov.in     satyapriya.rath95@outlook.com
    ID-0008 IMPERSONATION         satyapriya.rath@odisha.gov.in       satyapriya.rath33@gmail.com
    ID-0009    LEGITIMATE                      finsec.or@nic.in    secretariat.cell@odisha.gov.in
    ID-0009 IMPERSONATION     krushna.satpathy32@protonmail.com      krushna.satpathy23@gmail.com
    ID-0009 IMPERSONATION        krushna.satpathy@odisha.gov.in    krushna.satpathy46@outlook.com
    ID-0009 IMPERSONATION        krushna.satpathy@odisha.gov.in      krushna.satpathy45@yahoo.com
    ID-0010    LEGITIMATE              saumyajit.rout@gmail.com  procurement.office@odisha.gov.in
    ID-0010    LEGITIMATE              saumyajit.rout@gmail.com  secretariat.office@odisha.gov.in
    ID-0010    LEGITIMATE              saumyajit.rout@gmail.com         estate.cell@odisha.gov.in
    ID-0010 IMPERSONATION jyoti.bhattacharya@powergrid-india.in             accounts.55@gmail.com
    ID-0011    LEGITIMATE                            cmo@nic.in    secretariat.cell@odisha.gov.in

In [50]:
# DATASET 2 v7 — CHECK 13B
# Inspect Reply-To domain differences in LEGITIMATE records only

legit_reply_diff = reply_df[
    (reply_df["label"] == "LEGITIMATE") &
    (~reply_df["same_domain"])
].copy()

print(
    "LEGITIMATE records with different Reply-To domain:",
    len(legit_reply_diff)
)

print("\nTop Reply-To domains:")
print(
    legit_reply_diff["reply_domain"]
    .value_counts()
    .head(30)
)

print("\nExamples:")
print(
    legit_reply_diff[
        [
            "identity_id",
            "identity_name",
            "sender_email",
            "reply_to",
            "sender_domain",
            "reply_domain"
        ]
    ]
    .head(50)
    .to_string(index=False)
)

LEGITIMATE records with different Reply-To domain: 427

Top Reply-To domains:
reply_domain
odisha.gov.in               230
iitbbs.ac.in                 23
cooperation.gov.in            8
pnbindia.in                   6
iitb.ac.in                    6
hcltech.com                   5
od.gov.in                     3
aws.amazon.com                3
google.com                    3
microsoft.com                 3
cognizant.com                 3
centralbankofindia.co.in      3
ongcindia.com                 3
iitg.ac.in                    3
pg.com                        3
nitk.ac.in                    3
flipkart.com                  2
ltimindtree.com               2
mphasis.com                   2
wipro.com                     2
coca-cola.com                 2
marutisuzuki.com              2
airtel.in                     2
visa.com                      2
tatasteel.com                 2
larsentoubro.com              2
cci.gov.in                    2
bosch.in                      2
tcs.com                       2
rbi.org.in                    2
Name: count, dtype: int64

Examples:
identity_id            identity_name                         sender_email                            reply_to           sender_domain  reply_domain
    ID-0006     Sanjeeb Kumar Mishra                     finsec.or@nic.in       projects.office@odisha.gov.in                  nic.in odisha.gov.in
    ID-0006     Sanjeeb Kumar Mishra             pooja.pillai@outlook.com       finance.section@odisha.gov.in             outlook.com odisha.gov.in
    ID-0006     Sanjeeb Kumar Mishra  debasish.kapoor@anvilfabrication.in            legal.desk@odisha.gov.in     anvilfabrication.in odisha.gov.in
    ID-0007           Yamini Sarangi                   prakash.sen@pwc.in         legal.section@odisha.gov.in                  pwc.in odisha.gov.in
    ID-0009 Krushna Chandra Satpathy                     finsec.or@nic.in      secretariat.cell@odisha.gov.in                  nic.in odisha.gov.in
    ID-0010           Saumyajit Rout             saumyajit.rout@gmail.com    procurement.office@odisha.gov.in               gmail.com odisha.gov.in
    ID-0010           Saumyajit Rout             saumyajit.rout@gmail.com    secretariat.office@odisha.gov.in               gmail.com odisha.gov.in
    ID-0010           Saumyajit Rout             saumyajit.rout@gmail.com           estate.cell@odisha.gov.in               gmail.com odisha.gov.in
    ID-0011           Saswata Mishra                           cmo@nic.in      secretariat.cell@odisha.gov.in                  nic.in odisha.gov.in
    ID-0013              Anupam Saha                           cmo@nic.in   it services.section@odisha.gov.in                  nic.in odisha.gov.in
    ID-0013              Anupam Saha                           cmo@nic.in           stores.cell@odisha.gov.in                  nic.in odisha.gov.in
    ID-0015             Mirdha Toppo             manish.nayak@infosys.com   administration.desk@odisha.gov.in             infosys.com odisha.gov.in
    ID-0018        Trilochan Mohanty                           cmo@nic.in            legal.desk@odisha.gov.in                  nic.in odisha.gov.in
    ID-0019       Pradip Kumar Samal     sandeep.singh@aaravstationers.in         legal.section@odisha.gov.in      aaravstationers.in odisha.gov.in
    ID-0020            Hemant Sharma                 homesec.od@od.gov.in         projects.desk@odisha.gov.in               od.gov.in odisha.gov.in
    ID-0020            Hemant Sharma              deepak.gupta@iitd.ac.in      procurement.cell@odisha.gov.in              iitd.ac.in odisha.gov.in
    ID-0022         Samarendra Nayak  deepak.ghosh@gangaconstructions.net          legal.office@odisha.gov.in  gangaconstructions.net odisha.gov.in
    ID-0022         Samarendra Nayak              ashirbad.malik@kpmg.com         legal.section@odisha.gov.in                kpmg.com odisha.gov.in
    ID-0025        Siba Prasad Panda  sanjay.pati@capstonelogistics.co.in         projects.desk@odisha.gov.in capstonelogistics.co.in odisha.gov.in
    ID-0026        Tarun Kumar Panda   geeta.tripathy@skylinenetworks.com    secretariat.office@odisha.gov.in     skylinenetworks.com odisha.gov.in
    ID-0028          Ratikanta Panda                  priya.gupta@tcs.com         estate.office@odisha.gov.in                 tcs.com odisha.gov.in
    ID-0029         Suryanarayan Kar   nandini.malik@sunriseinfratech.com      accounts.section@odisha.gov.in    sunriseinfratech.com odisha.gov.in
    ID-0031          Aatish Anshuman         usha.roy@aaravstationers.net          accounts.cell@iitbbs.ac.in     aaravstationers.net  iitbbs.ac.in
    ID-0032             Abhinav Arya anjali.menon@novatechinstruments.net       vigilance.office@iitbbs.ac.in novatechinstruments.net  iitbbs.ac.in
    ID-0032             Abhinav Arya                alok.bhat@hotmail.com          stores.office@iitbbs.ac.in             hotmail.com  iitbbs.ac.in
    ID-0034       Akshaya Kumar Rath     anjali.chopra@sagartransport.net       accounts.section@iitbbs.ac.in      sagartransport.net  iitbbs.ac.in
    ID-0036      Abhijit Datta Banik           omkar.verma@bluepeak.co.in        planning.office@iitbbs.ac.in          bluepeak.co.in  iitbbs.ac.in
    ID-0036      Abhijit Datta Banik                  rajesh.reddy@pwc.in administration.section@iitbbs.ac.in                  pwc.in  iitbbs.ac.in
    ID-0039            Akash Jaiswal             pooja.singh@axisbank.com     it services.office@iitbbs.ac.in            axisbank.com  iitbbs.ac.in
    ID-0040     Akhilesh Kumar Singh             zoya.mohanty@bluepeak.in       procurement.cell@iitbbs.ac.in             bluepeak.in  iitbbs.ac.in
    ID-0041                 Akshay K        yashwant.singh@rediffmail.com administration.section@iitbbs.ac.in          rediffmail.com  iitbbs.ac.in
    ID-0041                 Akshay K          meera.parida@nimbusit.co.in  administration.office@iitbbs.ac.in          nimbusit.co.in  iitbbs.ac.in
    ID-0043            Amrit B. Sahu           subrata.nayak@axisbank.com         stores.section@iitbbs.ac.in            axisbank.com  iitbbs.ac.in
    ID-0044         Amrita Satapathy          pratyush.parida@infosys.com     it services.office@iitbbs.ac.in             infosys.com  iitbbs.ac.in
    ID-0044         Amrita Satapathy                    zoya.bose@cdac.in          accounts.desk@iitbbs.ac.in                 cdac.in  iitbbs.ac.in
    ID-0044         Amrita Satapathy         harish.parida@nimbusit.co.in         vigilance.cell@iitbbs.ac.in          nimbusit.co.in  iitbbs.ac.in
    ID-0047           Animesh Mandal    rakesh.patnaik@aaravstationers.in       secretariat.desk@iitbbs.ac.in      aaravstationers.in  iitbbs.ac.in
    ID-0050  Ankit Ravindra Deshmukh      geeta.thomas@zenithsecurity.net       it services.cell@iitbbs.ac.in      zenithsecurity.net  iitbbs.ac.in
    ID-0054       Shireesh B. Kedare          snehasish.dash@axisbank.com   human resources.office@iitb.ac.in            axisbank.com    iitb.ac.in
    ID-0054       Shireesh B. Kedare               deepak.sethi@yahoo.com      administration.desk@iitb.ac.in               yahoo.com    iitb.ac.in
    ID-0055         Ravindra D. Gudi           kavita.trivedi@sebi.gov.in      procurement.section@iitb.ac.in             sebi.gov.in    iitb.ac.in
    ID-0055         Ravindra D. Gudi   amit.bansal@utkalelectricals.co.in       procurement.office@iitb.ac.in  utkalelectricals.co.in    iitb.ac.in
    ID-0056                Murty B S mohit.parida@tridenthousekeeping.com          projects.office@iith.ac.in tridenthousekeeping.com    iith.ac.in
    ID-0057            V Venkata Rao                kiran.bansal@icai.org   human resources.office@iith.ac.in                icai.org    iith.ac.in
    ID-0058              V. Kamakoti             sandeep.bhat@outlook.com    internal audit.office@iitm.ac.in             outlook.com    iitm.ac.in
    ID-0059       Kamal Kishore Pant             preeti.varghese@yahoo.in           vigilance.desk@iitr.ac.in                yahoo.in    iitr.ac.in
    ID-0061            Ashok Chandra                       mdps@pnb.co.in           estate.office@pnbindia.in               pnb.co.in   pnbindia.in
    ID-0061            Ashok Chandra     sunita.trivedi@zenithsecurity.in        secretariat.desk@pnbindia.in       zenithsecurity.in   pnbindia.in
    ID-0062             Kalyan Kumar               rajesh.seth@nabard.org          estate.section@pnbindia.in              nabard.org   pnbindia.in
    ID-0063           M. Paramasivam                       hosd@pnb.co.in        projects.section@pnbindia.in               pnb.co.in   pnbindia.in

In [51]:
# DATASET 2 v7 — CHECK 14
# Inspect reply_to_match distribution

print("reply_to_match distribution:")
print(
    df2["reply_to_match"].value_counts(dropna=False)
)

print("\nBy label:")
print(
    pd.crosstab(
        df2["label"],
        df2["reply_to_match"],
        margins=True
    )
)

reply_to_match distribution:
reply_to_match
True     8600
False    1400
Name: count, dtype: int64

By label:
reply_to_match  False  True    All
label
IMPERSONATION     973  4027   5000
LEGITIMATE        427  4573   5000
All              1400  8600  10000

In [52]:
# DATASET 2 v7 — CHECK 14A
# Verify reply_to_match against sender_email and reply_to

reply_check = df2[df2["reply_to"].notna()].copy()

# Extract sender email and reply-to domains
reply_check["sender_domain"] = (
    reply_check["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

reply_check["reply_domain"] = (
    reply_check["reply_to"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Expected match:
# True when Reply-To uses the same domain as sender
expected_reply_match = (
    reply_check["sender_domain"] == reply_check["reply_domain"]
)

# Normalize stored value
stored_reply_match = (
    reply_check["reply_to_match"]
    .astype(str)
    .str.strip()
    .str.lower()
    .isin(["true", "1", "yes"])
)

# Compare
errors = stored_reply_match != expected_reply_match

print("Reply-To records checked:", len(reply_check))
print("reply_to_match inconsistencies:", errors.sum())

if errors.sum() == 0:
    print("\nPASS — reply_to_match is consistent with sender/reply-to domains.")
else:
    print("\nExamples of inconsistencies:")
    print(
        reply_check.loc[
            errors,
            [
                "identity_id",
                "label",
                "sender_email",
                "reply_to",
                "reply_to_match",
                "sender_domain",
                "reply_domain"
            ]
        ]
        .head(30)
        .to_string(index=False)
    )

Reply-To records checked: 1890
reply_to_match inconsistencies: 0

PASS — reply_to_match is consistent with sender/reply-to domains.

In [53]:
# DATASET 2 v7 — CHECK 15
# Validate attack_type against label

print("Attack types by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["attack_type"],
        margins=True
    )
)

print("\nUnique attack types:")
print(
    sorted(df2["attack_type"].dropna().unique())
)

print("\nMissing attack_type:")
print(
    df2["attack_type"].isna().sum()
)

Attack types by label:
attack_type    ACCOUNT_CHANGE  AUTHORITY_ABUSE  CHANNEL_CHANGE  \
label
IMPERSONATION             470              481             474
LEGITIMATE                  0                0               0
All                       470              481             474

attack_type    CREDENTIAL_REQUEST  DOCUMENT_REQUEST  FINANCIAL_REQUEST  NONE  \
label
IMPERSONATION                 511               469                520     0
LEGITIMATE                      0                 0                  0  5000
All                           511               469                520  5000

attack_type    SENSITIVE_DATA_REQUEST  SOCIAL_ENGINEERING  URGENT_REQUEST  \
label
IMPERSONATION                     535                 486             492
LEGITIMATE                          0                   0               0
All                               535                 486             492

attack_type    VENDOR_PAYMENT    All
label
IMPERSONATION             562   5000
LEGITIMATE                  0   5000
All                       562  10000

Unique attack types:
['ACCOUNT_CHANGE', 'AUTHORITY_ABUSE', 'CHANNEL_CHANGE', 'CREDENTIAL_REQUEST', 'DOCUMENT_REQUEST', 'FINANCIAL_REQUEST', 'NONE', 'SENSITIVE_DATA_REQUEST', 'SOCIAL_ENGINEERING', 'URGENT_REQUEST', 'VENDOR_PAYMENT']

Missing attack_type:
0

In [54]:
# DATASET 2 v7 — CHECK 16
# Validate impersonation_mechanism against label

print("Impersonation mechanisms by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["impersonation_mechanism"],
        margins=True
    )
)

print("\nUnique impersonation mechanisms:")
print(
    sorted(
        df2["impersonation_mechanism"]
        .dropna()
        .astype(str)
        .unique()
    )
)

print("\nMissing impersonation_mechanism:")
print(
    df2["impersonation_mechanism"].isna().sum()
)

Impersonation mechanisms by label:
impersonation_mechanism  AUTHORITY_IMPERSONATION  COMPROMISED_ACCOUNT  \
label
IMPERSONATION                                252                  911
LEGITIMATE                                     0                    0
All                                          252                  911

impersonation_mechanism  COMPROMISED_COLLEAGUE  DISPLAY_NAME_SPOOF  \
label
IMPERSONATION                              975                 367
LEGITIMATE                                   0                   0
All                                        975                 367

impersonation_mechanism  EXECUTIVE_ASSISTANT_PROXY  FAKE_ASSISTANT  \
label
IMPERSONATION                                  306             226
LEGITIMATE                                       0               0
All                                            306             226

impersonation_mechanism  FAKE_DEPARTMENT  FAKE_HELPDESK  LOOKALIKE_DOMAIN  \
label
IMPERSONATION                        305             66               442
LEGITIMATE                             0              0                 0
All                                  305             66               442

impersonation_mechanism  NONE  PARTNER_SPOOF  REPLY_TO_DIVERT  \
label
IMPERSONATION               0            198              287
LEGITIMATE               5000              0                0
All                      5000            198              287

impersonation_mechanism  SUBDOMAIN_DECEPTION  TYPO_DOMAIN  VENDOR_SPOOF    All
label
IMPERSONATION                            237          260           168   5000
LEGITIMATE                                 0            0             0   5000
All                                      237          260           168  10000

Unique impersonation mechanisms:
['AUTHORITY_IMPERSONATION', 'COMPROMISED_ACCOUNT', 'COMPROMISED_COLLEAGUE', 'DISPLAY_NAME_SPOOF', 'EXECUTIVE_ASSISTANT_PROXY', 'FAKE_ASSISTANT', 'FAKE_DEPARTMENT', 'FAKE_HELPDESK', 'LOOKALIKE_DOMAIN', 'NONE', 'PARTNER_SPOOF', 'REPLY_TO_DIVERT', 'SUBDOMAIN_DECEPTION', 'TYPO_DOMAIN', 'VENDOR_SPOOF']

Missing impersonation_mechanism:
0

In [55]:
# DATASET 2 v7 — CHECK 17
# Validate sender_relationship

print("Sender relationships by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["sender_relationship"],
        margins=True
    )
)

print("\nUnique sender relationships:")
print(
    sorted(
        df2["sender_relationship"]
        .dropna()
        .astype(str)
        .unique()
    )
)

print("\nMissing sender_relationship:")
print(
    df2["sender_relationship"].isna().sum()
)

Sender relationships by label:
sender_relationship  EXTERNAL_CONSULTANT_PERSONAL  EXTERNAL_PARTNER  \
label
IMPERSONATION                                   0                 0
LEGITIMATE                                    323               571
All                                           323               571

sender_relationship  EXTERNAL_VENDOR  IMPERSONATES_IDENTITY  \
label
IMPERSONATION                      0                   2810
LEGITIMATE                       720                      0
All                              720                   2810

sender_relationship  IMPERSONATES_THIRD_PARTY  INTERNAL_COLLEAGUE  \
label
IMPERSONATION                            2190                   0
LEGITIMATE                                  0                1053
All                                      2190                1053

sender_relationship  INTERNAL_SHARED_MAILBOX  SELF_OUTBOUND    All
label
IMPERSONATION                              0              0   5000
LEGITIMATE                               343           1990   5000
All                                      343           1990  10000

Unique sender relationships:
['EXTERNAL_CONSULTANT_PERSONAL', 'EXTERNAL_PARTNER', 'EXTERNAL_VENDOR', 'IMPERSONATES_IDENTITY', 'IMPERSONATES_THIRD_PARTY', 'INTERNAL_COLLEAGUE', 'INTERNAL_SHARED_MAILBOX', 'SELF_OUTBOUND']

Missing sender_relationship:
0

In [56]:
# DATASET 2 v7 — CHECK 18
# Validate scenario_family

print("Scenario families by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["scenario_family"],
        margins=True
    )
)

print("\nUnique scenario families:")
print(
    sorted(
        df2["scenario_family"]
        .dropna()
        .astype(str)
        .unique()
    )
)

print("\nMissing scenario_family:")
print(
    df2["scenario_family"].isna().sum()
)

Scenario families by label:
scenario_family  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access  \
label
IMPERSONATION                                        146
LEGITIMATE                                             0
All                                                  146

scenario_family  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank  \
label
IMPERSONATION                                      131
LEGITIMATE                                           0
All                                                131

scenario_family  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact  \
label
IMPERSONATION                                          59
LEGITIMATE                                              0
All                                                    59

scenario_family  IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access  \
label
IMPERSONATION                                       134
LEGITIMATE                                            0
All                                                 134

scenario_family  IMP/AUTHORITY_ABUSE/APPROVE:approval  \
label
IMPERSONATION                                     164
LEGITIMATE                                          0
All                                               164

scenario_family  IMP/AUTHORITY_ABUSE/MOVE_MONEY:payment  \
label
IMPERSONATION                                       138
LEGITIMATE                                            0
All                                                 138

scenario_family  IMP/AUTHORITY_ABUSE/SEND_ITEM:doc  \
label
IMPERSONATION                                  179
LEGITIMATE                                       0
All                                            179

scenario_family  IMP/CHANNEL_CHANGE/SWITCH:channel  \
label
IMPERSONATION                                  474
LEGITIMATE                                       0
All                                            474

scenario_family  IMP/CREDENTIAL_REQUEST/CONFIRM:verify  \
label
IMPERSONATION                                      264
LEGITIMATE                                           0
All                                                264

scenario_family  IMP/CREDENTIAL_REQUEST/DISCLOSE:credential  ...  \
label                                                        ...
IMPERSONATION                                           247  ...
LEGITIMATE                                                0  ...
All                                                     247  ...

scenario_family  LEGIT/deadline/SEND_ITEM:doc  LEGIT/document/SEND_ITEM:doc  \
label
IMPERSONATION                               0                             0
LEGITIMATE                                153                           500
All                                       153                           500

scenario_family  LEGIT/favour/CONFIRM:verify  LEGIT/favour/DISCLOSE:data  \
label
IMPERSONATION                              0                           0
LEGITIMATE                               180                         161
All                                      180                         161

scenario_family  LEGIT/favour/SEND_ITEM:doc  LEGIT/meeting/CONFIRM:verify  \
label
IMPERSONATION                             0                             0
LEGITIMATE                              159                           238
All                                     159                           238

scenario_family  LEGIT/meeting/SEND_ITEM:doc  LEGIT/payment/CONFIRM:verify  \
label
IMPERSONATION                              0                             0
LEGITIMATE                               262                           246
All                                      262                           246

scenario_family  LEGIT/payment/MOVE_MONEY:payment    All
label
IMPERSONATION                                   0   5000
LEGITIMATE                                    254   5000
All                                           254  10000

[3 rows x 44 columns]

Unique scenario families:
['IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access', 'IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank', 'IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact', 'IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access', 'IMP/AUTHORITY_ABUSE/APPROVE:approval', 'IMP/AUTHORITY_ABUSE/MOVE_MONEY:payment', 'IMP/AUTHORITY_ABUSE/SEND_ITEM:doc', 'IMP/CHANNEL_CHANGE/SWITCH:channel', 'IMP/CREDENTIAL_REQUEST/CONFIRM:verify', 'IMP/CREDENTIAL_REQUEST/DISCLOSE:credential', 'IMP/DOCUMENT_REQUEST/SEND_ITEM:doc', 'IMP/FINANCIAL_REQUEST/APPROVE:approval', 'IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment', 'IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data', 'IMP/SOCIAL_ENGINEERING/CONFIRM:verify', 'IMP/SOCIAL_ENGINEERING/DISCLOSE:data', 'IMP/SOCIAL_ENGINEERING/SEND_ITEM:doc', 'IMP/URGENT_REQUEST/APPROVE:approval', 'IMP/URGENT_REQUEST/MOVE_MONEY:payment', 'IMP/URGENT_REQUEST/SEND_ITEM:doc', 'IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank', 'IMP/VENDOR_PAYMENT/MOVE_MONEY:payment', 'LEGIT/access/CHANGE_RECORD:contact', 'LEGIT/access/CONFIRM:verify', 'LEGIT/access/GRANT_ACCESS:access', 'LEGIT/approval/APPROVE:approval', 'LEGIT/approval/SEND_ITEM:doc', 'LEGIT/bank/CHANGE_RECORD:bank', 'LEGIT/bank/CONFIRM:verify', 'LEGIT/channel/CHANGE_RECORD:contact', 'LEGIT/channel/SWITCH:channel', 'LEGIT/data/DISCLOSE:data', 'LEGIT/deadline/APPROVE:approval', 'LEGIT/deadline/MOVE_MONEY:payment', 'LEGIT/deadline/SEND_ITEM:doc', 'LEGIT/document/SEND_ITEM:doc', 'LEGIT/favour/CONFIRM:verify', 'LEGIT/favour/DISCLOSE:data', 'LEGIT/favour/SEND_ITEM:doc', 'LEGIT/meeting/CONFIRM:verify', 'LEGIT/meeting/SEND_ITEM:doc', 'LEGIT/payment/CONFIRM:verify', 'LEGIT/payment/MOVE_MONEY:payment']

Missing scenario_family:
0

In [57]:
# DATASET 2 v7 — CHECK 19
# Validate request_category

print("Request categories by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["request_category"],
        margins=True
    )
)

print("\nUnique request categories:")
print(
    sorted(
        df2["request_category"]
        .dropna()
        .astype(str)
        .unique()
    )
)

print("\nMissing request_category:")
print(
    df2["request_category"].isna().sum()
)

Request categories by label:
request_category  access  approval  bank  channel  data  deadline  document  \
label
IMPERSONATION        487       403   497      314   495       566       666
LEGITIMATE           500       500   500      500   500       500       500
All                  987       903   997      814   995      1066      1166

request_category  favour  meeting  payment    All
label
IMPERSONATION        233      686      653   5000
LEGITIMATE           500      500      500   5000
All                  733     1186     1153  10000

Unique request categories:
['access', 'approval', 'bank', 'channel', 'data', 'deadline', 'document', 'favour', 'meeting', 'payment']

Missing request_category:
0

In [58]:
# DATASET 2 v7 — CHECK 20
# Check scenario_family vs request_category consistency

# Extract the category component from scenario_family
df2["scenario_category_extracted"] = (
    df2["scenario_family"]
    .astype(str)
    .str.split("/")
    .str[1]
    .str.lower()
)

# Map scenario-family categories to request categories
category_map = {
    "access": "access",
    "approval": "approval",
    "bank": "bank",
    "channel": "channel",
    "data": "data",
    "deadline": "deadline",
    "document": "document",
    "favour": "favour",
    "meeting": "meeting",
    "payment": "payment",
    "account_change": "bank",
    "authority_abuse": "approval",
    "credential_request": "data",
    "document_request": "document",
    "financial_request": "payment",
    "sensitive_data_request": "data",
    "social_engineering": "favour",
    "urgent_request": "deadline",
    "vendor_payment": "payment"
}

df2["expected_request_category"] = (
    df2["scenario_category_extracted"]
    .map(category_map)
)

# Compare
category_errors = (
    df2["request_category"].astype(str).str.lower()
    != df2["expected_request_category"]
)

print("Total records:", len(df2))
print("Scenario/request category mismatches:", category_errors.sum())

if category_errors.sum() > 0:
    print("\nExamples:")
    print(
        df2.loc[
            category_errors,
            [
                "identity_id",
                "label",
                "scenario_family",
                "request_category",
                "scenario_category_extracted",
                "expected_request_category"
            ]
        ]
        .head(30)
        .to_string(index=False)
    )
else:
    print("\nPASS — scenario_family and request_category are consistent.")

Total records: 10000
Scenario/request category mismatches: 2736

Examples:
identity_id         label                            scenario_family request_category scenario_category_extracted expected_request_category
    ID-0001 IMPERSONATION   IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         deadline           financial_request                   payment
    ID-0001 IMPERSONATION       IMP/AUTHORITY_ABUSE/APPROVE:approval         deadline             authority_abuse                  approval
    ID-0001 IMPERSONATION      IMP/CREDENTIAL_REQUEST/CONFIRM:verify         document          credential_request                      data
    ID-0001 IMPERSONATION      IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank             bank              vendor_payment                   payment
    ID-0001 IMPERSONATION          IMP/CHANNEL_CHANGE/SWITCH:channel          meeting              channel_change                       NaN
    ID-0001 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential         document          credential_request                      data
    ID-0001 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access          credential_request                      data
    ID-0002 IMPERSONATION       IMP/AUTHORITY_ABUSE/APPROVE:approval         deadline             authority_abuse                  approval
    ID-0002 IMPERSONATION          IMP/CHANNEL_CHANGE/SWITCH:channel          channel              channel_change                       NaN
    ID-0002 IMPERSONATION      IMP/VENDOR_PAYMENT/MOVE_MONEY:payment             bank              vendor_payment                   payment
    ID-0002 IMPERSONATION   IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         approval           financial_request                   payment
    ID-0002 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access          credential_request                      data
    ID-0002 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access          credential_request                      data
    ID-0002 IMPERSONATION         IMP/DOCUMENT_REQUEST/SEND_ITEM:doc          meeting            document_request                  document
    ID-0002 IMPERSONATION      IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank           access              account_change                      bank
    ID-0003 IMPERSONATION        IMP/URGENT_REQUEST/APPROVE:approval          meeting              urgent_request                  deadline
    ID-0003 IMPERSONATION           IMP/URGENT_REQUEST/SEND_ITEM:doc          meeting              urgent_request                  deadline
    ID-0003 IMPERSONATION      IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access          credential_request                      data
    ID-0003 IMPERSONATION          IMP/CHANNEL_CHANGE/SWITCH:channel          channel              channel_change                       NaN
    ID-0003 IMPERSONATION      IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access          credential_request                      data
    ID-0003 IMPERSONATION          IMP/AUTHORITY_ABUSE/SEND_ITEM:doc          meeting             authority_abuse                  approval
    ID-0003 IMPERSONATION      IMP/VENDOR_PAYMENT/MOVE_MONEY:payment             bank              vendor_payment                   payment
    ID-0003 IMPERSONATION      IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank             bank              vendor_payment                   payment
    ID-0004 IMPERSONATION      IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access          credential_request                      data
    ID-0004 IMPERSONATION          IMP/CHANNEL_CHANGE/SWITCH:channel          channel              channel_change                       NaN
    ID-0005 IMPERSONATION   IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact           access              account_change                      bank
    ID-0005 IMPERSONATION     IMP/FINANCIAL_REQUEST/APPROVE:approval         deadline           financial_request                   payment
    ID-0005 IMPERSONATION   IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data         document      sensitive_data_request                      data
    ID-0005 IMPERSONATION       IMP/SOCIAL_ENGINEERING/SEND_ITEM:doc             data          social_engineering                    favour
    ID-0005 IMPERSONATION   IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data         document      sensitive_data_request                      data

In [ ]:
# DATASET 2 v7 — CHECK 13
# Inspect reply_to coverage and distribution by label

print("Total records:", len(df2))

print("\nMissing reply_to:")
print(df2["reply_to"].isna().sum())

print("\nPresent reply_to:")
print(df2["reply_to"].notna().sum())

print("\nReply_to coverage by label:")
print(
    pd.crosstab(
        df2["label"],
        df2["reply_to"].notna(),
        margins=True
    )
)

print("\nTop reply_to values:")
print(
    df2["reply_to"]
    .value_counts(dropna=True)
    .head(30)
)

Total records: 10000

Missing reply_to:
8110

Present reply_to:
1890

Reply_to coverage by label:
reply_to       False  True    All
label
IMPERSONATION   4011   989   5000
LEGITIMATE      4099   901   5000
All             8110  1890  10000

Top reply_to values:
reply_to
procurement.cell@odisha.gov.in          12
secretariat.cell@odisha.gov.in          10
establishment.cell@odisha.gov.in        10
administration.cell@odisha.gov.in       10
legal.section@odisha.gov.in             10
projects.office@odisha.gov.in            9
projects.section@odisha.gov.in           9
it.support@odisha.org                    9
human resources.office@odisha.gov.in     9
estate.desk@odisha.gov.in                9
estate.cell@odisha.gov.in                9
finance.section@odisha.gov.in            8
accounts.desk@odisha.gov.in              8
secretariat.office@odisha.gov.in         8
internal audit.cell@odisha.gov.in        8
internal audit.section@odisha.gov.in     8
accounts.office@odisha.gov.in            8
legal.desk@odisha.gov.in                 8
human resources.cell@odisha.gov.in       7
projects.desk@odisha.gov.in              7
procurement.section@odisha.gov.in        7
planning.desk@odisha.gov.in              6
planning.cell@odisha.gov.in              6
administration.office@odisha.gov.in      6
procurement.desk@odisha.gov.in           6
establishment.section@odisha.gov.in      6
administration.desk@odisha.gov.in        6
it services.cell@odisha.gov.in           6
stores.cell@odisha.gov.in                6
secretariat.desk@odisha.gov.in           6
Name: count, dtype: int64

# DATASET 2 v7 — CHECK 20
# Check scenario_family vs request_category consistency

df2["scenario_category_extracted"] = (
    df2["scenario_family"]
    .astype(str)
    .str.split("/")
    .str[1]
    .str.lower()
)

category_map = {
    "access": "access",
    "approval": "approval",
    "bank": "bank",
    "channel": "channel",
    "data": "data",
    "deadline": "deadline",
    "document": "document",
    "favour": "favour",
    "meeting": "meeting",
    "payment": "payment",
    "account_change": "bank",
    "authority_abuse": "approval",
    "credential_request": "data",
    "document_request": "document",
    "financial_request": "payment",
    "sensitive_data_request": "data",
    "social_engineering": "favour",
    "urgent_request": "deadline",
    "vendor_payment": "payment"
}

df2["expected_request_category"] = (
    df2["scenario_category_extracted"]
    .map(category_map)
)

category_errors = (
    df2["request_category"].astype(str).str.lower()
    != df2["expected_request_category"]
)

print("Total records:", len(df2))
print("Scenario/request category mismatches:", category_errors.sum())

if category_errors.sum() > 0:
    print("\nExamples:")
    print(
        df2.loc[
            category_errors,
            [
                "identity_id",
                "label",
                "scenario_family",
                "request_category",
                "scenario_category_extracted",
                "expected_request_category"
            ]
        ]
        .head(30)
        .to_string(index=False)
    )
else:
    print("\nPASS — scenario_family and request_category are consistent.")

# DATASET 2 v7 — CHECK 20
# Check scenario_family vs request_category consistency

df2["scenario_category_extracted"] = (
    df2["scenario_family"]
    .astype(str)
    .str.split("/")
    .str[1]
    .str.lower()
)

category_map = {
    "access": "access",
    "approval": "approval",
    "bank": "bank",
    "channel": "channel",
    "data": "data",
    "deadline": "deadline",
    "document": "document",
    "favour": "favour",
    "meeting": "meeting",
    "payment": "payment",
    "account_change": "bank",
    "authority_abuse": "approval",
    "credential_request": "data",
    "document_request": "document",
    "financial_request": "payment",
    "sensitive_data_request": "data",
    "social_engineering": "favour",
    "urgent_request": "deadline",
    "vendor_payment": "payment"
}

df2["expected_request_category"] = (
    df2["scenario_category_extracted"]
    .map(category_map)
)

category_errors = (
    df2["request_category"].astype(str).str.lower()
    != df2["expected_request_category"]
)

print("Total records:", len(df2))
print("Scenario/request category mismatches:", category_errors.sum())

if category_errors.sum() > 0:
    print("\nExamples:")
    print(
        df2.loc[
            category_errors,
            [
                "identity_id",
                "label",
                "scenario_family",
                "request_category",
                "scenario_category_extracted",
                "expected_request_category"
            ]
        ]
        .head(30)
        .to_string(index=False)
    )
else:
    print("\nPASS — scenario_family and request_category are consistent.")

# DATASET 2 v7 — CHECK 20
# Check scenario_family vs request_category consistency

df2["scenario_category_extracted"] = (
    df2["scenario_family"]
    .astype(str)
    .str.split("/")
    .str[1]
    .str.lower()
)

category_map = {
    "access": "access",
    "approval": "approval",
    "bank": "bank",
    "channel": "channel",
    "data": "data",
    "deadline": "deadline",
    "document": "document",
    "favour": "favour",
    "meeting": "meeting",
    "payment": "payment",
    "account_change": "bank",
    "authority_abuse": "approval",
    "credential_request": "data",
    "document_request": "document",
    "financial_request": "payment",
    "sensitive_data_request": "data",
    "social_engineering": "favour",
    "urgent_request": "deadline",
    "vendor_payment": "payment"
}

df2["expected_request_category"] = (
    df2["scenario_category_extracted"]
    .map(category_map)
)

category_errors = (
    df2["request_category"].astype(str).str.lower()
    != df2["expected_request_category"]
)

print("Total records:", len(df2))
print("Scenario/request category mismatches:", category_errors.sum())

if category_errors.sum() > 0:
    print("\nExamples:")
    print(
        df2.loc[
            category_errors,
            [
                "identity_id",
                "label",
                "scenario_family",
                "request_category",
                "scenario_category_extracted",
                "expected_request_category"
            ]
        ]
        .head(30)
        .to_string(index=False)
    )
else:
    print("\nPASS — scenario_family and request_category are consistent.")

In [60]:
# DATASET 2 v7 — CHECK 20 (CORRECTED)
# Verify request_category using the value after ":" in scenario_family

# Extract the request category from the end of scenario_family
df2["scenario_request_extracted"] = (
    df2["scenario_family"]
    .astype(str)
    .str.split(":")
    .str[-1]
    .str.strip()
    .str.lower()
)

# Compare with request_category
category_errors = (
    df2["request_category"]
    .astype(str)
    .str.strip()
    .str.lower()
    != df2["scenario_request_extracted"]
)

print("Total records:", len(df2))
print("Scenario/request category mismatches:", category_errors.sum())

if category_errors.sum() > 0:
    print("\nExamples:")
    print(
        df2.loc[
            category_errors,
            [
                "identity_id",
                "label",
                "scenario_family",
                "request_category",
                "scenario_request_extracted"
            ]
        ]
        .head(30)
        .to_string(index=False)
    )
else:
    print("\nPASS — scenario_family and request_category are consistent.")

Total records: 10000
Scenario/request category mismatches: 6849

Examples:
identity_id         label                            scenario_family request_category scenario_request_extracted
    ID-0001    LEGITIMATE                 LEGIT/favour/SEND_ITEM:doc           favour                        doc
    ID-0001    LEGITIMATE               LEGIT/document/SEND_ITEM:doc         document                        doc
    ID-0001    LEGITIMATE                LEGIT/meeting/SEND_ITEM:doc          meeting                        doc
    ID-0001    LEGITIMATE            LEGIT/deadline/APPROVE:approval         deadline                   approval
    ID-0001    LEGITIMATE                  LEGIT/bank/CONFIRM:verify             bank                     verify
    ID-0001 IMPERSONATION   IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         deadline                    payment
    ID-0001 IMPERSONATION       IMP/AUTHORITY_ABUSE/APPROVE:approval         deadline                   approval
    ID-0001 IMPERSONATION      IMP/CREDENTIAL_REQUEST/CONFIRM:verify         document                     verify
    ID-0001 IMPERSONATION          IMP/CHANNEL_CHANGE/SWITCH:channel          meeting                    channel
    ID-0001 IMPERSONATION      IMP/URGENT_REQUEST/MOVE_MONEY:payment         deadline                    payment
    ID-0001 IMPERSONATION          IMP/AUTHORITY_ABUSE/SEND_ITEM:doc         approval                        doc
    ID-0001 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential         document                 credential
    ID-0001 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access                 credential
    ID-0002    LEGITIMATE               LEGIT/document/SEND_ITEM:doc         document                        doc
    ID-0002    LEGITIMATE            LEGIT/deadline/APPROVE:approval         deadline                   approval
    ID-0002    LEGITIMATE         LEGIT/access/CHANGE_RECORD:contact           access                    contact
    ID-0002    LEGITIMATE                 LEGIT/favour/SEND_ITEM:doc           favour                        doc
    ID-0002    LEGITIMATE        LEGIT/channel/CHANGE_RECORD:contact          channel                    contact
    ID-0002    LEGITIMATE                LEGIT/meeting/SEND_ITEM:doc          meeting                        doc
    ID-0002    LEGITIMATE               LEGIT/payment/CONFIRM:verify          payment                     verify
    ID-0002 IMPERSONATION       IMP/AUTHORITY_ABUSE/APPROVE:approval         deadline                   approval
    ID-0002 IMPERSONATION      IMP/VENDOR_PAYMENT/MOVE_MONEY:payment             bank                    payment
    ID-0002 IMPERSONATION   IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         approval                    payment
    ID-0002 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access                 credential
    ID-0002 IMPERSONATION         IMP/DOCUMENT_REQUEST/SEND_ITEM:doc         document                        doc
    ID-0002 IMPERSONATION IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access                 credential
    ID-0002 IMPERSONATION         IMP/DOCUMENT_REQUEST/SEND_ITEM:doc          meeting                        doc
    ID-0002 IMPERSONATION      IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank           access                       bank
    ID-0003    LEGITIMATE               LEGIT/approval/SEND_ITEM:doc         approval                        doc
    ID-0003    LEGITIMATE               LEGIT/deadline/SEND_ITEM:doc         deadline                        doc

In [61]:
# DATASET 2 v7 — CHECK 20A
# Diagnose scenario_family -> request_category mapping
# DO NOT MODIFY DATASET

mapping_check = (
    df2.groupby(
        ["scenario_family", "request_category"],
        dropna=False
    )
    .size()
    .reset_index(name="record_count")
    .sort_values("record_count", ascending=False)
)

print("Unique scenario_family / request_category combinations:",
      len(mapping_check))

print("\nMost common combinations:")
print(
    mapping_check
    .head(50)
    .to_string(index=False)
)

Unique scenario_family / request_category combinations: 76

Most common combinations:
                           scenario_family request_category  record_count
              LEGIT/document/SEND_ITEM:doc         document           500
                  LEGIT/data/DISCLOSE:data             data           500
  IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data             data           371
        IMP/DOCUMENT_REQUEST/SEND_ITEM:doc         document           315
         IMP/CHANNEL_CHANGE/SWITCH:channel          channel           314
               LEGIT/meeting/SEND_ITEM:doc          meeting           262
             LEGIT/bank/CHANGE_RECORD:bank             bank           259
           LEGIT/approval/APPROVE:approval         approval           259
          LEGIT/payment/MOVE_MONEY:payment          payment           254
              LEGIT/channel/SWITCH:channel          channel           250
       LEGIT/channel/CHANGE_RECORD:contact          channel           250
              LEGIT/payment/CONFIRM:verify          payment           246
              LEGIT/approval/SEND_ITEM:doc         approval           241
                 LEGIT/bank/CONFIRM:verify             bank           241
              LEGIT/meeting/CONFIRM:verify          meeting           238
        LEGIT/access/CHANGE_RECORD:contact           access           201
     IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank          payment           186
     IMP/VENDOR_PAYMENT/MOVE_MONEY:payment          payment           186
               LEGIT/favour/CONFIRM:verify           favour           180
         LEGIT/deadline/MOVE_MONEY:payment         deadline           176
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access           173
           LEGIT/deadline/APPROVE:approval         deadline           171
  IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data         document           164
                LEGIT/favour/DISCLOSE:data           favour           161
         IMP/CHANNEL_CHANGE/SWITCH:channel          meeting           160
                LEGIT/favour/SEND_ITEM:doc           favour           159
        IMP/DOCUMENT_REQUEST/SEND_ITEM:doc          meeting           154
              LEGIT/deadline/SEND_ITEM:doc         deadline           153
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access           151
               LEGIT/access/CONFIRM:verify           access           150
          LEGIT/access/GRANT_ACCESS:access           access           149
  IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         deadline           103
   IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access             bank            98
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential         document            96
     IMP/VENDOR_PAYMENT/MOVE_MONEY:payment             bank            96
       IMP/URGENT_REQUEST/APPROVE:approval         deadline            95
     IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank             bank            94
         IMP/AUTHORITY_ABUSE/SEND_ITEM:doc         approval            92
    IMP/FINANCIAL_REQUEST/APPROVE:approval         deadline            92
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify         document            91
    IMP/FINANCIAL_REQUEST/APPROVE:approval          payment            86
     IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank             bank            85
      IMP/AUTHORITY_ABUSE/APPROVE:approval         approval            84
      IMP/SOCIAL_ENGINEERING/DISCLOSE:data           favour            82
  IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment          payment            82
    IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access             bank            81
  IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         approval            79
     IMP/URGENT_REQUEST/MOVE_MONEY:payment         deadline            79
      IMP/SOCIAL_ENGINEERING/SEND_ITEM:doc           favour            79
    IMP/FINANCIAL_REQUEST/APPROVE:approval         approval            78

In [62]:
# DATASET 2 v7 — CHECK 20B
# Check whether each exact scenario_family has one stable request_category

scenario_category_counts = (
    df2.groupby(
        "scenario_family",
        dropna=False
    )["request_category"]
    .nunique()
    .reset_index(name="unique_request_categories")
)

inconsistent_scenarios = scenario_category_counts[
    scenario_category_counts["unique_request_categories"] > 1
]

print(
    "Unique scenario_family values:",
    len(scenario_category_counts)
)

print(
    "Scenario families mapped to multiple request categories:",
    len(inconsistent_scenarios)
)

if len(inconsistent_scenarios) > 0:
    print("\nInconsistent scenario families:")
    print(
        inconsistent_scenarios
        .sort_values("unique_request_categories", ascending=False)
        .to_string(index=False)
    )
else:
    print(
        "\nPASS — Every exact scenario_family maps to one request_category."
    )

Unique scenario_family values: 43
Scenario families mapped to multiple request categories: 22

Inconsistent scenario families:
                           scenario_family  unique_request_categories
      IMP/AUTHORITY_ABUSE/APPROVE:approval                          3
    IMP/AUTHORITY_ABUSE/MOVE_MONEY:payment                          3
     IMP/URGENT_REQUEST/MOVE_MONEY:payment                          3
  IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment                          3
    IMP/FINANCIAL_REQUEST/APPROVE:approval                          3
         IMP/AUTHORITY_ABUSE/SEND_ITEM:doc                          3
          IMP/URGENT_REQUEST/SEND_ITEM:doc                          3
      IMP/SOCIAL_ENGINEERING/SEND_ITEM:doc                          3
      IMP/SOCIAL_ENGINEERING/DISCLOSE:data                          3
     IMP/SOCIAL_ENGINEERING/CONFIRM:verify                          3
       IMP/URGENT_REQUEST/APPROVE:approval                          3
    IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access                          2
   IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access                          2
     IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank                          2
  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact                          2
  IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data                          2
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify                          2
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential                          2
         IMP/CHANNEL_CHANGE/SWITCH:channel                          2
        IMP/DOCUMENT_REQUEST/SEND_ITEM:doc                          2
     IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank                          2
     IMP/VENDOR_PAYMENT/MOVE_MONEY:payment                          2

In [63]:
# DATASET 2 v7 — CHECK 20C
# Show every inconsistent scenario_family and its request_category distribution

inconsistent_families = (
    df2.groupby("scenario_family")["request_category"]
    .nunique()
)

inconsistent_families = inconsistent_families[
    inconsistent_families > 1
].index

for family in inconsistent_families:
    print("\n" + "=" * 90)
    print("SCENARIO FAMILY:", family)

    print(
        df2.loc[
            df2["scenario_family"] == family,
            "request_category"
        ].value_counts()
    )

==========================================================================================
SCENARIO FAMILY: IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access
request_category
bank      98
access    48
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank
request_category
bank      85
access    46
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact
request_category
bank      43
access    16
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access
request_category
bank      81
access    53
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/AUTHORITY_ABUSE/APPROVE:approval
request_category
approval    84
deadline    48
meeting     32
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/AUTHORITY_ABUSE/MOVE_MONEY:payment
request_category
approval    70
meeting     35
deadline    33
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/AUTHORITY_ABUSE/SEND_ITEM:doc
request_category
approval    92
meeting     49
deadline    38
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/CHANNEL_CHANGE/SWITCH:channel
request_category
channel    314
meeting    160
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/CREDENTIAL_REQUEST/CONFIRM:verify
request_category
access      173
document     91
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/CREDENTIAL_REQUEST/DISCLOSE:credential
request_category
access      151
document     96
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/DOCUMENT_REQUEST/SEND_ITEM:doc
request_category
document    315
meeting     154
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/FINANCIAL_REQUEST/APPROVE:approval
request_category
deadline    92
payment     86
approval    78
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment
request_category
deadline    103
payment      82
approval     79
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data
request_category
data        371
document    164
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/SOCIAL_ENGINEERING/CONFIRM:verify
request_category
favour     72
meeting    43
data       32
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/SOCIAL_ENGINEERING/DISCLOSE:data
request_category
favour     82
data       46
meeting    39
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/SOCIAL_ENGINEERING/SEND_ITEM:doc
request_category
favour     79
meeting    47
data       46
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/URGENT_REQUEST/APPROVE:approval
request_category
deadline    95
meeting     44
payment     35
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/URGENT_REQUEST/MOVE_MONEY:payment
request_category
deadline    79
meeting     42
payment     39
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/URGENT_REQUEST/SEND_ITEM:doc
request_category
deadline    78
meeting     41
payment     39
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank
request_category
payment    186
bank        94
Name: count, dtype: int64

==========================================================================================
SCENARIO FAMILY: IMP/VENDOR_PAYMENT/MOVE_MONEY:payment
request_category
payment    186
bank        96
Name: count, dtype: int64

In [64]:
# DATASET 2 v7 — CHECK 20D
# Compact summary of all inconsistent scenario_family mappings

mapping_summary = (
    df2[df2["scenario_family"].isin(inconsistent_families)]
    .groupby(["scenario_family", "request_category"])
    .size()
    .reset_index(name="record_count")
)

# Pivot for easy inspection
mapping_pivot = (
    mapping_summary
    .pivot(
        index="scenario_family",
        columns="request_category",
        values="record_count"
    )
    .fillna(0)
    .astype(int)
)

print("All inconsistent scenario families:")
print(mapping_pivot.to_string())

All inconsistent scenario families:
request_category                            access  approval  bank  channel  data  deadline  document  favour  meeting  payment
scenario_family
IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access         48         0    98        0     0         0         0       0        0        0
IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank           46         0    85        0     0         0         0       0        0        0
IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact        16         0    43        0     0         0         0       0        0        0
IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access          53         0    81        0     0         0         0       0        0        0
IMP/AUTHORITY_ABUSE/APPROVE:approval             0        84     0        0     0        48         0       0       32        0
IMP/AUTHORITY_ABUSE/MOVE_MONEY:payment           0        70     0        0     0        33         0       0       35        0
IMP/AUTHORITY_ABUSE/SEND_ITEM:doc                0        92     0        0     0        38         0       0       49        0
IMP/CHANNEL_CHANGE/SWITCH:channel                0         0     0      314     0         0         0       0      160        0
IMP/CREDENTIAL_REQUEST/CONFIRM:verify          173         0     0        0     0         0        91       0        0        0
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential     151         0     0        0     0         0        96       0        0        0
IMP/DOCUMENT_REQUEST/SEND_ITEM:doc               0         0     0        0     0         0       315       0      154        0
IMP/FINANCIAL_REQUEST/APPROVE:approval           0        78     0        0     0        92         0       0        0       86
IMP/FINANCIAL_REQUEST/MOVE_MONEY:payment         0        79     0        0     0       103         0       0        0       82
IMP/SENSITIVE_DATA_REQUEST/DISCLOSE:data         0         0     0        0   371         0       164       0        0        0
IMP/SOCIAL_ENGINEERING/CONFIRM:verify            0         0     0        0    32         0         0      72       43        0
IMP/SOCIAL_ENGINEERING/DISCLOSE:data             0         0     0        0    46         0         0      82       39        0
IMP/SOCIAL_ENGINEERING/SEND_ITEM:doc             0         0     0        0    46         0         0      79       47        0
IMP/URGENT_REQUEST/APPROVE:approval              0         0     0        0     0        95         0       0       44       35
IMP/URGENT_REQUEST/MOVE_MONEY:payment            0         0     0        0     0        79         0       0       42       39
IMP/URGENT_REQUEST/SEND_ITEM:doc                 0         0     0        0     0        78         0       0       41       39
IMP/VENDOR_PAYMENT/CHANGE_RECORD:bank            0         0    94        0     0         0         0       0        0      186
IMP/VENDOR_PAYMENT/MOVE_MONEY:payment            0         0    96        0     0         0         0       0        0      186

In [65]:
# DATASET 2 v7 — CHECK 20E
# Determine how LEGIT scenario families map to request_category.
# This helps establish the intended mapping for IMPERSONATION families.

legit_mapping = (
    df2[df2["label"] == "LEGITIMATE"]
    .groupby(["scenario_family", "request_category"])
    .size()
    .reset_index(name="record_count")
    .sort_values(["scenario_family", "record_count"], ascending=[True, False])
)

print(legit_mapping.to_string(index=False))

                    scenario_family request_category  record_count
 LEGIT/access/CHANGE_RECORD:contact           access           201
        LEGIT/access/CONFIRM:verify           access           150
   LEGIT/access/GRANT_ACCESS:access           access           149
    LEGIT/approval/APPROVE:approval         approval           259
       LEGIT/approval/SEND_ITEM:doc         approval           241
      LEGIT/bank/CHANGE_RECORD:bank             bank           259
          LEGIT/bank/CONFIRM:verify             bank           241
LEGIT/channel/CHANGE_RECORD:contact          channel           250
       LEGIT/channel/SWITCH:channel          channel           250
           LEGIT/data/DISCLOSE:data             data           500
    LEGIT/deadline/APPROVE:approval         deadline           171
  LEGIT/deadline/MOVE_MONEY:payment         deadline           176
       LEGIT/deadline/SEND_ITEM:doc         deadline           153
       LEGIT/document/SEND_ITEM:doc         document           500
        LEGIT/favour/CONFIRM:verify           favour           180
         LEGIT/favour/DISCLOSE:data           favour           161
         LEGIT/favour/SEND_ITEM:doc           favour           159
       LEGIT/meeting/CONFIRM:verify          meeting           238
        LEGIT/meeting/SEND_ITEM:doc          meeting           262
       LEGIT/payment/CONFIRM:verify          payment           246
   LEGIT/payment/MOVE_MONEY:payment          payment           254

In [66]:
# DATASET 2 v7 — CHECK 20F
# Inspect ambiguous IMP scenario families using actual message content

ambiguous_families = [
    "IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access",
    "IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank",
    "IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact",
    "IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access",
    "IMP/CREDENTIAL_REQUEST/CONFIRM:verify",
    "IMP/CREDENTIAL_REQUEST/DISCLOSE:credential"
]

cols = [
    "identity_id",
    "label",
    "scenario_family",
    "request_category",
    "subject",
    "message"
]

ambiguous_df = df2[
    df2["scenario_family"].isin(ambiguous_families)
][cols].copy()

print(
    ambiguous_df[
        [
            "scenario_family",
            "request_category",
            "subject",
            "message"
        ]
    ]
    .head(50)
    .to_string(index=False)
)

                           scenario_family request_category                                                        subject                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 message
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify         document                       Follow-up: the site handover certificate                                                                                                                                                                                                                                                           BILL-2024-710 was submitted during October covering Rs. 526,000. Could you verify the status of BILL-2024-710 before payment at https://niti.gov.in/portal/75679? The authenticator had stopped working after the upgrade. A copy is available at https://niti.gov.in/portal/75679. Projects have already examined the item. Projects has already certified this.\n\nKindly revert once anything else is needed.\n\nBest,\nMohan Charan Majhi\nChief Minister
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential         document                           Query on the tender evaluation sheet                                                                                                                                                                                                                                                                                                                                                                                                                 Dear Gaurav,\n\nProfiles that are not revalidated will be suspended. Would you pull the second-factor code on your authenticator to mohan.majhi92@hotmail.com and no one else? This is immediate - it has to be completed before close of business.\n\nMany thanks,\nMohan Charan Majhi\nChief Minister
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access                         Access review - the procurement portal                                                                                                                                                                                                                                                                                                                                 Profiles that are not confirmed will be suspended. The covering sheet is attached. Internal Audit have been held informed. The form is at https://odisha.net/docs/19254. Kindly forward the MFA code from your device to this thread alone. There is no time - the date is this evening.\n\nLet me know the best way we wish to take this forward.\n\nWith regards,\nMohan Charan Majhi
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access                                  Access to the treasury module                                                                                                                                                                                                                                   Dear Hemant Sharma,\n\nPlace at your disposal the existing password for the account to the records section at docs.20@gmail.com. Profiles not revalidated will be blocked. The utilisation certificate sits in the record with IT Services. Our statutory filing for May includes this. I shall answer for the deviation myself. Available on +91 90291 91960 should anything be unclear. Reachable on +91 90291 91960 should anything be unclear.\n\nRegards,\nInternal Audit Office
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access The finance portal access for the records digitisation backlog                                                                                                                                                                                                                                                                                                                                                       Hemant,\n\nPull the existing password on the account to accounts.32@yahoo.in. Profiles that are not revalidated get suspended. Please do not call the office line on this. A mandate has been validated via the standard route. This statutory window closes on 22 January. Thanks for the assistance here.\n\nRegards and thanks,\nEstate Office\nEstate Section
     IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank           access                                    Re: the vendor master login                                                                                                                                                                                                                                                                        Hello Omkar,\n\nPapers pertaining to the vendor consolidation exercise sit with IT Services. The existing account is suspended. To settle it, configure the payee record against PO/2025/356 to the beneficiary advised by Meridian Facility Services earlier this month. Kindly there is no need to route it through IT Services. Glad to take this up on a call if that is easier.\n\nBest regards,\nHemant Sharma\nAdditional Chief Secretary
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access                         Fwd: Access review - the vendor master                                                                                                                                                                                                                                                                                                                         Dear Anuj,\n\nI discussed the point in passing at the previous review. My authenticator had stopped working after the upgrade. A form is available at https://drive.google.com/sso/63335. Certify receipt of the beneficiary list against CH-63798 at https://drive.google.com/sso/63335 by 4 May. This closing time is close of business today.\n\nRegards,\nAccounts Office\nAccounts Section
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access                                   Re: the payroll system login                                                                                                                                                                                                                                                                                Internal Audit raised INC-86636 on the matter last week. My authenticator has desynchronised since the migration. A copy is at https://nic.in/review/7903. Record the staff code and the last four digits of the registered account at the revalidation page at https://nic.in/review/7903. Please feel free to check with Internal Audit if you wish. Thanks for your assistance on this.\n\nRegards,\nVivek Mohanty\nManager - Finance
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access                              Access request: the vendor master                                                                                                                                                                                                                 Hi Pruthwee,\n\nThe revalidation exercise on the vendor master ends today. Towards that purpose, the regional outreach programme is at the closure stage and Human Resources has flagged this. The form is available at https://ntpc.co.in/id/22120. Validate the account entry held on the vendor master at the verification page at https://ntpc.co.in/id/22120. This request is logged under TKT-30575. Happy to discuss over a call if that is easier.\n\nRegards,\nKavita Pillai\nDeputy Secretary
  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact             bank                    Re: Beneficiary details - Sunrise Infratech                                                                                                                                                                                                                                                                                    Hello Nandini Barik,\n\nThe signed minutes is in the file with Finance. For this purpose, the matter falls with Finance for present. The existing mandate is suspended.\n\nOverwrite the officer of reference for the disaster preparedness review to the mandate shown on the latest sheet. Finance has already certified the entry. Marking Finance to keep them in the loop.\n\nBest,\nPruthwee Raj Pani\nAFA-cum-Under Secretary
  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact             bank                       Re: bank mandate for Ganga Constructions                                                                                                                                                                                                                                                                              Change the recorded contact line against the account to 364073976752 at IDBI Bank (SBIN0516065). Our branch has reissued the account record.\n\nThe page is available at https://tinyurl.com/m92123. This sits under BILL-2025-9489. A note will be raised afterwards to regularise it. Kindly do check with Stores if you be necessary. Kindly let me know once something else is required.\n\nRegards and thanks,\nParthasarathi Mallick
  IMP/ACCOUNT_CHANGE/CHANGE_RECORD:contact           access                    Fwd: Access review - the compliance tracker                                                                                                                                                                                                                                                                                                                          Hi Sasmita,\n\nOur bank has migrated the customer number.\n\nThe form is at https://odisha.mail.mailsecure.net/share/5816. We would ask that you re-point the recorded mobile number on the account to the account advised by Orion Office Supplies last month. Do say if I have missed anything. This is urgent - it has to be completed before close of business. Thanks for the help on it.
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access                     Access review - the HR self-service portal                                                                                                                                                            Good afternoon Sanjeeb Kumar Mishra,\n\nPlease reveal the existing passcode on the profile to this thread alone. My verification code keeps going to the handset we no longer hold. The requirement arises from the October cycle of the citizen services portal rollout. Treat my word as the authority for it. Many thanks for the assistance on this. Please feel free to check with Finance if you be necessary.\n\nFinance has asked me to carry the matter ahead directly. Kindly confirm this.\n\nSincerely,\nSecretariat Office\nSecretariat Section
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential         document                                  Copy of the audited statement                                                                                                                                                                                                                                                                                                                    Greetings Usha,\n\nProfiles that are not revalidated get suspended. Total amount involved is Rs. 952,000.\n\nIn order to settle this, we await your response. A handover of the field survey exercise to Estate is underway. Kindly place at your disposal the current password for the profile to this thread alone. Thank you in advance with it.\n\nSincerely,\nYamini Sarangi\nSpecial Secretary
   IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access           access                              Verification step on the intranet                                                                                                                                                                                                                                                      Good morning Satyapriya Rath,\n\nThe bank has reissued the account record. The audit party has been examining the disaster preparedness review records. Please correct the approver rights on the intranet to the payee named in PO/2025/680. Against that basis, we have no scope to wait for IT Services' clearance. Verification has since been completed from this end. Kindly acknowledge receipt.\n\nSincerely,\nRekha Malik\nAccounts, Novatech Instruments
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access                                     Account lockout - CH-66613                                                                                                                   Good morning Satyapriya,\n\nThe index sheet is enclosed. This request comes from the July cycle of the regional outreach programme. My verification code is being sent to a device we no longer reach. This falls under SI-2024-7205. Given the position, the form is available at https://cag.gov.in/share/46124. Kindly confirm receipt. May I ask you to verify your credential record on the ticketing system at the revalidation form at https://cag.gov.in/share/46124. The concurrence is minuted in the record. Thank you in advance with it.\n\nThank you,\nBijaya Mohanty\nDeputy Secretary
   IMP/ACCOUNT_CHANGE/CHANGE_RECORD:access             bank                             Account particulars for August run Dear Sarika,\n\nOur audit team is reviewing the digital records migration files. Our branch have migrated the account record. The form is available at https://odisha.verify.gateway-mail.net/portal/52306. The matter concerns Bluepeak Systems' engagement under the digital records migration. Substitute the approver permissions in the HR self-service portal to the new account 931582505580 at IDBI Bank. The revised scope note is on the record with Vigilance. The request arises from the August cycle of the digital records migration.\n\nSR-12391 carries the authorisation for this release.\n\nPlease do check through Vigilance if needed.\n\nThanks,\nKrushna Chandra Satpathy\nAdditional Secretary
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify           access                Verification step on the HR self-service portal                                                                                                                                                                                                              Good afternoon Lalit,\n\nRecord the credential record on the HR self-service portal at https://odisha-india.gov.in/share/43444 by 26 September. My authenticator has desynchronised after the upgrade. Please do not call the office desk on this. We am consolidating all papers on the accessibility compliance project before 26 September.\n\nMarking Administration for information.\n\nPlease do verify through Administration if required.\n\nBest,\nKrushna Chandra Satpathy\nAdditional Secretary
     IMP/CREDENTIAL_REQUEST/CONFIRM:verify         document                              Re: Request for the risk register                                                                                                                                                                             Dear Bhavna,\n\nWould you confirm delivery of the risk register against TKT-21733 at https://odisha.gov.in/verify/27175? The token has desynchronised after the upgrade. A query by Legal on BILL-2025-3295 is pending. Happy to discuss on a call if that is easier. Any sanction note may follow afterwards. The amount involved is Rs. 233,000. Please do not put this before Legal. This sits inside the sanctioned limits. For that purpose, grateful for a response.\n\nWith regards,\nKrushna Chandra Satpathy\nAdditional Secretary
    IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access             bank                                Banking details for PO/2025/228                                                                                                                                                                                                                                                                                                                                                           Hi Saumyajit,\n\nMy current mandate is closed. Kindly confirm this.\n\nProvision maker permissions in the compliance tracker to me directly. A file will be raised later to regularise the action. The approval is minuted in the record. Let me know the best way you would like to proceed.\n\nRegards and thanks,\nSecretariat Office\nSecretariat Section
    IMP/ACCOUNT_CHANGE/GRANT_ACCESS:access           access                                   Re: the finance portal login                                                                                                                                                                                                                                                                                                                            Respected Saswata,\n\nThe mandate form will be sent once it is countersigned.\n\nAvailable on +91 72460 71066 should anything be unclear. The copy is at https://odisha.gov.in/docs/34181. Provision maker rights in the finance portal to this thread. The internal control review is nearing a handover stage and Projects have listed this. Please confirm if anything further is needed.
IMP/CREDENTIAL_REQUEST/DISCLOSE:credential           access       The shared drive access for the procurement reform pilot                                                                                                                                                                                                                                                                                                                             Hi Lakshmi Kurien,\n\nThe authenticator has desynchronised after the upgrade. Kindly pass on the current passcode on the account to me directly. The item shows against PO/2025/122 in the shared drive.\n\nPlease do not mark Secretariat in this. Reachable on +91 76717 97614 should anything be unclear.\n\nWith regards,\nSaswata Mishra\nAdditional Chief Secretary to Chief Minister
     IMP/ACCOUNT_CHANGE/CHANGE_RECORD:bank             bank                    Re: bank mandate for Prabhat Printing Press                                                                                                                                                                                              Good morning Manoj,\n\nMy existing account has been suspended. The page is at https://odisha.gov.in/dms/10190. We would ask that you amend the beneficiary details for Prabhat Printing Press to the beneficiary notified by Prabhat Printing Press earlier this week.\n\nReference REQ-80205 refers. IT Services has already cleared the step. Copying IT Services for information. Kindly feel free to check with IT Services if required. Kindly do check through IT Services if it be necessary.\n\nBest,\nLalit Gupta

In [67]:
# Remove temporary validation columns created during Check 20

temp_cols = [
    "scenario_category_extracted",
    "expected_request_category",
    "scenario_request_extracted"
]

df2.drop(
    columns=[c for c in temp_cols if c in df2.columns],
    inplace=True
)

print("Temporary validation columns removed.")
print("Current Dataset 2 shape:", df2.shape)

Temporary validation columns removed.
Current Dataset 2 shape: (10000, 34)

In [68]:
# DATASET 2 v7 — CHECK 21
# Re-check organization_domain and organization against Dataset 1

# Dataset 1 identity mapping
df1_map = df1.set_index("identity_id")

# Compare Dataset 2 against Dataset 1
domain_mismatch = (
    df2["organization_domain"].astype(str).str.strip().str.lower()
    !=
    df2["identity_id"]
        .map(df1_map["official_domain"])
        .astype(str).str.strip().str.lower()
)

organization_mismatch = (
    df2["organization"].astype(str).str.strip()
    !=
    df2["identity_id"]
        .map(df1_map["organization"])
        .astype(str).str.strip()
)

print("Organization domain mismatches:", domain_mismatch.sum())
print("Organization name mismatches:", organization_mismatch.sum())

print("\nAffected identity IDs:")
affected = df2.loc[
    domain_mismatch | organization_mismatch,
    "identity_id"
].unique()

print(list(affected))

print("\nMismatch summary:")
print(
    df2.loc[
        domain_mismatch | organization_mismatch,
        [
            "identity_id",
            "organization",
            "organization_domain"
        ]
    ]
    .drop_duplicates()
    .to_string(index=False)
)

Organization domain mismatches: 140
Organization name mismatches: 40

Affected identity IDs:
['ID-0114', 'ID-0140', 'ID-0155', 'ID-0210', 'ID-0215', 'ID-0216', 'ID-0233', 'ID-0239', 'ID-0250']

Mismatch summary:
identity_id                                    organization organization_domain
    ID-0114 Electronics & Information Technology Department              gov.in
    ID-0140                              Finance Department       odisha.gov.in
    ID-0155                              Finance Department       odisha.gov.in
    ID-0210                                Works Department              gov.in
    ID-0215                                Works Department              gov.in
    ID-0216                                Works Department              gov.in
    ID-0233                                Works Department              gov.in
    ID-0239                                Works Department              gov.in
    ID-0250                                Works Department              gov.in

In [69]:
# FIX CHECK 21
# Synchronize Dataset 2 identity metadata with frozen Dataset 1

# Create authoritative mappings from Dataset 1
org_map = df1.set_index("identity_id")["organization"].to_dict()
domain_map = df1.set_index("identity_id")["official_domain"].to_dict()

# Fix organization
df2["organization"] = df2["identity_id"].map(org_map)

# Fix organization domain
df2["organization_domain"] = df2["identity_id"].map(domain_map)

print("Dataset 2 identity metadata synchronized with Dataset 1.")
print("Current Dataset 2 shape:", df2.shape)

print("\nAffected identities updated:")
print([
    "ID-0114",
    "ID-0140",
    "ID-0155",
    "ID-0210",
    "ID-0215",
    "ID-0216",
    "ID-0233",
    "ID-0239",
    "ID-0250"
])

Dataset 2 identity metadata synchronized with Dataset 1.
Current Dataset 2 shape: (10000, 34)

Affected identities updated:
['ID-0114', 'ID-0140', 'ID-0155', 'ID-0210', 'ID-0215', 'ID-0216', 'ID-0233', 'ID-0239', 'ID-0250']

In [70]:
# CHECK 21 — VERIFY DATASET 2 METADATA AGAINST DATASET 1

df1_map = df1.set_index("identity_id")

domain_mismatch = (
    df2["organization_domain"].astype(str).str.strip().str.lower()
    !=
    df2["identity_id"]
        .map(df1_map["official_domain"])
        .astype(str).str.strip().str.lower()
)

organization_mismatch = (
    df2["organization"].astype(str).str.strip()
    !=
    df2["identity_id"]
        .map(df1_map["organization"])
        .astype(str).str.strip()
)

print("Organization domain mismatches:", domain_mismatch.sum())
print("Organization name mismatches:", organization_mismatch.sum())

if domain_mismatch.sum() == 0 and organization_mismatch.sum() == 0:
    print("\nPASS — Dataset 2 identity metadata matches Dataset 1.")
else:
    print("\nFAIL — Metadata mismatches still exist.")
    
    affected = df2.loc[
        domain_mismatch | organization_mismatch,
        "identity_id"
    ].unique()
    
    print("Affected identities:", list(affected))

Organization domain mismatches: 0
Organization name mismatches: 0

PASS — Dataset 2 identity metadata matches Dataset 1.

In [71]:
# CHECK 22 — LEGITIMATE SENDER CONSISTENCY

# Dataset 1 authoritative mappings
df1_map = df1.set_index("identity_id")

# Only legitimate records
legit = df2[df2["label"].str.upper() == "LEGITIMATE"].copy()

# Expected official email/domain
legit["expected_email"] = legit["identity_id"].map(
    df1_map["official_email"]
)

legit["expected_domain"] = legit["identity_id"].map(
    df1_map["official_domain"]
)

# Normalize
legit["sender_email_clean"] = (
    legit["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

legit["expected_email_clean"] = (
    legit["expected_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

legit["sender_domain"] = (
    legit["sender_email_clean"]
    .str.split("@")
    .str[-1]
)

legit["expected_domain_clean"] = (
    legit["expected_domain"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Check whether sender email is exactly the official email
email_mismatch = (
    legit["sender_email_clean"] != legit["expected_email_clean"]
)

# Check whether sender domain matches official domain
domain_mismatch = (
    legit["sender_domain"] != legit["expected_domain_clean"]
)

print("LEGITIMATE records:", len(legit))
print("Official email mismatches:", email_mismatch.sum())
print("Official domain mismatches:", domain_mismatch.sum())

print("\nLEGITIMATE records with domain mismatch:")
print(
    legit.loc[
        domain_mismatch,
        [
            "identity_id",
            "identity_name",
            "sender_name",
            "sender_email",
            "expected_email",
            "expected_domain"
        ]
    ]
    .drop_duplicates()
    .to_string(index=False)
)

LEGITIMATE records: 5000
Official email mismatches: 3010
Official domain mismatches: 2356

LEGITIMATE records with domain mismatch:
identity_id                           identity_name                   sender_name                                 sender_email                           expected_email          expected_domain
    ID-0001                      Mohan Charan Majhi            Mohan Charan Majhi                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0001                      Mohan Charan Majhi                 Sasmita Verma             sasmita.verma@induscabling.co.in                               cmo@nic.in            odisha.gov.in
    ID-0002                           Hemant Sharma                 Hemant Sharma                             iprsec.or@nic.in                         iprsec.or@nic.in            odisha.gov.in
    ID-0002                           Hemant Sharma                   Kiran Ahuja            kiran.ahuja@capstonelogistics.com                         iprsec.or@nic.in            odisha.gov.in
    ID-0002                           Hemant Sharma                   Madhu Panda        madhu.panda@tridenthousekeeping.co.in                         iprsec.or@nic.in            odisha.gov.in
    ID-0003                Anuj Kumar Das Pattanaik      Anuj Kumar Das Pattanaik                       director-ipr.od@gov.in                   director-ipr.od@gov.in            odisha.gov.in
    ID-0003                Anuj Kumar Das Pattanaik               Deepak Varghese                  deepak.varghese@infosys.com                   director-ipr.od@gov.in            odisha.gov.in
    ID-0003                Anuj Kumar Das Pattanaik                 Rakesh Kapoor                 rakesh.kapoor@orionoffice.in                   director-ipr.od@gov.in            odisha.gov.in
    ID-0004                       Pruthwee Raj Pani             Pruthwee Raj Pani                    pruthweeraj1970@gmail.com                pruthweeraj1970@gmail.com            odisha.gov.in
    ID-0004                       Pruthwee Raj Pani            Ashirbad Deshpande ashirbad.deshpande@pinnaclefurnishings.co.in                pruthweeraj1970@gmail.com            odisha.gov.in
    ID-0005                   Parthasarathi Mallick         Parthasarathi Mallick                               rti-ori@nic.in                           rti-ori@nic.in            odisha.gov.in
    ID-0006                    Sanjeeb Kumar Mishra          Sanjeeb Kumar Mishra                             finsec.or@nic.in                         finsec.or@nic.in            odisha.gov.in
    ID-0006                    Sanjeeb Kumar Mishra                  Pooja Pillai                     pooja.pillai@outlook.com                         finsec.or@nic.in            odisha.gov.in
    ID-0006                    Sanjeeb Kumar Mishra               Debasish Kapoor          debasish.kapoor@anvilfabrication.in                         finsec.or@nic.in            odisha.gov.in
    ID-0006                    Sanjeeb Kumar Mishra                  Suresh Sahoo                     suresh.sahoo@outlook.com                         finsec.or@nic.in            odisha.gov.in
    ID-0007                          Yamini Sarangi                  Ananya Dutta           ananya.dutta@vertexconsultancy.com                    yamini.sarangi@nic.in            odisha.gov.in
    ID-0007                          Yamini Sarangi                   Prakash Sen                           prakash.sen@pwc.in                    yamini.sarangi@nic.in            odisha.gov.in
    ID-0007                          Yamini Sarangi                Yamini Sarangi                        yamini.sarangi@nic.in                    yamini.sarangi@nic.in            odisha.gov.in
    ID-0007                          Yamini Sarangi                Pratyush Menon         pratyush.menon@skylinenetworks.co.in                    yamini.sarangi@nic.in            odisha.gov.in
    ID-0008                         Satyapriya Rath               Satyapriya Rath                             finsec.or@nic.in                         finsec.or@nic.in            odisha.gov.in
    ID-0008                         Satyapriya Rath               Sasmita Chauhan                     sasmita.chauhan@yahoo.in                         finsec.or@nic.in            odisha.gov.in
    ID-0008                         Satyapriya Rath                 Divya Khuntia                 divya.khuntia@rediffmail.com                         finsec.or@nic.in            odisha.gov.in
    ID-0008                         Satyapriya Rath                  Bikash Naidu             bikash.naidu@aaravstationers.net                         finsec.or@nic.in            odisha.gov.in
    ID-0008                         Satyapriya Rath              Pratyush Routray           pratyush.routray@zenithsecurity.in                         finsec.or@nic.in            odisha.gov.in
    ID-0009                Krushna Chandra Satpathy      Krushna Chandra Satpathy                             finsec.or@nic.in                         finsec.or@nic.in            odisha.gov.in
    ID-0009                Krushna Chandra Satpathy                 Sandeep Ahuja        sandeep.ahuja@capstonelogistics.co.in                         finsec.or@nic.in            odisha.gov.in
    ID-0009                Krushna Chandra Satpathy                 Madhu Rastogi        madhu.rastogi@tridenthousekeeping.net                         finsec.or@nic.in            odisha.gov.in
    ID-0010                          Saumyajit Rout                Saumyajit Rout                     saumyajit.rout@gmail.com                 saumyajit.rout@gmail.com            odisha.gov.in
    ID-0010                          Saumyajit Rout                   Deepak Seth                      deepak.seth@hotmail.com                 saumyajit.rout@gmail.com            odisha.gov.in
    ID-0010                          Saumyajit Rout                Omkar Kulkarni                omkar.kulkarni@protonmail.com                 saumyajit.rout@gmail.com            odisha.gov.in
    ID-0011                          Saswata Mishra                Saswata Mishra                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0011                          Saswata Mishra                  Bijaya Dutta                    bijaya.dutta@hdfcbank.com                               cmo@nic.in            odisha.gov.in
    ID-0011                          Saswata Mishra                 Anjali Kurien                   anjali.kurien@bluepeak.net                               cmo@nic.in            odisha.gov.in
    ID-0011                          Saswata Mishra                Preeti Rastogi                     preeti.rastogi@gmail.com                               cmo@nic.in            odisha.gov.in
    ID-0011                          Saswata Mishra                  Bikash Singh             bikash.singh@anvilfabrication.in                               cmo@nic.in            odisha.gov.in
    ID-0011                          Saswata Mishra                   Meera Singh                        meera.singh@gmail.com                               cmo@nic.in            odisha.gov.in
    ID-0012                       Manoj Kumar Sahoo                    Naveen Sen                          naveen.sen@icai.org                               cmo@nic.in            odisha.gov.in
    ID-0012                       Manoj Kumar Sahoo                  Omkar Parida                       omkar.parida@wipro.com                               cmo@nic.in            odisha.gov.in
    ID-0012                       Manoj Kumar Sahoo             Manoj Kumar Sahoo                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0012                       Manoj Kumar Sahoo                    Kiran Iyer                            kiran.iyer@gov.in                               cmo@nic.in            odisha.gov.in
    ID-0012                       Manoj Kumar Sahoo                    Suresh Das                         suresh.das@yahoo.com                               cmo@nic.in            odisha.gov.in
    ID-0012                       Manoj Kumar Sahoo                  Suresh Sahoo                        suresh.sahoo@kpmg.com                               cmo@nic.in            odisha.gov.in
    ID-0013                             Anupam Saha                  Ritu Khuntia                        ritu.khuntia@yahoo.in                               cmo@nic.in            odisha.gov.in
    ID-0013                             Anupam Saha                   Anupam Saha                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0013                             Anupam Saha                  Harish Ghosh                     harish.ghosh@nhai.gov.in                               cmo@nic.in            odisha.gov.in
    ID-0013                             Anupam Saha                 Sasmita Barik                 sasmita.barik@protonmail.com                               cmo@nic.in            odisha.gov.in
    ID-0014                  Prasanna Kumar Sarangi        Prasanna Kumar Sarangi                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0014                  Prasanna Kumar Sarangi                Swati Tripathy                  swati.tripathy@powergrid.in                               cmo@nic.in            odisha.gov.in
    ID-0014                  Prasanna Kumar Sarangi                  Rohit Kurien           rohit.kurien@aaravstationers.co.in                               cmo@nic.in            odisha.gov.in
    ID-0014                  Prasanna Kumar Sarangi                  Nikhil Panda           nikhil.panda@vertexconsultancy.com                               cmo@nic.in            odisha.gov.in
    ID-0015                            Mirdha Toppo                  Manish Nayak                     manish.nayak@infosys.com                               cmo@nic.in            odisha.gov.in
    ID-0015                            Mirdha Toppo              Yashwant Routray                yashwant.routray@axisbank.com                               cmo@nic.in            odisha.gov.in
    ID-0015                            Mirdha Toppo                  Deepak Sethi             deepak.sethi@prabhatprinting.net                               cmo@nic.in            odisha.gov.in
    ID-0015                            Mirdha Toppo                 Madhu Mohanty                 madhu.mohanty@rediffmail.com                               cmo@nic.in            odisha.gov.in
    ID-0015                            Mirdha Toppo                    Vivek Bose                       vivek.bose@nhai.gov.in                               cmo@nic.in            odisha.gov.in
    ID-0016                          Chitrasen Rout                  Prakash Iyer             prakash.iyer@aaravstationers.net                               cmo@nic.in            odisha.gov.in
    ID-0016                          Chitrasen Rout                   Farah Barik             farah.barik@meridianfacility.com                               cmo@nic.in            odisha.gov.in
    ID-0016                          Chitrasen Rout                Chitrasen Rout                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0016                          Chitrasen Rout                  Meera Pillai               meera.pillai@sagartransport.in                               cmo@nic.in            odisha.gov.in
    ID-0017                  Umesh Chandra Tripathy        Umesh Chandra Tripathy                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0017                  Umesh Chandra Tripathy                   Amit Sharma                      amit.sharma@hotmail.com                               cmo@nic.in            odisha.gov.in
    ID-0017                  Umesh Chandra Tripathy                Manish Trivedi                     manish.trivedi@yahoo.com                               cmo@nic.in            odisha.gov.in
    ID-0018                       Trilochan Mohanty             Trilochan Mohanty                                   cmo@nic.in                               cmo@nic.in            odisha.gov.in
    ID-0018                       Trilochan Mohanty                 Karan Chauhan                      karan.chauhan@yahoo.com                               cmo@nic.in            odisha.gov.in
    ID-0018                       Trilochan Mohanty                Yashwant Nayak                yashwant.nayak@bluepeak.co.in                               cmo@nic.in            odisha.gov.in
    ID-0019                      Pradip Kumar Samal            Pradip Kumar Samal                                cmo@od.gov.in                            cmo@od.gov.in            odisha.gov.in
    ID-0019                      Pradip Kumar Samal                 Harish Mishra                     harish.mishra@bsnl.co.in                            cmo@od.gov.in            odisha.gov.in
    ID-0019                      Pradip Kumar Samal                Imran Kulkarni             imran.kulkarni@sagartransport.in                            cmo@od.gov.in            odisha.gov.in
    ID-0019                      Pradip Kumar Samal                 Sandeep Singh             sandeep.singh@aaravstationers.in                            cmo@od.gov.in            odisha.gov.in
    ID-0020                           Hemant Sharma                 Hemant Sharma                         homesec.od@od.gov.in                     homesec.od@od.gov.in            odisha.gov.in
    ID-0020                           Hemant Sharma              Subrata Varghese                 subrata.varghese@hotmail.com                     homesec.od@od.gov.in            odisha.gov.in
    ID-0020                           Hemant Sharma                  Deepak Gupta                      deepak.gupta@iitd.ac.in                     homesec.od@od.gov.in            odisha.gov.in
    ID-0020                           Hemant Sharma                   Varun Swain                       varun.swain@cag.gov.in                     homesec.od@od.gov.in            odisha.gov.in
    ID-0021                        Pranati Chhotray                Yashwant Reddy               yashwant.reddy@ecolinewaste.in           pranati.chhotray@odisha.gov.in            odisha.gov.in
    ID-0021                        Pranati Chhotray                    Omkar Nair                         omkar.nair@yahoo.com           pranati.chhotray@odisha.gov.in            odisha.gov.in
    ID-0021                        Pranati Chhotray                    Meera Dash                      meera.dash@deloitte.com           pranati.chhotray@odisha.gov.in            odisha.gov.in
    ID-0022                        Samarendra Nayak                  Deepak Ghosh          deepak.ghosh@gangaconstructions.net           samarendra.nayak@odisha.gov.in            odisha.gov.in
    ID-0022                        Samarendra Nayak                Naveen Trivedi       naveen.trivedi@tridenthousekeeping.com           samarendra.nayak@odisha.gov.in            odisha.gov.in
    ID-0022                        Samarendra Nayak                  Anita Mishra                      anita.mishra@iimb.ac.in           samarendra.nayak@odisha.gov.in            odisha.gov.in
    ID-0022                        Samarendra Nayak                Ashirbad Malik                      ashirbad.malik@kpmg.com           samarendra.nayak@odisha.gov.in            odisha.gov.in
    ID-0023                        G. Jagdish Kumar                 Jyoti Mohanty                 jyoti.mohanty@protonmail.com            gjagadish.kumar@odisha.gov.in            odisha.gov.in
    ID-0023                        G. Jagdish Kumar                 Kavita Sharma           kavita.sharma@utkalelectricals.com            gjagadish.kumar@odisha.gov.in            odisha.gov.in
    ID-0024                      Amiya Kumar Udgata                 Jyoti Routray                   jyoti.routray@nimbusit.com          amiyakumar.udgata@odisha.gov.in            odisha.gov.in
    ID-0024                      Amiya Kumar Udgata                Itishree Singh        itishree.singh@utkalelectricals.co.in          amiyakumar.udgata@odisha.gov.in            odisha.gov.in
    ID-0024                      Amiya Kumar Udgata               Neha Chatterjee                   neha.chatterjee@bsnl.co.in          amiyakumar.udgata@odisha.gov.in            odisha.gov.in
    ID-0025                       Siba Prasad Panda             Lakshmi Deshpande     lakshmi.deshpande@kalingaengineering.com                 siba.panda@odisha.gov.in            odisha.gov.in
    ID-0025                       Siba Prasad Panda                Gaurav Khuntia                      gaurav.khuntia@yahoo.in                 siba.panda@odisha.gov.in            odisha.gov.in
    ID-0025                       Siba Prasad Panda                  Rekha Behera                  rekha.behera@protonmail.com                 siba.panda@odisha.gov.in            odisha.gov.in
    ID-0025                       Siba Prasad Panda                   Sanjay Pati          sanjay.pati@capstonelogistics.co.in                 siba.panda@odisha.gov.in            odisha.gov.in
    ID-0026                       Tarun Kumar Panda                      Usha Rao               usha.rao@aaravstationers.co.in           tarunkumar.panda@odisha.gov.in            odisha.gov.in
    ID-0026                       Tarun Kumar Panda                Geeta Tripathy           geeta.tripathy@skylinenetworks.com           tarunkumar.panda@odisha.gov.in            odisha.gov.in
    ID-0026                       Tarun Kumar Panda                 Bijaya Behera            bijaya.behera@anvilfabrication.in           tarunkumar.panda@odisha.gov.in            odisha.gov.in
    ID-0027                     Pradip Kumar Behera                     Jyoti Roy                        jyoti.roy@infosys.com         pradipkumar.behera@odisha.gov.in            odisha.gov.in
    ID-0027                     Pradip Kumar Behera                Sasmita Parida                  sasmita.parida@hdfcbank.com         pradipkumar.behera@odisha.gov.in            odisha.gov.in
    ID-0027                     Pradip Kumar Behera                    Gaurav Roy                         gaurav.roy@yahoo.com         pradipkumar.behera@odisha.gov.in            odisha.gov.in
    ID-0027                     Pradip Kumar Behera               Bijaya Varghese         bijaya.varghese@zenithsecurity.co.in         pradipkumar.behera@odisha.gov.in            odisha.gov.in
    ID-0028                         Ratikanta Panda                    Amit Singh                         amit.singh@sbi.co.in            ratikanta.panda@odisha.gov.in            odisha.gov.in
    ID-0028                         Ratikanta Panda                   Priya Gupta                          priya.gupta@tcs.com            ratikanta.panda@odisha.gov.in            odisha.gov.in
    ID-0029                        Suryanarayan Kar                 Nandini Malik           nandini.malik@sunriseinfratech.com           suryanarayan.kar@odisha.gov.in            odisha.gov.in
    ID-0029                        Suryanarayan Kar                  Ananya Malik                 ananya.malik@induscabling.in           suryanarayan.kar@odisha.gov.in            odisha.gov.in
    ID-0030                         Rajkishore Rout                  Priya Mishra          priya.mishra@gangaconstructions.net            rajkishore.rout@odisha.gov.in            odisha.gov.in

In [72]:
# CHECK 22A — Validate self-sender records in LEGITIMATE messages

legit = df2[df2["label"].str.upper() == "LEGITIMATE"].copy()

# Normalize names for comparison
legit["sender_name_clean"] = (
    legit["sender_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

legit["identity_name_clean"] = (
    legit["identity_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Records where sender is the identity itself
self_sender = legit[
    legit["sender_name_clean"] == legit["identity_name_clean"]
].copy()

# Dataset 1 authoritative email/domain
self_sender["expected_email"] = self_sender["identity_id"].map(
    df1_map["official_email"]
)

self_sender["expected_domain"] = self_sender["identity_id"].map(
    df1_map["official_domain"]
)

# Normalize
self_sender["sender_email_clean"] = (
    self_sender["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

self_sender["expected_email_clean"] = (
    self_sender["expected_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

self_sender["sender_domain"] = (
    self_sender["sender_email_clean"]
    .str.split("@")
    .str[-1]
)

self_sender["expected_domain_clean"] = (
    self_sender["expected_domain"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Exact email mismatch
email_mismatch = (
    self_sender["sender_email_clean"]
    !=
    self_sender["expected_email_clean"]
)

# Domain mismatch
domain_mismatch = (
    self_sender["sender_domain"]
    !=
    self_sender["expected_domain_clean"]
)

print("LEGITIMATE self-sender records:", len(self_sender))
print("Self-sender official email mismatches:", email_mismatch.sum())
print("Self-sender official domain mismatches:", domain_mismatch.sum())

print("\nSelf-sender domain mismatches:")
print(
    self_sender.loc[
        domain_mismatch,
        [
            "identity_id",
            "identity_name",
            "sender_name",
            "sender_email",
            "expected_email",
            "expected_domain"
        ]
    ]
    .drop_duplicates()
    .to_string(index=False)
)

LEGITIMATE self-sender records: 1397
Self-sender official email mismatches: 0
Self-sender official domain mismatches: 169

Self-sender domain mismatches:
identity_id            identity_name              sender_name                sender_email              expected_email    expected_domain
    ID-0001       Mohan Charan Majhi       Mohan Charan Majhi                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0002            Hemant Sharma            Hemant Sharma            iprsec.or@nic.in            iprsec.or@nic.in      odisha.gov.in
    ID-0003 Anuj Kumar Das Pattanaik Anuj Kumar Das Pattanaik      director-ipr.od@gov.in      director-ipr.od@gov.in      odisha.gov.in
    ID-0004        Pruthwee Raj Pani        Pruthwee Raj Pani   pruthweeraj1970@gmail.com   pruthweeraj1970@gmail.com      odisha.gov.in
    ID-0005    Parthasarathi Mallick    Parthasarathi Mallick              rti-ori@nic.in              rti-ori@nic.in      odisha.gov.in
    ID-0006     Sanjeeb Kumar Mishra     Sanjeeb Kumar Mishra            finsec.or@nic.in            finsec.or@nic.in      odisha.gov.in
    ID-0007           Yamini Sarangi           Yamini Sarangi       yamini.sarangi@nic.in       yamini.sarangi@nic.in      odisha.gov.in
    ID-0008          Satyapriya Rath          Satyapriya Rath            finsec.or@nic.in            finsec.or@nic.in      odisha.gov.in
    ID-0009 Krushna Chandra Satpathy Krushna Chandra Satpathy            finsec.or@nic.in            finsec.or@nic.in      odisha.gov.in
    ID-0010           Saumyajit Rout           Saumyajit Rout    saumyajit.rout@gmail.com    saumyajit.rout@gmail.com      odisha.gov.in
    ID-0011           Saswata Mishra           Saswata Mishra                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0012        Manoj Kumar Sahoo        Manoj Kumar Sahoo                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0013              Anupam Saha              Anupam Saha                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0014   Prasanna Kumar Sarangi   Prasanna Kumar Sarangi                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0016           Chitrasen Rout           Chitrasen Rout                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0017   Umesh Chandra Tripathy   Umesh Chandra Tripathy                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0018        Trilochan Mohanty        Trilochan Mohanty                  cmo@nic.in                  cmo@nic.in      odisha.gov.in
    ID-0019       Pradip Kumar Samal       Pradip Kumar Samal               cmo@od.gov.in               cmo@od.gov.in      odisha.gov.in
    ID-0020            Hemant Sharma            Hemant Sharma        homesec.od@od.gov.in        homesec.od@od.gov.in      odisha.gov.in
    ID-0061            Ashok Chandra            Ashok Chandra              mdps@pnb.co.in              mdps@pnb.co.in        pnbindia.in
    ID-0062             Kalyan Kumar             Kalyan Kumar              hosd@pnb.co.in              hosd@pnb.co.in        pnbindia.in
    ID-0063           M. Paramasivam           M. Paramasivam              hosd@pnb.co.in              hosd@pnb.co.in        pnbindia.in
    ID-0064   Bibhu Prasad Mahapatra   Bibhu Prasad Mahapatra              hosd@pnb.co.in              hosd@pnb.co.in        pnbindia.in
    ID-0065             D. Surendran             D. Surendran              hosd@pnb.co.in              hosd@pnb.co.in        pnbindia.in
    ID-0081     Ashish Kumar Bhutani     Ashish Kumar Bhutani            secy-coop@gov.in            secy-coop@gov.in cooperation.gov.in
    ID-0082      Pankaj Kumar Bansal      Pankaj Kumar Bansal           as.cd-coop@gov.in           as.cd-coop@gov.in cooperation.gov.in
    ID-0083              Raman Kumar              Raman Kumar           js.cd-coop@gov.in           js.cd-coop@gov.in cooperation.gov.in
    ID-0084                S Sathiya                S Sathiya         director-cd1@gov.in         director-cd1@gov.in cooperation.gov.in
    ID-0085               Amit Kumar               Amit Kumar              dir-ctp@gov.in              dir-ctp@gov.in cooperation.gov.in
    ID-0086              Vipin Singh              Vipin Singh        dd.media-coop@gov.in        dd.media-coop@gov.in cooperation.gov.in
    ID-0087              Afsar Ahmed              Afsar Ahmed           dirol-coop@gov.in           dirol-coop@gov.in cooperation.gov.in
    ID-0088     Devendra Kumar Singh     Devendra Kumar Singh  chairperson-coop.ea@gov.in  chairperson-coop.ea@gov.in cooperation.gov.in
    ID-0089             Ravneet Kaur             Ravneet Kaur         cci-chairman@nic.in         cci-chairman@nic.in         cci.gov.in
    ID-0121        Bishnupriya Sahoo        Bishnupriya Sahoo           coopsec.or@nic.in           coopsec.or@nic.in      odisha.gov.in
    ID-0134    Chinmayee Chetna Dash    Chinmayee Chetna Dash            dstsec.od@nic.in            dstsec.od@nic.in      odisha.gov.in
    ID-0202             Supriya Jena             Supriya Jena             orhealth@nic.in             orhealth@nic.in      odisha.gov.in
    ID-0213         Rudra N. Acharya         Rudra N. Acharya          workssec.od@nic.in          workssec.od@nic.in      odisha.gov.in
    ID-0218       Amiya Ranjan Nayak       Amiya Ranjan Nayak          workssec.od@nic.in          workssec.od@nic.in      odisha.gov.in
    ID-0227        Amit Prasana Kiro        Amit Prasana Kiro          workssec.od@nic.in          workssec.od@nic.in      odisha.gov.in
    ID-0230        Sailabala Pradhan        Sailabala Pradhan          workssec.od@nic.in          workssec.od@nic.in      odisha.gov.in
    ID-0231             Sunil Tiwari             Sunil Tiwari          workssec.od@nic.in          workssec.od@nic.in      odisha.gov.in
    ID-0248     Miss Usharani Behera     Miss Usharani Behera          workssec.od@nic.in          workssec.od@nic.in      odisha.gov.in
    ID-0254    Kailash Chandra Nayak    Kailash Chandra Nayak             orhealth@nic.in             orhealth@nic.in      odisha.gov.in
    ID-0489          V. Ramgopal Rao          V. Ramgopal Rao vc@pilani.bits-pilani.ac.in vc@pilani.bits-pilani.ac.in  bits-pilani.ac.in

In [73]:
# CHECK 22B — Find self-sender emails that are NOT the Dataset 1 official email

# Use the self_sender dataframe created in Check 22A

# Only records where sender email differs from Dataset 1 official email
suspicious_self_email = self_sender[
    self_sender["sender_email_clean"] != self_sender["expected_email_clean"]
].copy()

print("Self-sender records:", len(self_sender))
print(
    "Self-sender records with email different from Dataset 1:",
    len(suspicious_self_email)
)

print("\nUnique identity/email combinations:")
print(
    suspicious_self_email[
        [
            "identity_id",
            "identity_name",
            "sender_name",
            "sender_email",
            "expected_email",
            "expected_domain"
        ]
    ]
    .drop_duplicates()
    .to_string(index=False)
)

Self-sender records: 1397
Self-sender records with email different from Dataset 1: 0

Unique identity/email combinations:
Empty DataFrame
Columns: [identity_id, identity_name, sender_name, sender_email, expected_email, expected_domain]
Index: []

In [74]:
# CHECK 23 — LEGITIMATE SELF-SENDER NAME CONSISTENCY

legit = df2[
    df2["label"].astype(str).str.upper() == "LEGITIMATE"
].copy()

# Normalize names
legit["sender_name_clean"] = (
    legit["sender_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

legit["identity_name_clean"] = (
    legit["identity_name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Only self-sender records
self_sender = legit[
    legit["sender_name_clean"] == legit["identity_name_clean"]
].copy()

print("LEGITIMATE self-sender records:", len(self_sender))

# Check all legitimate records where sender appears to be the identity
# based on the sender email matching Dataset 1 official email
self_email_map = df1.set_index("identity_id")["official_email"].str.lower()

legit["expected_email"] = (
    legit["identity_id"].map(self_email_map)
)

legit["sender_email_clean"] = (
    legit["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
)

email_self = legit[
    legit["sender_email_clean"] == legit["expected_email"]
].copy()

name_mismatch = (
    email_self["sender_name"].astype(str).str.strip().str.lower()
    !=
    email_self["identity_name"].astype(str).str.strip().str.lower()
)

print("Records using Dataset 1 official email:", len(email_self))
print("Official-email self-sender name mismatches:", name_mismatch.sum())

if name_mismatch.sum() > 0:
    print("\nPotential name mismatches:")
    print(
        email_self.loc[
            name_mismatch,
            [
                "identity_id",
                "identity_name",
                "sender_name",
                "sender_email"
            ]
        ]
        .drop_duplicates()
        .to_string(index=False)
    )
else:
    print("\nPASS — Legitimate self-sender names are consistent.")

LEGITIMATE self-sender records: 1397
Records using Dataset 1 official email: 1990
Official-email self-sender name mismatches: 593

Potential name mismatches:
identity_id                           identity_name                      sender_name                            sender_email
    ID-0101                     Sri Raghunandan Das                  Raghunandan Das                         wrsec.od@nic.in
    ID-0102              Dr. Mrinalini Darswal, IAS                Mrinalini Darswal                     wcdsec.or@od.gov.in
    ID-0103                 Ms. Rashmita Panda, IAS                   Rashmita Panda                  secy-msme.od@od.gov.in
    ID-0104              Dr. N. Thirumala Naik, IAS                N. Thirumala Naik                  Secretarysme.od@nic.in
    ID-0105                Dr. Nivedita Prusty, IAS                  Nivedita Prusty                 hthdepartment@gmail.com
    ID-0106               Smt Chinmayee Biswal, OAS                 Chinmayee Biswal                 hthdepartment@gmail.com
    ID-0107           Dr. Pabitra Mohan Samal, OSJS        Pabitra Mohan Samal, OSJS                        lawsec.or@nic.in
    ID-0108    Shri Rajesh Kumar Agarwala, OAS(SAG)            Rajesh Kumar Agarwala                        labsec.od@nic.in
    ID-0109            Sri Pratap Chandra Hota, IAS              Pratap Chandra Hota                   mail.pchota@gmail.com
    ID-0110                      Smt. Urmila Kanhar                    Urmila Kanhar                         ctsec.od@nic.in
    ID-0111                    Shri Biswombar Sethi                  Biswombar Sethi                         ctsec.od@nic.in
    ID-0112  Shri Saroj Kanta Mohanty, O.A.S. (SAG)    Saroj Kanta Mohanty, O.A.S. (                        indsec.or@nic.in
    ID-0113                     Smt. Sarita Dhanwar                   Sarita Dhanwar                        agrsec.or@nic.in
    ID-0114                    Shri Sabyasachi Hota                  Sabyasachi Hota                  sabyasachi.hota@gov.in
    ID-0115            Smt. Sonia Behera, OAS (SAG)                     Sonia Behera                   ssepdodisha@gmail.com
    ID-0116                     Sri Gangadhar Nayak                  Gangadhar Nayak                        hudsec.or@nic.in
    ID-0117              Smt. Nirmala Kumari Biswal            Nirmala Kumari Biswal                         ctsec.od@nic.in
    ID-0118                   Smt Mamata Samantaroy                Mamata Samantaroy                 hthdepartment@gmail.com
    ID-0119                 Smt. Urmiprava Maharana               Urmiprava Maharana                        dstsec.od@nic.in
    ID-0120                   Mr. Binaya Kumar Dash                Binaya Kumar Dash                  dashbinaya45@gmail.com
    ID-0122                       Smt. Smita Biswal                     Smita Biswal                         orhealth@nic.in
    ID-0123                    Sri Gaurahari Behera                 Gaurahari Behera                         orhealth@nic.in
    ID-0124            Shri Lalit Kumar Kanhar, OAS               Lalit Kumar Kanhar                          etet.od@nic.in
    ID-0125                   Shri Manoranjan Panda                 Manoranjan Panda                        dsmsec.od@nic.in
    ID-0126                    Shri Shaktikanta Ray                  Shaktikanta Ray             itpmu@orissaminerals.gov.in
    ID-0127                        Sri Dillip Sahoo                     Dillip Sahoo        mo.cuttack@orissaminerals.gov.in
    ID-0128            Smt. Soojata Misra, OAS (SS)                    Soojata Misra                       stscdev@gmail.com
    ID-0129                  Sri Manas Ranjan Patra               Manas Ranjan Patra                 hthdepartment@gmail.com
    ID-0130                  Puspanjali Bisoi (OSS)               Puspanjali Bisoi (                        dpesec.od@nic.in
    ID-0131   Shri Durgaprasad Mohapatra, OAS (SAG)            Durgaprasad Mohapatra                  Secretarysme.od@nic.in
    ID-0132                     Shri Narottam Sahoo                   Narottam Sahoo                        dsmsec.od@nic.in
    ID-0133                    Rajat Kumar Kar, ADG                  Rajat Kumar Kar                        dsmsec.od@nic.in
    ID-0135          Sri Probodh Kumar Dwibedy, OSS            Probodh Kumar Dwibedy                  excisesec.or@od.gov.in
    ID-0136                 Sri Parakhita Bhoi, OSS                   Parakhita Bhoi                  excisesec.or@od.gov.in
    ID-0137              Smt. Banita Dash, OFS(SAG)                      Banita Dash                       stscdev@gmail.com
    ID-0138   Shri Shailendra Narayan Nayak, O.I.S. Shailendra Narayan Nayak, O.I.S.          shailendra.nayak@odisha.gov.in
    ID-0139                   Smt. Rashmi Kabi, OFS                      Rashmi Kabi                  giapncodisha@gmail.com
    ID-0140               Sri Bijaya Kumar Mangaraj            Bijaya Kumar Mangaraj                        finsec.or@nic.in
    ID-0141               Dr. Jagadish Sarangi, OAS                 Jagadish Sarangi                    tourismsec.od@nic.in
    ID-0142               Shri Dharmendra Satapathy             Dharmendra Satapathy                         ctsec.od@nic.in
    ID-0143             Shri Bhaskar Raito OAS(SAG)                    Bhaskar Raito                   ssepdodisha@gmail.com
    ID-0144            Sri Daridryabhanjan MM Patra         Daridryabhanjan MM Patra                     dbmmpatra@gmail.com
    ID-0145                Sri Amit Kumar Nayak,OAS                 Amit Kumar Nayak                    sportsysec.od@nic.in
    ID-0146                Sri Krutibash Routh, OAS                  Krutibash Routh                     wcdsec.or@od.gov.in
    ID-0147                     Smt. Soumitri Nayak                   Soumitri Nayak                        labsec.od@nic.in
    ID-0148                      Sri Umakanta Barik                   Umakanta Barik                         ctsec.od@nic.in
    ID-0149            Shri Rama Chandra Kisku, OAS               Rama Chandra Kisku                 dsm.edespatch@od.gov.in
    ID-0150                    Sri Abhijeet Routray                 Abhijeet Routray                 hthdepartment@gmail.com
    ID-0151                      Sri Anshuman Nayak                   Anshuman Nayak                 hthdepartment@gmail.com
    ID-0152 Smt. Sumitra Kumari Pattnaik, OAS (SAG)          Sumitra Kumari Pattnaik                     wcdsec.or@od.gov.in
    ID-0153                   Sri Bimbadhar Pradhan                Bimbadhar Pradhan         bimbadhar.pradhan@odisha.gov.in
    ID-0154         Sri Bibekananda Sahoo, OAS(SAG)                Bibekananda Sahoo                     wcdsec.or@od.gov.in
    ID-0155                 Shri Santosh Kumar Suar               Santosh Kumar Suar                        finsec.od@nic.in
    ID-0156             Shri Daulat Chandrakar, OAS                Daulat Chandrakar                        dsmsec.od@nic.in
    ID-0157             Sri Sibashis Dhal, OFS (SS)                    Sibashis Dhal                  Secretarysme.od@nic.in
    ID-0158                Shri Niranjana Jena, OAS                   Niranjana Jena                        labsec.od@nic.in
    ID-0159          Shri Sudhakar Nayak, OAS (SAG)                   Sudhakar Nayak                    sportsysec.od@nic.in
    ID-0160                  Shri Manoj Behera, OAS                     Manoj Behera                    tourismsec.od@nic.in
    ID-0161                Shri Chandrapati Pradhan              Chandrapati Pradhan                  secy-msme.od@od.gov.in
    ID-0162              Sri Laxmikanta Mishra, OSS                Laxmikanta Mishra                        energy@od.gov.in
    ID-0163          Sri Smruti Ranjan Pradhan, IAS            Smruti Ranjan Pradhan                      fesec.or@od.gov.in
    ID-0164      Sri Subhananda Mohapatra, OAS(SAG)             Subhananda Mohapatra                        hudsec.or@nic.in
    ID-0165            Shri Nelson Lakra, OFS (SAG)                     Nelson Lakra                    sportsysec.od@nic.in
    ID-0166            Shri Ghasiram Murmu, OAS(SS)                   Ghasiram Murmu                        gadmin.or@nic.in
    ID-0167                  Sri Shubhranshu Mishra               Shubhranshu Mishra          addl.secretarypolicy@gmail.com
    ID-0168         Sri Siba Prasad Mohapatra, OSJS      Siba Prasad Mohapatra, OSJS                        lawsec.or@nic.in
    ID-0169              Shri Manoranjan Samantaray            Manoranjan Samantaray                        labsec.od@nic.in
    ID-0170          Sri Deba Prasad Dash, OAS (SS)                 Deba Prasad Dash specialsecretarycultureodisha@gmail.com
    ID-0171           Dr. Monica Priyadarshini, IAS             Monica Priyadarshini                         prsec.od@nic.in
    ID-0172                  Sri Amar Kumar Pradhan               Amar Kumar Pradhan                         ctsec.od@nic.in
    ID-0173        Sri Siddharth Shankar Swain, IAS          Siddharth Shankar Swain                    directorsp.od@gov.in
    ID-0174           Shri Balaram Mallik, OAS(SAG)                   Balaram Mallik                       fardsec.od@nic.in
    ID-0175         Shri Sukanta Kumar Pradhan, OAS            Sukanta Kumar Pradhan                     sdte.addl@gmail.com
    ID-0176               Shri Gobinda Ch. Samantra             Gobinda Ch. Samantra                        dsmsec.od@nic.in
    ID-0177                   Shri Ganapati Pradhan                 Ganapati Pradhan                        dsmsec.od@nic.in
    ID-0178                       Shri Salil Behera                     Salil Behera                        dsmsec.od@nic.in
    ID-0179                  Shri Pradip Kumar Naik                Pradip Kumar Naik                        dsmsec.od@nic.in
    ID-0180                  Dr. Yeddula Vijay, IAS                    Yeddula Vijay                    sportsysec.od@nic.in
    ID-0181                  Smt. Bidyut Prava Rout                Bidyut Prava Rout                        dstsec.od@nic.in
    ID-0182             Smt. Madhusmita Behera, OFS                Madhusmita Behera          madhusmitabehera0711@gmail.com
    ID-0183                  Sri Arindam Dakua, IAS                    Arindam Dakua                       dmahudd@gmail.com
    ID-0184                 Smt. Lipsa Das, OAS(SS)                        Lipsa Das                lipsa.das2@odisha.gov.in
    ID-0185                       Sri Lingaraj Otta                    Lingaraj Otta             lingaraj.otta@odisha.gov.in
    ID-0186       Shri Ashok Kumar Panda, OAS (SAG)                Ashok Kumar Panda                        labsec.od@nic.in
    ID-0187       Shri Laxman Kumar Mallick, I.A.S.     Laxman Kumar Mallick, I.A.S.                        welsec.od@nic.in
    ID-0188            Dr. Debi Dutta Tripathy, OFS              Debi Dutta Tripathy                        energy@od.gov.in
    ID-0189               Shri Indramani Nayak, IAS                  Indramani Nayak                         prsec.od@nic.in
    ID-0190         Shri Debashis Patnaik, OAS(SAG)                 Debashis Patnaik                  excisesec.or@od.gov.in
    ID-0191                Ms. Rajani Jani, OAS(SS)                      Rajani Jani               rajani.jani@odisha.gov.in
    ID-0192           Shri Susanta Kumar Singh, OAS              Susanta Kumar Singh                        dpesec.od@nic.in
    ID-0193                       Sri Ganeswar Jena                    Ganeswar Jena                 ganeswarjena2@gmail.com
    ID-0194             Sri Trilochan Patra, OAS(S)                  Trilochan Patra                  excisesec.or@od.gov.in
    ID-0195             Sri Saroja Kumar Swain, OAS               Saroja Kumar Swain               info@odishatourism.gov.in
    ID-0196             Shri Kina Charan Soren, OSS                Kina Charan Soren                         pasec.od@nic.in
    ID-0197                      Shri Bhagala Sirka                    Bhagala Sirka                  secy-msme.od@od.gov.in
    ID-0198              Sri Pradyumna Kumar Muduli           Pradyumna Kumar Muduli                         ctsec.od@nic.in
    ID-0199            Sri Subrat Kumar Behera, OAS              Subrat Kumar Behera                 hthdepartment@gmail.com
    ID-0200                       Sri Sunaram Murmu                    Sunaram Murmu                        dstsec.od@nic.in
    ID-0201          Shri Manoj Kumar Padhy,OAS(SS)                Manoj Kumar Padhy                  Secretarysme.od@nic.in
    ID-0203                 Sri Nilamani Nayak, OSS                   Nilamani Nayak                 hthdepartment@gmail.com
    ID-0204                   Sri Saroj Kumar Sahoo                Saroj Kumar Sahoo                    sksahoo667@gmail.com
    ID-0205                       Smt. Lipsa Prusty                     Lipsa Prusty             itpmu@orissaminerals.gov.in
    ID-0206               Shri Jitendra Kumar Panda             Jitendra Kumar Panda       mo.baripada@orissaminerals.gov.in
    ID-0207    Smt. Shanti Sudha Kanungo, OFS (SAG)             Shanti Sudha Kanungo                         itsec.od@nic.in
    ID-0208               Sri Biswajit Routray, OTS            Biswajit Routray, OTS         ad.tourism@odishatourism.gov.in
    ID-0209                    Er. Ratikanta Behera                 Ratikanta Behera                      workssec.od@nic.in
    ID-0210               Er. Kshiradhar Kandhapani            Kshiradhar Kandhapani                       eenhjpr.od@gov.in
    ID-0211                         Er. D.P. Mishra                      D.P. Mishra                      workssec.od@nic.in
    ID-0212                       Er. Gayatri Patel                    Gayatri Patel                  gayatriuce@yahoo.co.in
    ID-0214                      Shri Debashis Rout                    Debashis Rout                      workssec.od@nic.in
    ID-0215                     Er. Tara Pr. Mishra                  Tara Pr. Mishra                      ceroads.owd@gov.in
    ID-0216                   Er. Rama Kr. Moharana                Rama Kr. Moharana                        cewbp.owd@gov.in
    ID-0217                          Er. Goutam Pal                       Goutam Pal                      workssec.od@nic.in
    ID-0219                          Er. Pravat Das                       Pravat Das                      workssec.od@nic.in
    ID-0220                    Er. Lokanatha Mishra                 Lokanatha Mishra                      workssec.od@nic.in
    ID-0221                       Er. Prafulla Naik                    Prafulla Naik                      workssec.od@nic.in
    ID-0222              Er. Subhransu Sekhar Swain           Subhransu Sekhar Swain                     ssswain@pmuosrp.org
    ID-0223                      Er. Pravat Ku. Das                   Pravat Ku. Das                      workssec.od@nic.in
    ID-0224                 Er. Sudhi Ranjan Mishra              Sudhi Ranjan Mishra                  eepwdboudha.owd@gov.in
    ID-0225                           Er B.K. Lenka                       B.K. Lenka                      workssec.od@nic.in
    ID-0226                    Er. Niroj Kumar Dash                 Niroj Kumar Dash                      workssec.od@nic.in
    ID-0228                       Shri Dipak R. Das                     Dipak R. Das                      workssec.od@nic.in
    ID-0229                    Shri Mahadev Badhaik                  Mahadev Badhaik                      workssec.od@nic.in
    ID-0232                     Shri Jayadev Mishra                   Jayadev Mishra                      workssec.od@nic.in
    ID-0233                       Er. Gouranga Sahu                    Gouranga Sahu                  cebuildings.owd@gov.in
    ID-0235                        Er. S.N. Acharya                     S.N. Acharya                      workssec.od@nic.in
    ID-0236                        Er. Ajit Ku. Ray                     Ajit Ku. Ray                      workssec.od@nic.in
    ID-0237                   Er. Akshaya Ku. Sahoo                Akshaya Ku. Sahoo                      workssec.od@nic.in
    ID-0238                   Er. Bijay Kumar Nayak                Bijay Kumar Nayak                      workssec.od@nic.in
    ID-0239                 Dr. Narayan Chandra Pal              Narayan Chandra Pal                    cedesigns.owd@gov.in
    ID-0241                      Er. Narmada Behera                   Narmada Behera                      workssec.od@nic.in
    ID-0242                     Er. Pasant Tripathy                  Pasant Tripathy                      workssec.od@nic.in
    ID-0243                      Er. Mahendra Samal                   Mahendra Samal                      workssec.od@nic.in
    ID-0244                      Er. Niranjan Padhi                   Niranjan Padhi                      workssec.od@nic.in
    ID-0245                Er. Pradip Kumar Subudhi             Pradip Kumar Subudhi                      workssec.od@nic.in
    ID-0246               Er. Chandrama Bhusan Dash            Chandrama Bhusan Dash                      workssec.od@nic.in
    ID-0249                  Sri Devi Prasad Mishra               Devi Prasad Mishra                      workssec.od@nic.in
    ID-0250                    Er. Binod Bihari Das                 Binod Bihari Das                       eenhsbp.od@gov.in
    ID-0251                      Er. Satyaban Patel                   Satyaban Patel                       eenhjsg@gmail.com
    ID-0252          Er. Archana Das Pattanaik, IAS            Archana Das Pattanaik                       archana.dp@gov.in
    ID-0253          Shri Niti Ranjan Sen, OAS(SAG)                  Niti Ranjan Sen                        labsec.od@nic.in
    ID-0255                       Dr Usharani Sahoo                   Usharani Sahoo                         orhealth@nic.in
    ID-0256           Dr. Arun Kumar Sahoo, O.S.J.S        Arun Kumar Sahoo, O.S.J.S                        lawsec.or@nic.in
    ID-0257              Shri Narayan Chandra Nayak            Narayan Chandra Nayak                  secy-msme.od@od.gov.in
    ID-0258                   Smt Mamata Nayak, OAS                     Mamata Nayak                 hthdepartment@gmail.com
    ID-0259            Shri Bijay Kumar Prusty, IAS               Bijay Kumar Prusty                        gadmin.or@nic.in
    ID-0260             Sri Rudra Narayan Dash, OAS               Rudra Narayan Dash                    tourismsec.od@nic.in
    ID-0261                       Smt. Usharani Das                     Usharani Das              usharani.das@odisha.gov.in
    ID-0262          Shri Girish Chandra Singh, IAS             Girish Chandra Singh                  Secretarysme.od@nic.in
    ID-0263                Sri Surendra Kumar Sahoo             Surendra Kumar Sahoo                       coopsec.or@nic.in

In [75]:
# CHECK 23A — NORMALIZED SELF-SENDER NAME CONSISTENCY

import re

def normalize_person_name(name):
    name = str(name).strip().lower()

    # Remove common honorifics/titles
    titles = [
        "dr", "mr", "mrs", "ms", "smt", "shri", "sri",
        "prof", "professor"
    ]

    for title in titles:
        name = re.sub(rf"\b{title}\.?\b", " ", name)

    # Remove common professional/designation suffixes
    suffixes = [
        "ias", "ips", "ifs", "oas", "osjs", "irs",
        "o a s", "o.a.s", "o.a.s.", "sag", "osd"
    ]

    for suffix in suffixes:
        name = re.sub(rf"\b{re.escape(suffix)}\b", " ", name)

    # Remove punctuation
    name = re.sub(r"[^a-z0-9\s]", " ", name)

    # Normalize spaces
    name = re.sub(r"\s+", " ", name).strip()

    return name


# Official-email records
email_self["identity_name_normalized"] = (
    email_self["identity_name"].apply(normalize_person_name)
)

email_self["sender_name_normalized"] = (
    email_self["sender_name"].apply(normalize_person_name)
)

# Compare normalized names
normalized_name_mismatch = (
    email_self["identity_name_normalized"]
    !=
    email_self["sender_name_normalized"]
)

print("Official-email self-sender records:", len(email_self))
print(
    "Normalized name mismatches:",
    normalized_name_mismatch.sum()
)

if normalized_name_mismatch.sum() > 0:
    print("\nPotential genuine name mismatches:")
    print(
        email_self.loc[
            normalized_name_mismatch,
            [
                "identity_id",
                "identity_name",
                "sender_name",
                "sender_email",
                "identity_name_normalized",
                "sender_name_normalized"
            ]
        ]
        .drop_duplicates()
        .to_string(index=False)
    )
else:
    print("\nPASS — Names match after removing titles/designations.")

Official-email self-sender records: 1990
Normalized name mismatches: 206

Potential genuine name mismatches:
identity_id                        identity_name            sender_name                            sender_email  identity_name_normalized sender_name_normalized
    ID-0128         Smt. Soojata Misra, OAS (SS)          Soojata Misra                       stscdev@gmail.com          soojata misra ss          soojata misra
    ID-0130               Puspanjali Bisoi (OSS)     Puspanjali Bisoi (                        dpesec.od@nic.in      puspanjali bisoi oss       puspanjali bisoi
    ID-0133                 Rajat Kumar Kar, ADG        Rajat Kumar Kar                        dsmsec.od@nic.in       rajat kumar kar adg        rajat kumar kar
    ID-0135       Sri Probodh Kumar Dwibedy, OSS  Probodh Kumar Dwibedy                  excisesec.or@od.gov.in probodh kumar dwibedy oss  probodh kumar dwibedy
    ID-0136              Sri Parakhita Bhoi, OSS         Parakhita Bhoi                  excisesec.or@od.gov.in        parakhita bhoi oss         parakhita bhoi
    ID-0137           Smt. Banita Dash, OFS(SAG)            Banita Dash                       stscdev@gmail.com           banita dash ofs            banita dash
    ID-0139                Smt. Rashmi Kabi, OFS            Rashmi Kabi                  giapncodisha@gmail.com           rashmi kabi ofs            rashmi kabi
    ID-0157          Sri Sibashis Dhal, OFS (SS)          Sibashis Dhal                  Secretarysme.od@nic.in      sibashis dhal ofs ss          sibashis dhal
    ID-0162           Sri Laxmikanta Mishra, OSS      Laxmikanta Mishra                        energy@od.gov.in     laxmikanta mishra oss      laxmikanta mishra
    ID-0165         Shri Nelson Lakra, OFS (SAG)           Nelson Lakra                    sportsysec.od@nic.in          nelson lakra ofs           nelson lakra
    ID-0166         Shri Ghasiram Murmu, OAS(SS)         Ghasiram Murmu                        gadmin.or@nic.in         ghasiram murmu ss         ghasiram murmu
    ID-0170       Sri Deba Prasad Dash, OAS (SS)       Deba Prasad Dash specialsecretarycultureodisha@gmail.com       deba prasad dash ss       deba prasad dash
    ID-0182          Smt. Madhusmita Behera, OFS      Madhusmita Behera          madhusmitabehera0711@gmail.com     madhusmita behera ofs      madhusmita behera
    ID-0184              Smt. Lipsa Das, OAS(SS)              Lipsa Das                lipsa.das2@odisha.gov.in              lipsa das ss              lipsa das
    ID-0188         Dr. Debi Dutta Tripathy, OFS    Debi Dutta Tripathy                        energy@od.gov.in   debi dutta tripathy ofs    debi dutta tripathy
    ID-0191             Ms. Rajani Jani, OAS(SS)            Rajani Jani               rajani.jani@odisha.gov.in            rajani jani ss            rajani jani
    ID-0194          Sri Trilochan Patra, OAS(S)        Trilochan Patra                  excisesec.or@od.gov.in         trilochan patra s        trilochan patra
    ID-0196          Shri Kina Charan Soren, OSS      Kina Charan Soren                         pasec.od@nic.in     kina charan soren oss      kina charan soren
    ID-0201       Shri Manoj Kumar Padhy,OAS(SS)      Manoj Kumar Padhy                  Secretarysme.od@nic.in      manoj kumar padhy ss      manoj kumar padhy
    ID-0203              Sri Nilamani Nayak, OSS         Nilamani Nayak                 hthdepartment@gmail.com        nilamani nayak oss         nilamani nayak
    ID-0207 Smt. Shanti Sudha Kanungo, OFS (SAG)   Shanti Sudha Kanungo                         itsec.od@nic.in  shanti sudha kanungo ofs   shanti sudha kanungo
    ID-0209                 Er. Ratikanta Behera       Ratikanta Behera                      workssec.od@nic.in       er ratikanta behera       ratikanta behera
    ID-0210            Er. Kshiradhar Kandhapani  Kshiradhar Kandhapani                       eenhjpr.od@gov.in  er kshiradhar kandhapani  kshiradhar kandhapani
    ID-0211                      Er. D.P. Mishra            D.P. Mishra                      workssec.od@nic.in             er d p mishra             d p mishra
    ID-0212                    Er. Gayatri Patel          Gayatri Patel                  gayatriuce@yahoo.co.in          er gayatri patel          gayatri patel
    ID-0215                  Er. Tara Pr. Mishra        Tara Pr. Mishra                      ceroads.owd@gov.in         er tara pr mishra         tara pr mishra
    ID-0216                Er. Rama Kr. Moharana      Rama Kr. Moharana                        cewbp.owd@gov.in       er rama kr moharana       rama kr moharana
    ID-0217                       Er. Goutam Pal             Goutam Pal                      workssec.od@nic.in             er goutam pal             goutam pal
    ID-0219                       Er. Pravat Das             Pravat Das                      workssec.od@nic.in             er pravat das             pravat das
    ID-0220                 Er. Lokanatha Mishra       Lokanatha Mishra                      workssec.od@nic.in       er lokanatha mishra       lokanatha mishra
    ID-0221                    Er. Prafulla Naik          Prafulla Naik                      workssec.od@nic.in          er prafulla naik          prafulla naik
    ID-0222           Er. Subhransu Sekhar Swain Subhransu Sekhar Swain                     ssswain@pmuosrp.org er subhransu sekhar swain subhransu sekhar swain
    ID-0223                   Er. Pravat Ku. Das         Pravat Ku. Das                      workssec.od@nic.in          er pravat ku das          pravat ku das
    ID-0224              Er. Sudhi Ranjan Mishra    Sudhi Ranjan Mishra                  eepwdboudha.owd@gov.in    er sudhi ranjan mishra    sudhi ranjan mishra
    ID-0225                        Er B.K. Lenka             B.K. Lenka                      workssec.od@nic.in              er b k lenka              b k lenka
    ID-0226                 Er. Niroj Kumar Dash       Niroj Kumar Dash                      workssec.od@nic.in       er niroj kumar dash       niroj kumar dash
    ID-0233                    Er. Gouranga Sahu          Gouranga Sahu                  cebuildings.owd@gov.in          er gouranga sahu          gouranga sahu
    ID-0235                     Er. S.N. Acharya           S.N. Acharya                      workssec.od@nic.in            er s n acharya            s n acharya
    ID-0236                     Er. Ajit Ku. Ray           Ajit Ku. Ray                      workssec.od@nic.in            er ajit ku ray            ajit ku ray
    ID-0237                Er. Akshaya Ku. Sahoo      Akshaya Ku. Sahoo                      workssec.od@nic.in       er akshaya ku sahoo       akshaya ku sahoo
    ID-0238                Er. Bijay Kumar Nayak      Bijay Kumar Nayak                      workssec.od@nic.in      er bijay kumar nayak      bijay kumar nayak
    ID-0241                   Er. Narmada Behera         Narmada Behera                      workssec.od@nic.in         er narmada behera         narmada behera
    ID-0242                  Er. Pasant Tripathy        Pasant Tripathy                      workssec.od@nic.in        er pasant tripathy        pasant tripathy
    ID-0243                   Er. Mahendra Samal         Mahendra Samal                      workssec.od@nic.in         er mahendra samal         mahendra samal
    ID-0244                   Er. Niranjan Padhi         Niranjan Padhi                      workssec.od@nic.in         er niranjan padhi         niranjan padhi
    ID-0245             Er. Pradip Kumar Subudhi   Pradip Kumar Subudhi                      workssec.od@nic.in   er pradip kumar subudhi   pradip kumar subudhi
    ID-0246            Er. Chandrama Bhusan Dash  Chandrama Bhusan Dash                      workssec.od@nic.in  er chandrama bhusan dash  chandrama bhusan dash
    ID-0250                 Er. Binod Bihari Das       Binod Bihari Das                       eenhsbp.od@gov.in       er binod bihari das       binod bihari das
    ID-0251                   Er. Satyaban Patel         Satyaban Patel                       eenhjsg@gmail.com         er satyaban patel         satyaban patel
    ID-0252       Er. Archana Das Pattanaik, IAS  Archana Das Pattanaik                       archana.dp@gov.in  er archana das pattanaik  archana das pattanaik

In [76]:
# CHECK 23B — IMPROVED NAME NORMALIZATION

def normalize_person_name_v2(name):
    name = str(name).strip().lower()

    # Remove anything inside parentheses
    name = re.sub(r"\([^)]*\)", " ", name)

    # Remove common titles/designations
    tokens_to_remove = [
        "dr", "mr", "mrs", "ms", "smt", "shri", "sri",
        "prof", "professor", "er",
        "ias", "ips", "ifs", "oas", "oss", "osjs",
        "ofs", "irs", "adg", "ss", "sag", "osd"
    ]

    for token in tokens_to_remove:
        name = re.sub(
            rf"\b{re.escape(token)}\.?\b",
            " ",
            name
        )

    # Remove punctuation
    name = re.sub(r"[^a-z0-9\s]", " ", name)

    # Normalize spaces
    name = re.sub(r"\s+", " ", name).strip()

    return name


email_self["identity_name_normalized_v2"] = (
    email_self["identity_name"].apply(normalize_person_name_v2)
)

email_self["sender_name_normalized_v2"] = (
    email_self["sender_name"].apply(normalize_person_name_v2)
)

name_mismatch_v2 = (
    email_self["identity_name_normalized_v2"]
    !=
    email_self["sender_name_normalized_v2"]
)

print("Official-email self-sender records:", len(email_self))
print("Remaining normalized name mismatches:", name_mismatch_v2.sum())

if name_mismatch_v2.sum() > 0:
    print("\nRemaining potential mismatches:")
    print(
        email_self.loc[
            name_mismatch_v2,
            [
                "identity_id",
                "identity_name",
                "sender_name",
                "sender_email",
                "identity_name_normalized_v2",
                "sender_name_normalized_v2"
            ]
        ]
        .drop_duplicates()
        .to_string(index=False)
    )
else:
    print("\nPASS — All official-email self-sender names match after normalization.")

Official-email self-sender records: 1990
Remaining normalized name mismatches: 0

PASS — All official-email self-sender names match after normalization.

In [77]:
# CHECK 24 — SENDER EMAIL STRUCTURE & NAME PRESENCE

# Check missing/blank sender fields
missing_sender_name = (
    df2["sender_name"].isna()
    | df2["sender_name"].astype(str).str.strip().eq("")
)

missing_sender_email = (
    df2["sender_email"].isna()
    | df2["sender_email"].astype(str).str.strip().eq("")
)

# Basic email structure
email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_sender_email = ~df2["sender_email"].astype(str).str.strip().str.match(
    email_pattern,
    na=False
)

print("Total records:", len(df2))
print("Missing/blank sender_name:", missing_sender_name.sum())
print("Missing/blank sender_email:", missing_sender_email.sum())
print("Malformed sender_email:", invalid_sender_email.sum())

if (
    missing_sender_name.sum() == 0
    and missing_sender_email.sum() == 0
    and invalid_sender_email.sum() == 0
):
    print("\nPASS — Sender fields are structurally valid.")
else:
    print("\nFAIL — Structural sender issues found.")

    print("\nProblematic records:")
    print(
        df2.loc[
            missing_sender_name
            | missing_sender_email
            | invalid_sender_email,
            [
                "message_id",
                "identity_id",
                "label",
                "sender_name",
                "sender_email"
            ]
        ]
        .head(50)
        .to_string(index=False)
    )

Total records: 10000
Missing/blank sender_name: 0
Missing/blank sender_email: 0
Malformed sender_email: 0

PASS — Sender fields are structurally valid.

In [78]:
# CHECK 25 — SENDER RELATIONSHIP CONSISTENCY

expected_relationships = {
    "LEGITIMATE": {
        "EXTERNAL_CONSULTANT_PERSONAL",
        "EXTERNAL_PARTNER",
        "EXTERNAL_VENDOR",
        "INTERNAL_COLLEAGUE",
        "INTERNAL_SHARED_MAILBOX",
        "SELF_OUTBOUND"
    },
    "IMPERSONATION": {
        "IMPERSONATES_IDENTITY",
        "IMPERSONATES_THIRD_PARTY"
    }
}

# Normalize
df2["_label_check"] = (
    df2["label"].astype(str).str.strip().str.upper()
)

df2["_relationship_check"] = (
    df2["sender_relationship"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Missing values
missing_relationship = (
    df2["sender_relationship"].isna()
    | df2["sender_relationship"].astype(str).str.strip().eq("")
)

# Unexpected relationship for the label
relationship_invalid = df2.apply(
    lambda row: row["_relationship_check"]
    not in expected_relationships.get(row["_label_check"], set()),
    axis=1
)

print("Missing sender_relationship:", missing_relationship.sum())
print("Invalid label/relationship combinations:", relationship_invalid.sum())

if missing_relationship.sum() == 0 and relationship_invalid.sum() == 0:
    print("\nPASS — Sender relationships are consistent with labels.")
else:
    print("\nFAIL — Sender relationship inconsistencies found.")

    print(
        df2.loc[
            missing_relationship | relationship_invalid,
            [
                "message_id",
                "identity_id",
                "label",
                "sender_name",
                "sender_email",
                "sender_relationship"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Missing sender_relationship: 0
Invalid label/relationship combinations: 0

PASS — Sender relationships are consistent with labels.

In [79]:
# CHECK 26 — ATTACK TYPE CONSISTENCY

valid_attack_types = {
    "ACCOUNT_CHANGE",
    "AUTHORITY_ABUSE",
    "CHANNEL_CHANGE",
    "CREDENTIAL_REQUEST",
    "DOCUMENT_REQUEST",
    "FINANCIAL_REQUEST",
    "SENSITIVE_DATA_REQUEST",
    "SOCIAL_ENGINEERING",
    "URGENT_REQUEST",
    "VENDOR_PAYMENT",
    "NONE"
}

# Normalize
df2["_label_check"] = (
    df2["label"].astype(str).str.strip().str.upper()
)

df2["_attack_type_check"] = (
    df2["attack_type"].astype(str).str.strip().str.upper()
)

# Missing
missing_attack_type = (
    df2["attack_type"].isna()
    | df2["attack_type"].astype(str).str.strip().eq("")
)

# Invalid category
invalid_attack_type = ~df2["_attack_type_check"].isin(
    valid_attack_types
)

# Legitimate must be NONE
legit_invalid = (
    (df2["_label_check"] == "LEGITIMATE")
    & (df2["_attack_type_check"] != "NONE")
)

# Impersonation must NOT be NONE
imp_invalid = (
    (df2["_label_check"] == "IMPERSONATION")
    & (df2["_attack_type_check"] == "NONE")
)

total_invalid = (
    missing_attack_type
    | invalid_attack_type
    | legit_invalid
    | imp_invalid
)

print("Missing attack_type:", missing_attack_type.sum())
print("Invalid attack_type values:", invalid_attack_type.sum())
print("LEGITIMATE records with non-NONE attack_type:", legit_invalid.sum())
print("IMPERSONATION records with NONE attack_type:", imp_invalid.sum())

print("\nTotal invalid records:", total_invalid.sum())

if total_invalid.sum() == 0:
    print("\nPASS — attack_type is consistent with label.")
else:
    print("\nFAIL — attack_type inconsistencies found.")
    
    print(
        df2.loc[
            total_invalid,
            [
                "message_id",
                "identity_id",
                "label",
                "attack_type"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Missing attack_type: 0
Invalid attack_type values: 0
LEGITIMATE records with non-NONE attack_type: 0
IMPERSONATION records with NONE attack_type: 0

Total invalid records: 0

PASS — attack_type is consistent with label.

In [80]:
# CHECK 27 — IMPERSONATION MECHANISM CONSISTENCY

valid_mechanisms = {
    "AUTHORITY_IMPERSONATION",
    "COMPROMISED_ACCOUNT",
    "COMPROMISED_COLLEAGUE",
    "DISPLAY_NAME_SPOOF",
    "EXECUTIVE_ASSISTANT_PROXY",
    "FAKE_ASSISTANT",
    "FAKE_DEPARTMENT",
    "FAKE_HELPDESK",
    "LOOKALIKE_DOMAIN",
    "REPLY_TO_DIVERT",
    "SUBDOMAIN_DECEPTION",
    "TYPO_DOMAIN",
    "VENDOR_SPOOF",
    "PARTNER_SPOOF",
    "NONE"
}

# Normalize
df2["_mechanism_check"] = (
    df2["impersonation_mechanism"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Missing
missing_mechanism = (
    df2["impersonation_mechanism"].isna()
    | df2["impersonation_mechanism"].astype(str).str.strip().eq("")
)

# Invalid values
invalid_mechanism = ~df2["_mechanism_check"].isin(
    valid_mechanisms
)

# LEGITIMATE must be NONE
legit_invalid = (
    (df2["_label_check"] == "LEGITIMATE")
    & (df2["_mechanism_check"] != "NONE")
)

# IMPERSONATION must not be NONE
imp_invalid = (
    (df2["_label_check"] == "IMPERSONATION")
    & (df2["_mechanism_check"] == "NONE")
)

total_invalid = (
    missing_mechanism
    | invalid_mechanism
    | legit_invalid
    | imp_invalid
)

print("Missing impersonation_mechanism:", missing_mechanism.sum())
print("Invalid mechanism values:", invalid_mechanism.sum())
print(
    "LEGITIMATE records with non-NONE mechanism:",
    legit_invalid.sum()
)
print(
    "IMPERSONATION records with NONE mechanism:",
    imp_invalid.sum()
)

print("\nTotal invalid records:", total_invalid.sum())

if total_invalid.sum() == 0:
    print("\nPASS — impersonation_mechanism is consistent with label.")
else:
    print("\nFAIL — mechanism inconsistencies found.")
    
    print(
        df2.loc[
            total_invalid,
            [
                "message_id",
                "identity_id",
                "label",
                "impersonation_mechanism"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Missing impersonation_mechanism: 0
Invalid mechanism values: 0
LEGITIMATE records with non-NONE mechanism: 0
IMPERSONATION records with NONE mechanism: 0

Total invalid records: 0

PASS — impersonation_mechanism is consistent with label.

In [81]:
# CHECK 28 — SCENARIO FAMILY ↔ LABEL CONSISTENCY

scenario = (
    df2["scenario_family"]
    .astype(str)
    .str.strip()
)

label = (
    df2["label"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Missing / blank
missing_scenario = (
    df2["scenario_family"].isna()
    | scenario.eq("")
)

# Valid prefix
invalid_prefix = ~scenario.str.startswith(("LEGIT/", "IMP/"))

# LEGIT scenario must have LEGITIMATE label
legit_label_mismatch = (
    scenario.str.startswith("LEGIT/")
    & (label != "LEGITIMATE")
)

# IMP scenario must have IMPERSONATION label
imp_label_mismatch = (
    scenario.str.startswith("IMP/")
    & (label != "IMPERSONATION")
)

total_invalid = (
    missing_scenario
    | invalid_prefix
    | legit_label_mismatch
    | imp_label_mismatch
)

print("Missing scenario_family:", missing_scenario.sum())
print("Invalid scenario_family prefix:", invalid_prefix.sum())
print("LEGIT scenario / wrong label:", legit_label_mismatch.sum())
print("IMP scenario / wrong label:", imp_label_mismatch.sum())

print("\nTotal invalid records:", total_invalid.sum())

if total_invalid.sum() == 0:
    print("\nPASS — scenario_family is consistent with label.")
else:
    print("\nFAIL — scenario_family inconsistencies found.")

    print(
        df2.loc[
            total_invalid,
            [
                "message_id",
                "identity_id",
                "label",
                "scenario_family"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Missing scenario_family: 0
Invalid scenario_family prefix: 0
LEGIT scenario / wrong label: 0
IMP scenario / wrong label: 0

Total invalid records: 0

PASS — scenario_family is consistent with label.

In [82]:
# CHECK 29 — REQUEST CATEGORY VALIDATION

valid_request_categories = {
    "access",
    "approval",
    "bank",
    "channel",
    "data",
    "deadline",
    "document",
    "favour",
    "meeting",
    "payment"
}

request_category = (
    df2["request_category"]
    .astype(str)
    .str.strip()
)

missing_category = (
    df2["request_category"].isna()
    | request_category.eq("")
)

invalid_category = ~request_category.isin(
    valid_request_categories
)

print("Missing request_category:", missing_category.sum())
print("Invalid request_category values:", invalid_category.sum())

print("\nCategory distribution:")
print(
    df2["request_category"]
    .value_counts()
    .sort_index()
)

print("\nCategory × Label:")
print(
    pd.crosstab(
        df2["request_category"],
        df2["label"]
    )
)

if missing_category.sum() == 0 and invalid_category.sum() == 0:
    print("\nPASS — request_category values are valid.")
else:
    print("\nFAIL — request_category issues found.")
    
    print(
        df2.loc[
            missing_category | invalid_category,
            [
                "message_id",
                "identity_id",
                "label",
                "request_category"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Missing request_category: 0
Invalid request_category values: 0

Category distribution:
request_category
access       987
approval     903
bank         997
channel      814
data         995
deadline    1066
document    1166
favour       733
meeting     1186
payment     1153
Name: count, dtype: int64

Category × Label:
label             IMPERSONATION  LEGITIMATE
request_category
access                      487         500
approval                    403         500
bank                        497         500
channel                     314         500
data                        495         500
deadline                    566         500
document                    666         500
favour                      233         500
meeting                     686         500
payment                     653         500

PASS — request_category values are valid.

In [83]:
# CHECK 30 — LABEL AND REQUEST CATEGORY COVERAGE

valid_labels = {
    "LEGITIMATE",
    "IMPERSONATION"
}

labels = (
    df2["label"]
    .astype(str)
    .str.strip()
    .str.upper()
)

invalid_labels = ~labels.isin(valid_labels)

# Build category × label table
coverage = pd.crosstab(
    df2["request_category"],
    labels
)

expected_categories = sorted(valid_request_categories)

# Check that every category exists in both labels
missing_legitimate = [
    cat for cat in expected_categories
    if coverage.get("LEGITIMATE", pd.Series()).get(cat, 0) == 0
]

missing_impersonation = [
    cat for cat in expected_categories
    if coverage.get("IMPERSONATION", pd.Series()).get(cat, 0) == 0
]

print("Invalid label values:", invalid_labels.sum())
print("Categories missing LEGITIMATE records:", missing_legitimate)
print("Categories missing IMPERSONATION records:", missing_impersonation)

print("\nCoverage table:")
print(coverage)

if (
    invalid_labels.sum() == 0
    and len(missing_legitimate) == 0
    and len(missing_impersonation) == 0
):
    print("\nPASS — All request categories are represented in both labels.")
else:
    print("\nFAIL — Label/category coverage issue found.")

Invalid label values: 0
Categories missing LEGITIMATE records: []
Categories missing IMPERSONATION records: []

Coverage table:
label             IMPERSONATION  LEGITIMATE
request_category
access                      487         500
approval                    403         500
bank                        497         500
channel                     314         500
data                        495         500
deadline                    566         500
document                    666         500
favour                      233         500
meeting                     686         500
payment                     653         500

PASS — All request categories are represented in both labels.

In [84]:
# CHECK 31 — DOMAIN_MATCH FINAL VERIFICATION

# Sender domain
sender_domain = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Dataset 1 authoritative domain
expected_domain = (
    df2["identity_id"]
    .map(df1_map["official_domain"])
    .astype(str)
    .str.strip()
    .str.lower()
)

# Expected boolean value
expected_domain_match = (
    sender_domain == expected_domain
)

# Normalize stored value
stored_domain_match = (
    df2["domain_match"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": True,
        "false": False
    })
)

# Compare
mismatch = (
    stored_domain_match != expected_domain_match
)

print("Total records:", len(df2))
print("Stored domain_match TRUE:", (stored_domain_match == True).sum())
print("Stored domain_match FALSE:", (stored_domain_match == False).sum())
print("domain_match inconsistencies:", mismatch.sum())

if mismatch.sum() == 0:
    print("\nPASS — domain_match is completely consistent.")
else:
    print("\nFAIL — domain_match inconsistencies found.")

    print(
        df2.loc[
            mismatch,
            [
                "message_id",
                "identity_id",
                "sender_email",
                "domain_match"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Total records: 10000
Stored domain_match TRUE: 4467
Stored domain_match FALSE: 5533
domain_match inconsistencies: 0

PASS — domain_match is completely consistent.

In [86]:
# CHECK 32 — REPLY_TO_MATCH FINAL VERIFICATION

# Normalize sender domain
sender_domain = (
    df2["sender_email"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.split("@")
    .str[-1]
)

# Normalize reply_to
reply_to_clean = (
    df2["reply_to"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Extract Reply-To domain
reply_domain = (
    reply_to_clean
    .str.split("@")
    .str[-1]
)

# Records with Reply-To
has_reply_to = (
    df2["reply_to"].notna()
    & reply_to_clean.ne("")
    & reply_to_clean.ne("nan")
)

# Expected value
expected_reply_match = (
    sender_domain == reply_domain
)

# Stored value
stored_reply_match = (
    df2["reply_to_match"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": True,
        "false": False
    })
)

# Check only records where Reply-To exists
mismatch = (
    has_reply_to
    & (stored_reply_match != expected_reply_match)
)

print("Records with Reply-To:", has_reply_to.sum())
print("Stored reply_to_match TRUE:", (stored_reply_match == True).sum())
print("Stored reply_to_match FALSE:", (stored_reply_match == False).sum())
print("reply_to_match inconsistencies:", mismatch.sum())

if mismatch.sum() == 0:
    print("\nPASS — reply_to_match is completely consistent.")
else:
    print("\nFAIL — reply_to_match inconsistencies found.")

    print(
        df2.loc[
            mismatch,
            [
                "message_id",
                "identity_id",
                "label",
                "sender_email",
                "reply_to",
                "reply_to_match"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Records with Reply-To: 1890
Stored reply_to_match TRUE: 8600
Stored reply_to_match FALSE: 1400
reply_to_match inconsistencies: 0

PASS — reply_to_match is completely consistent.

In [87]:
# CHECK 33 — CLEAN TEMPORARY VALIDATION COLUMNS

temp_cols = [
    "_label_check",
    "_relationship_check",
    "_attack_type_check",
    "_mechanism_check",
    "expected_email",
    "expected_domain",
    "sender_email_clean",
    "sender_domain",
    "expected_domain_clean",
    "sender_name_clean",
    "identity_name_clean",
    "identity_name_normalized",
    "sender_name_normalized",
    "identity_name_normalized_v2",
    "sender_name_normalized_v2",
    "expected_email_clean"
]

existing_temp_cols = [
    col for col in temp_cols
    if col in df2.columns
]

df2.drop(
    columns=existing_temp_cols,
    inplace=True
)

print("Temporary validation columns removed:", existing_temp_cols)
print("Current Dataset 2 shape:", df2.shape)

print("\nCurrent columns:")
print(df2.columns.tolist())

Temporary validation columns removed: ['_label_check', '_relationship_check', '_attack_type_check', '_mechanism_check']
Current Dataset 2 shape: (10000, 34)

Current columns:
['message_id', 'identity_id', 'identity_name', 'identity_role', 'organization', 'organization_type', 'organization_domain', 'sender_name', 'sender_email', 'receiver_name', 'receiver_email', 'reply_to', 'date', 'subject', 'message', 'label', 'attack_type', 'impersonation_mechanism', 'sender_relationship', 'scenario_family', 'request_category', 'domain_match', 'reply_to_match', 'risk_signals', 'urgency_level', 'has_link', 'has_attachment', 'link_domain_class', 'data_type', 'generation_version', 'generation_batch', 'generator_type', 'generation_seed', 'research_source']

In [88]:
# CHECK 34 — DATE VALIDATION

date_clean = (
    df2["date"]
    .astype(str)
    .str.strip()
)

missing_date = (
    df2["date"].isna()
    | date_clean.eq("")
    | date_clean.eq("nan")
)

parsed_dates = pd.to_datetime(
    df2["date"],
    errors="coerce"
)

invalid_date = (
    ~missing_date
    & parsed_dates.isna()
)

print("Total records:", len(df2))
print("Missing/blank dates:", missing_date.sum())
print("Invalid/unparseable dates:", invalid_date.sum())

if missing_date.sum() == 0 and invalid_date.sum() == 0:
    print("\nPASS — All date values are valid.")
    
    print("\nDate range:")
    print("Minimum:", parsed_dates.min())
    print("Maximum:", parsed_dates.max())
else:
    print("\nFAIL — Date issues found.")
    
    print(
        df2.loc[
            missing_date | invalid_date,
            [
                "message_id",
                "identity_id",
                "date"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Total records: 10000
Missing/blank dates: 0
Invalid/unparseable dates: 0

PASS — All date values are valid.

Date range:
Minimum: 2025-01-01 06:35:00+00:00
Maximum: 2026-02-04 22:25:00+00:00

In [89]:
# CHECK 35 — SUBJECT AND MESSAGE COMPLETENESS

subject_clean = (
    df2["subject"]
    .astype(str)
    .str.strip()
)

message_clean = (
    df2["message"]
    .astype(str)
    .str.strip()
)

missing_subject = (
    df2["subject"].isna()
    | subject_clean.eq("")
    | subject_clean.eq("nan")
)

missing_message = (
    df2["message"].isna()
    | message_clean.eq("")
    | message_clean.eq("nan")
)

print("Total records:", len(df2))
print("Missing/blank subject:", missing_subject.sum())
print("Missing/blank message:", missing_message.sum())

print("\nMessage length statistics:")
print(message_clean.str.len().describe())

if missing_subject.sum() == 0 and missing_message.sum() == 0:
    print("\nPASS — All subjects and messages are present.")
else:
    print("\nFAIL — Subject/message completeness issues found.")

    print(
        df2.loc[
            missing_subject | missing_message,
            [
                "message_id",
                "identity_id",
                "label",
                "subject",
                "message"
            ]
        ]
        .head(100)
        .to_string(index=False)
    )

Total records: 10000
Missing/blank subject: 0
Missing/blank message: 0

Message length statistics:
count    10000.000000
mean       436.237200
std         80.807941
min        190.000000
25%        379.000000
50%        434.000000
75%        490.000000
max        724.000000
Name: message, dtype: float64

PASS — All subjects and messages are present.